#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installGNU();

print "Installing project file\n";
install( "${src}/template-cppgenerichello/app.kdevelop",     "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-cppgenerichello/app.prj",         "${dest}/${APPNAMELC}.prj" );


print "Installing application sources\n";
install( "${src}/template-cppgenerichello/main.cpp",         "${dest}/src/${APPNAMELC}.cpp" );

print "Finished\n";
