[Desktop Entry]
Type=Service
Name=QMake Project Builder
Name[bs]=QMake graditelj projekata
Name[ca]=Constructor de projecte QMake
Name[ca@valencia]=Constructor de projecte QMake
Name[de]=Ersteller für QMake-Projekte
Name[en_GB]=QMake Project Builder
Name[es]=Constructor de proyectos QMake
Name[et]=QMake'i projekti ehitaja
Name[fr]=Constructeur de projets QMake
Name[ga]=Tógálaí Tionscadail QMake
Name[hu]=QMake projektfordító
Name[it]=Creatore di progetti per QMake
Name[nds]=QMake-Projektbuumoduul
Name[nl]=QMake-projectbouwer
Name[pl]=Budowanie projektu QMake
Name[pt]=Construtor de Projectos do QMake
Name[pt_BR]=Construtor de projetos do QMake
Name[sk]=Prekladač projektov QMake
Name[sv]=Bygg QMake-projekt
Name[tr]=QMake Proje Oluşturucu
Name[uk]=Інструмент збирання проектів QMake
Name[x-test]=xxQMake Project Builderxx
Comment=Builds QMake Projects
Comment[bs]=Gradi QMake Projekte
Comment[ca]=Construeix projectes QMake
Comment[ca@valencia]=Construeix projectes QMake
Comment[de]=Erstellt QMake-Projekte
Comment[en_GB]=Builds QMake Projects
Comment[es]=Construye proyectos de QMake
Comment[et]=QMake'i projektide ehitamine
Comment[fr]=Construit des projets QMake
Comment[ga]=Tóg tionscadail QMake
Comment[hu]=QMake projektek fordítása
Comment[it]=Crea progetti QMake
Comment[nds]=Buut QMake-Projekten
Comment[nl]=Bouwt QMake-projecten
Comment[pl]=Buduje projekty QMake
Comment[pt]=Compila projectos do QMake
Comment[pt_BR]=Compila projetos do QMake
Comment[sk]=Prekladá projekty QMake
Comment[sv]=Bygger QMake-projekt
Comment[tr]=QMake Projelerini İnşa Eder
Comment[uk]=Збирає проекти QMake
Comment[x-test]=xxBuilds QMake Projectsxx
Icon=gear
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevqmakebuilder
X-KDE-PluginInfo-Name=KDevQMakeBuilder
X-KDevelop-ProjectBuilder=QMake
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Project
X-KDevelop-Interfaces=org.kdevelop.IQMakeBuilder
X-KDevelop-IRequired=org.kdevelop.IOutputView,org.kdevelop.IMakeBuilder
X-KDevelop-Mode=NoGUI
