#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installGNU();
installDocbook();
installWX();

print "Installing project file\n";
install( "${src}/template-wxhello/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-common/wx-Makefile.am",      "${dest}/Makefile.am");
install( "${src}/template-common/wx-Makefile.cvs",     "${dest}/Makefile.cvs");
install( "${src}/template-common/wx-configure.in",     "${dest}/configure.in");
install( "${src}/template-common/hi16-app-app.png",    "${dest}/src/hi16-app-${APPNAMELC}.png");
install( "${src}/template-common/hi32-app-app.png",    "${dest}/src/hi32-app-${APPNAMELC}.png");
install( "${src}/template-wxhello/subdirs",            "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-wxhello/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-wxhello/app.cpp",           "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-wxhello/app.h",             "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-wxhello/app.desktop",       "${dest}/src/${APPNAMELC}.desktop" );

print "Finished\n";
