#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
# install the kdevelop project file
install( "${src}/template-khello2/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application\n";
# set permissions
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
# install files needed by automake & friends.
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-khello2/subdirs",             "${dest}/subdirs" );
install( "${src}/template-common/kde-app.lsm",         "${dest}/src/${APPNAMELC}.lsm" );
# install application images
install( "${src}/template-common/hi16-app-app.png",    "${dest}/src/hi16-app-${APPNAMELC}.png");
install( "${src}/template-common/hi32-app-app.png",    "${dest}/src/hi32-app-${APPNAMELC}.png");

print "Installing application sources\n";
# install src/Makefile.am
install( "${src}/template-khello2/src-Makefile.am",   "${dest}/src/Makefile.am" );
# install sources
install( "${src}/template-khello2/app.cpp",           "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-khello2/app.h",             "${dest}/src/${APPNAMELC}.h" );

install( "${src}/template-khello2/widget.cpp",        "${dest}/src/${APPNAMELC}widget.cpp" );
install( "${src}/template-khello2/widget.h",          "${dest}/src/${APPNAMELC}widget.h" );
install( "${src}/template-khello2/widgetbase.ui",     "${dest}/src/${APPNAMELC}widgetbase.ui" );

install( "${src}/template-khello2/main.cpp",          "${dest}/src/main.cpp" );
install( "${src}/template-khello2/appui.rc",          "${dest}/src/${APPNAMELC}ui.rc" );
install( "${src}/template-khello2/app.desktop",       "${dest}/src/${APPNAMELC}.desktop" );

print "Finished\n";
