#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();

print "Installing project file\n";
install( "${src}/template-chellogba/app.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );
install( "${src}/template-chellogba/README.devel",    "${dest}/README.devel" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-chellogba/c-Makefile.am",   "${dest}/Makefile.am" );
install( "${src}/template-chellogba/c-Makefile.cvs",  "${dest}/Makefile.cvs" );
install( "${src}/template-chellogba/configure.in",    "${dest}/configure.in" );


print "Installing application sources\n";
install( "${src}/template-chellogba/src-Makefile.am", "${dest}/src/Makefile.am" );
install( "${src}/template-chellogba/main.c",          "${dest}/src/main.c" );
install( "${src}/template-chellogba/main.h",          "${dest}/src/main.h" );
install( "${src}/template-chellogba/gba.h",          "${dest}/src/gba.h" );
install( "${src}/template-chellogba/font.bmp",          "${dest}/src/font.bmp" );
install( "${src}/template-chellogba/font.raw.c",          "${dest}/src/font.raw.c" );
install( "${src}/template-chellogba/master.pal.c",          "${dest}/src/master.pal.c" );


print "Finished\n";
