#!/bin/sh

echo "running aclocal..."
aclocal
echo "running autoheader..."
autoheader
echo "running automake..."
automake
echo "running automoc..."
perl automoc
echo "running autoconf..."
autoconf
echo "running configure..."
./configure

