#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();

print "Installing project file\n";
install( "${src}/template-opiemenu/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/pics", 0777 );
mkdir( "${dest}/pics/${APPNAMELC}", 0777 );
mkdir( "${dest}/sounds", 0777 );
mkdir( "${dest}/sounds/${APPNAMELC}", 0777 );
mkdir( "${dest}/i18n", 0777 );

print "Installing application sources\n";
install( "${src}/template-opiemenu/Example.png", "${dest}/pics/${APPNAMELC}/${APPNAMELC}.png" );
install( "${src}/template-opiemenu/app.pro", "${dest}/${APPNAMELC}.pro" );
install( "${src}/template-opiemenu/simpleimpl.cpp", "${dest}/${APPNAMELC}.cpp" );
install( "${src}/template-opiemenu/simpleimpl.h", "${dest}/${APPNAMELC}.h" );

print "Finished\n";
