#!perl -I/usr/kde/3.1/share/apps/kdevappwizard/template-common

use kdevelop;

initKDevelop();

print "Installing project file\n";
install( "${src}/template-bashhello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-bashhello/app.sh",       "${dest}/${APPNAMELC}.sh" );

print "Finished\n";
