# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision$
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../../..
prefix = /usr/kde
exec_prefix = ${prefix}

bindir = /usr/kde/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/kdevelop
pkglibdir = $(libdir)/kdevelop
pkgincludedir = $(includedir)/kdevelop

top_builddir = ../../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/local/bin/ginstall -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnulibc1
build_triplet = i686-pc-linux-gnulibc1
host_alias = i686-pc-linux-gnulibc1
host_triplet = i686-pc-linux-gnulibc1
target_alias = @target_alias@
target_triplet = @target@
AS = 
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DLLTOOL = 
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/local/bin/msgfmt
IDL = @IDL@
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/usr/kde/include
KDE_LDFLAGS = -L/usr/kde/lib
KDE_RPATH = -rpath $(kde_libraries) -rpath $(qt_libraries) -rpath $(x_libraries)
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
LD = /usr/local/bin/ld
LEX = flex
LIBCOMPAT = 
LIBCRYPT = 
LIBDL = @LIBDL@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBSOCKET = 
LIBTIFF = -ltiff -ljpeg -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIBUCB = 
LIBUTIL = @LIBUTIL@
LIBXDMCP = @LIBXDMCP@
LIBZ = -lz
LIB_KAB = -lkab $(LIB_KIMGIO) $(LIB_KDECORE)
LIB_KDECORE = -lkdecore -lXext $(LIB_QT)
LIB_KDEUI = -lkdeui $(LIB_KDECORE)
LIB_KDEUTIL = @LIB_KDEUTIL@
LIB_KFILE = -lkfile $(LIB_KFM) $(LIB_KDEUI)
LIB_KFM = -lkfm $(LIB_KDECORE)
LIB_KHTML = -lkhtml $(LIB_KIMGIO) -ljscript
LIB_KHTMLW = -lkhtmlw $(LIB_KIMGIO) -ljscript
LIB_KIMGIO = -lkimgio $(LIBJPEG) $(LIBTIFF) $(LIBPNG) $(LIB_QT) -lm
LIB_KIO = @LIB_KIO@
LIB_LIBS = @LIB_LIBS@
LIB_MEDIATOOL = -lmediatool $(LIB_KDECORE)
LIB_QT = -lqt $(LIBPNG) $(LIB_X11)
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/qt/bin/moc
MSGFMT = /usr/local/bin/msgfmt
NM = /usr/local/bin/nm -B
PACKAGE = kdevelop
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PASSWDLIB = @PASSWDLIB@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = -I/usr/qt/include
QT_LDFLAGS = -L/usr/qt/lib
RANLIB = ranlib
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_NLS = yes
USE_SYMBOL_UNDERSCORE = no
VERSION = 1.0 Beta 1
XBINDIR = @XBINDIR@
XGETTEXT = /usr/local/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_SERVER = @X_SERVER@
ac_xdmdir = @ac_xdmdir@
all_includes = -I/usr/kde/include -I/usr/qt/include  -I/usr/X11R6/include
all_libraries = -L/usr/kde/lib -L/usr/qt/lib  -L/usr/X11R6/lib
idldir = @idldir@
install_root = 
kde_appsdir = /usr/kde/share/applnk
kde_bindir = /usr/kde/bin
kde_cgidir = /usr/kde/cgi-bin
kde_confdir = /usr/kde/share/config
kde_datadir = /usr/kde/share/apps
kde_htmldir = /usr/kde/share/doc/HTML
kde_icondir = /usr/kde/share/icons
kde_includes = /usr/kde/include
kde_libraries = /usr/kde/lib
kde_locale = /usr/kde/share/locale
kde_mimedir = /usr/kde/share/mimelnk
kde_minidir = /usr/kde/share/icons/mini
kde_partsdir = /usr/kde/parts
kde_sounddir = /usr/kde/share/sounds
kde_toolbardir = /usr/kde/share/toolbar
kde_wallpaperdir = /usr/kde/share/wallpapers
qt_includes = /usr/qt/include
qt_libraries = /usr/qt/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib
xdmconfigsubdir = @xdmconfigsubdir@

EXTRA_DIST = index.sgml logotp3.png             index.html index-1.html index-2.html index-3.html index-4.html index-5.html index-6.html index-7.html             index-8.html index-9.html index-10.html index-11.html index-12.html index-13.html index-14.html  index-15.html             index-16.html

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../../config.h
CONFIG_CLEAN_FILES = 
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu doc/pt/manual/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu doc/pt/manual/Makefile
	cd $(top_srcdir) && perl am_edit doc/pt/manual/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = doc/pt/manual

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu doc/pt/manual/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-local
uninstall: uninstall-am
all-am: Makefile
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-local install-data-am install-data install-am install \
uninstall-local uninstall-am uninstall all-redirect all-am all \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


install-data-local:
#>- 	$(mkinstalldirs) $(kde_htmldir)/pt/kdevelop
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(kde_htmldir)/pt/kdevelop
#>- 	$(INSTALL_DATA) logotp3.png $(kde_htmldir)/pt/kdevelop/logotp3.png
#>+ 1
	$(INSTALL_DATA) logotp3.png $(DESTDIR)$(kde_htmldir)/pt/kdevelop/logotp3.png
#>- 	$(INSTALL_DATA) index.html $(kde_htmldir)/pt/kdevelop/index.html
#>+ 1
	$(INSTALL_DATA) index.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index.html
#>- 	$(INSTALL_DATA) index-1.html $(kde_htmldir)/pt/kdevelop/index-1.html
#>+ 1
	$(INSTALL_DATA) index-1.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-1.html
#>- 	$(INSTALL_DATA) index-2.html $(kde_htmldir)/pt/kdevelop/index-2.html
#>+ 1
	$(INSTALL_DATA) index-2.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-2.html
#>- 	$(INSTALL_DATA) index-3.html $(kde_htmldir)/pt/kdevelop/index-3.html
#>+ 1
	$(INSTALL_DATA) index-3.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-3.html
#>- 	$(INSTALL_DATA) index-4.html $(kde_htmldir)/pt/kdevelop/index-4.html
#>+ 1
	$(INSTALL_DATA) index-4.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-4.html
#>- 	$(INSTALL_DATA) index-5.html $(kde_htmldir)/pt/kdevelop/index-5.html
#>+ 1
	$(INSTALL_DATA) index-5.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-5.html
#>- 	$(INSTALL_DATA) index-6.html $(kde_htmldir)/pt/kdevelop/index-6.html
#>+ 1
	$(INSTALL_DATA) index-6.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-6.html
#>- 	$(INSTALL_DATA) index-7.html $(kde_htmldir)/pt/kdevelop/index-7.html
#>+ 1
	$(INSTALL_DATA) index-7.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-7.html
#>- 	$(INSTALL_DATA) index-8.html $(kde_htmldir)/pt/kdevelop/index-8.html
#>+ 1
	$(INSTALL_DATA) index-8.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-8.html
#>- 	$(INSTALL_DATA) index-9.html $(kde_htmldir)/pt/kdevelop/index-9.html
#>+ 1
	$(INSTALL_DATA) index-9.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-9.html
#>- 	$(INSTALL_DATA) index-10.html $(kde_htmldir)/pt/kdevelop/index-10.html
#>+ 1
	$(INSTALL_DATA) index-10.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-10.html
#>- 	$(INSTALL_DATA) index-11.html $(kde_htmldir)/pt/kdevelop/index-11.html
#>+ 1
	$(INSTALL_DATA) index-11.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-11.html
#>- 	$(INSTALL_DATA) index-12.html $(kde_htmldir)/pt/kdevelop/index-12.html
#>+ 1
	$(INSTALL_DATA) index-12.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-12.html
#>- 	$(INSTALL_DATA) index-13.html $(kde_htmldir)/pt/kdevelop/index-13.html
#>+ 1
	$(INSTALL_DATA) index-13.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-13.html
#>- 	$(INSTALL_DATA) index-14.html $(kde_htmldir)/pt/kdevelop/index-14.html
#>+ 1
	$(INSTALL_DATA) index-14.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-14.html
#>- 	$(INSTALL_DATA) index-15.html $(kde_htmldir)/pt/kdevelop/index-15.html
#>+ 1
	$(INSTALL_DATA) index-15.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-15.html
#>- 	$(INSTALL_DATA) index-16.html $(kde_htmldir)/pt/kdevelop/index-16.html
#>+ 1
	$(INSTALL_DATA) index-16.html $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-16.html

uninstall-local:
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/logotp3.png
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/logotp3.png
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-1.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-1.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-2.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-2.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-3.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-3.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-4.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-4.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-5.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-5.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-6.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-6.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-7.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-7.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-8.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-8.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-9.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-9.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-10.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-10.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-11.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-11.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-12.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-12.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-13.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-13.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-14.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-14.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-15.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-15.html
#>- 	-rm -f $(kde_htmldir)/pt/kdevelop/index-16.html
#>+ 1
	-rm -f $(DESTDIR)$(kde_htmldir)/pt/kdevelop/index-16.html

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu doc/pt/manual/Makefile
	cd $(top_srcdir) && perl am_edit doc/pt/manual/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean
