#!/usr/bin/perl

use gideon;

initGideon();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kioslave/slave.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-app.lsm",             "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kioslave/subdirs",           "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kioslave/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-kioslave/slave.cpp",         "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-kioslave/slave.h",           "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-kioslave/slave.protocol",    "${dest}/src/${APPNAMELC}.protocol" );

print "Finished\n";
