#ifndef KROSSDUCONTEXT_H
#define KROSSDUCONTEXT_H

#include<QtCore/QVariant>

//This is file has been generated by xmltokross, you should not edit this file but the files used to generate it.

namespace KDevelop { class IndexedDUContext; }
namespace KDevelop { class LocalIndexedDUContext; }
namespace KDevelop { class ImportTraceItem; }
namespace KDevelop { class DUContext; }
namespace KDevelop { class Import; }
namespace KDevelop { class SearchItem; }
namespace Handlers
{
	QVariant _kDevelopDUContextSearchItemHandler(void* type);
	QVariant kDevelopDUContextSearchItemHandler(KDevelop::DUContext::SearchItem* type);
	QVariant kDevelopDUContextSearchItemHandler(const KDevelop::DUContext::SearchItem* type);

	QVariant _kDevelopDUContextImportHandler(void* type);
	QVariant kDevelopDUContextImportHandler(KDevelop::DUContext::Import* type);
	QVariant kDevelopDUContextImportHandler(const KDevelop::DUContext::Import* type);

	QVariant _kDevelopDUContextHandler(void* type);
	QVariant kDevelopDUContextHandler(KDevelop::DUContext* type);
	QVariant kDevelopDUContextHandler(const KDevelop::DUContext* type);

	QVariant _kDevelopImportTraceItemHandler(void* type);
	QVariant kDevelopImportTraceItemHandler(KDevelop::ImportTraceItem* type);
	QVariant kDevelopImportTraceItemHandler(const KDevelop::ImportTraceItem* type);

	QVariant _kDevelopLocalIndexedDUContextHandler(void* type);
	QVariant kDevelopLocalIndexedDUContextHandler(KDevelop::LocalIndexedDUContext* type);
	QVariant kDevelopLocalIndexedDUContextHandler(const KDevelop::LocalIndexedDUContext* type);

	QVariant _kDevelopIndexedDUContextHandler(void* type);
	QVariant kDevelopIndexedDUContextHandler(KDevelop::IndexedDUContext* type);
	QVariant kDevelopIndexedDUContextHandler(const KDevelop::IndexedDUContext* type);

}

#endif
