#ifndef KROSSDUCHAINLOCK_H
#define KROSSDUCHAINLOCK_H

#include<QtCore/QVariant>

//This is file has been generated by xmltokross, you should not edit this file but the files used to generate it.

namespace KDevelop { class DUChainLock; }
namespace KDevelop { class DUChainReadLocker; }
namespace KDevelop { class DUChainWriteLocker; }
namespace Handlers
{
	QVariant _kDevelopDUChainLockHandler(void* type);
	QVariant kDevelopDUChainLockHandler(KDevelop::DUChainLock* type) { return _kDevelopDUChainLockHandler((void*) type); }
	QVariant kDevelopDUChainLockHandler(const KDevelop::DUChainLock* type) { return _kDevelopDUChainLockHandler((void*) type); }

	QVariant _kDevelopDUChainReadLockerHandler(void* type);
	QVariant kDevelopDUChainReadLockerHandler(KDevelop::DUChainReadLocker* type) { return _kDevelopDUChainReadLockerHandler((void*) type); }
	QVariant kDevelopDUChainReadLockerHandler(const KDevelop::DUChainReadLocker* type) { return _kDevelopDUChainReadLockerHandler((void*) type); }

	QVariant _kDevelopDUChainWriteLockerHandler(void* type);
	QVariant kDevelopDUChainWriteLockerHandler(KDevelop::DUChainWriteLocker* type) { return _kDevelopDUChainWriteLockerHandler((void*) type); }
	QVariant kDevelopDUChainWriteLockerHandler(const KDevelop::DUChainWriteLocker* type) { return _kDevelopDUChainWriteLockerHandler((void*) type); }

}

#endif
