#ifndef KDEVSOURCEFORMATTER_EXPORT_H
#define KDEVSOURCEFORMATTER_EXPORT_H

// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>

#ifndef KDEVSOURCEFORMATTER_EXPORT
# if defined(MAKE_KDEVSOURCEFORMATTER_LIB)
// We are building this library
#  define KDEVSOURCEFORMATTER_EXPORT KDE_EXPORT
# else
// We are using this library
#  define KDEVSOURCEFORMATTER_EXPORT KDE_IMPORT
# endif
#endif

# ifndef KDEVSOURCEFORMATTER_EXPORT_DEPRECATED
#  define KDEVSOURCEFORMATTER_EXPORT_DEPRECATED KDE_DEPRECATED KDEVSOURCEFORMATTER_EXPORT
# endif

#endif
