#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kopart/kopart.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-app.lsm",             "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-kopart/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kopart/subdirs",           "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kopart/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-kopart/kopart_view.cpp",         "${dest}/src/${APPNAMELC}_view.cpp" );
install( "${src}/template-kopart/kopart_view.h",           "${dest}/src/${APPNAMELC}_view.h" );
install( "${src}/template-kopart/kopart_part.cpp",         "${dest}/src/${APPNAMELC}_part.cpp" );
install( "${src}/template-kopart/kopart_part.h",           "${dest}/src/${APPNAMELC}_part.h" );
install( "${src}/template-kopart/kopart_factory.cpp",         "${dest}/src/${APPNAMELC}_factory.cpp" );
install( "${src}/template-kopart/kopart_factory.h",           "${dest}/src/${APPNAMELC}_factory.h" );
install( "${src}/template-kopart/kopart_aboutdata.h",           "${dest}/src/${APPNAMELC}_aboutdata.h" );
install( "${src}/template-kopart/kopart.rc",         "${dest}/src/${APPNAMELC}.rc" );
install( "${src}/template-kopart/kopart.desktop",         "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-kopart/x-kopart.desktop",         "${dest}/src/x-${APPNAMELC}.desktop" );
install( "${src}/template-kopart/main.cpp",         "${dest}/src/x-${APPNAMELC}.cpp" );

print "Finished\n";
