#!/usr/bin/perl

use gideon;

initGideon();
installFileTemplate();
installLicense();

print "Installing project file\n";
installHTML( "${src}/template-qtopiaapp/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/bin", 0777 );

print "Installing application sources\n";
install( "${src}/template-qtopiaapp/Example.png", "${dest}/${APPNAME}.png" );
install( "${src}/template-qtopiaapp/app.pro", "${dest}/${APPNAMELC}.pro" );
install( "${src}/template-qtopiaapp/example.cpp", "${dest}/${APPNAMELC}.cpp" );
install( "${src}/template-qtopiaapp/example.h", "${dest}/${APPNAMELC}.h" );
install( "${src}/template-qtopiaapp/examplebase.ui", "${dest}/${APPNAMELC}base.ui" );
install( "${src}/template-qtopiaapp/example.control", "${dest}/${APPNAMELC}.control" );
install( "${src}/template-qtopiaapp/example.desktop", "${dest}/${APPNAMELC}.desktop" );
install( "${src}/template-qtopiaapp/example.html", "${dest}/${APPNAMELC}.html" );
install( "${src}/template-qtopiaapp/main.cpp", "${dest}/main.cpp" );

print "Finished\n";
