#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installGNU();

print "Installing project file\n";
install( "${src}/template-prc-tool/prc-tool.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
install( "${src}/template-prc-tool/src-Makefile",   "${dest}/Makefile" );

print "Installing application sources\n";
install( "${src}/template-prc-tool/palmhello.c",          "${dest}/${APPNAME}.c" );
install( "${src}/template-prc-tool/palmhello.pbitm",	"${dest}/${APPNAME}.pbitm" );
install( "${src}/template-prc-tool/palmhello.rcp",	"${dest}/${APPNAME}.rcp");
install( "${src}/template-prc-tool/palmhelloRsc.h",	"${dest}/${APPNAME}Rsc.h");
install( "${src}/template-prc-tool/callback.h",		"${dest}/callback.h" );
print "Finished\n";
