# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kitemmodels': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/threadweaver': '@stable'
    'sdk/libkomparediff2': '@same'
    'utilities/okteta': '@stable'
    'kdevelop/kdevelop-pg-qt': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/libksysguard': '@stable'

Options:
  cppcheck-ignore-files:
    # Windows CI nodes are killed by the OOM killer, because cppcheck
    # uses far in excess of 8GB of RAM when it tries to process file
    # plugins/clang/tests/files/kdev_ignored/mangle-ms-back-references-pr13207.cpp
    # Disable checking the directory that contains this file until the cppcheck
    # bug is fixed and a fixed cppcheck version is installed on CI servers.
    - plugins/clang/tests/files/kdev_ignored/
