# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/ktexttemplate': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
    'frameworks/threadweaver': '@latest-kf6'
    'kdevelop/kdevelop-pg-qt': '@latest-kf6'
    'sdk/libkomparediff2': '@same'
    # TODO: Okteta Qt6 port not yet complete, ETA 10/2024 or later. Once available, adapt code & reenable again.
    # 'utilities/okteta': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/krunner': '@latest-kf6'
    'plasma/libksysguard': '@latest-kf6'
    'plasma/libplasma': '@latest-kf6'

Options:
  per-test-timeout: 200 # the 60-second default is not enough for test_gdb
  use-ccache: True
  # Verifying that benchmarks can be built is useful, but running them is wasteful and timeout-prone.
  # So tell ctest not to run benchmarks (whose names conveniently start with "bench_").
  ctest-arguments: '-E "^bench_"'
  allow-failing-tests-on: ['@all']
  gcovr-arguments: '--gcov-ignore-parse-errors=negative_hits.warn --gcov-ignore-parse-errors=suspicious_hits.warn'
