# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/threadweaver': '@latest-kf6'
    'sdk/libkomparediff2': '@same'
    'frameworks/purpose': '@latest-kf6'
    'frameworks/kdeclarative': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    # 'utilities/okteta': '@latest-kf6'
    'kdevelop/kdevelop-pg-qt': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/libksysguard': '@latest-kf6'

Options:
  per-test-timeout: 200 # the 60-second default is not enough for test_gdb
