#ifndef KDEVELOP_CONFIG_H
#define KDEVELOP_CONFIG_H

/* config.h.  Generated by cmake from config.h.cmake */

#define VERSION "3.9.0"

/* Valgrind presence */
#cmakedefine HAVE_VALGRIND_H 1

#endif //  KDEVELOP_CONFIG_H
