#ifndef KDEVELOP_CONFIG_H
#define KDEVELOP_CONFIG_H

/* config.h.  Generated by cmake from config.h.cmake */

#define VERSION "@KDEVELOP_VERSION_MAJOR@.@KDEVELOP_VERSION_MINOR@.@KDEVELOP_VERSION_PATCH@"

#endif //  KDEVELOP_CONFIG_H
