#ifndef CONFIG_KDEVELOP_H
#define CONFIG_KDEVELOP_H

/* config-kdevelop.h.  Generated by cmake from config-kdevelop.h.cmake */

#cmakedefine01 KDEVELOP_SINGLE_APP

#cmakedefine01 HAVE_KSYSGUARD

#endif // CONFIG_KDEVELOP_H
