[Desktop Entry]
Type=Service
Icon=text-x-c++src
Exec=blubb
Comment=C/C++ Language Support
Comment[bs]=C/C++  Jezička podrška
Comment[ca]=Implementació del llenguatge C/C++
Comment[ca@valencia]=Implementació del llenguatge C/C++
Comment[cs]=Podpora jazyka C/C++
Comment[de]=Sprachunterstützung für C/C++
Comment[es]=Uso de lenguaje C/C++
Comment[fi]=C/C++-kielituki
Comment[hu]=C/C++ nyelvi támogatás
Comment[nl]=Ondersteuning voor de talen C/C++
Comment[pl]=Obsługa języków C/C++
Comment[pt]=Suporte à Linguagem C/C++
Comment[pt_BR]=Suporte à linguagem C/C++
Comment[sk]=Podpora jazyka C/C++
Comment[sv]=Stöd för språken C och C++
Comment[uk]=Підтримка мови C/C++
Comment[x-test]=xxC/C++ Language Supportxx
Name=C++ Support
Name[bs]=C++ Podrška
Name[ca]=Implementació per a C++
Name[ca@valencia]=Implementació per a C++
Name[cs]=Podpora jazyka C++
Name[de]=Unterstützung für C++
Name[es]=Uso de C++
Name[fi]=C++-tuki
Name[hu]=C++ támogatás
Name[nl]=Ondersteuning voor C++
Name[pl]=Obsługa C++
Name[pt]=Suporte a C/C++
Name[pt_BR]=Suporte à C++
Name[sk]=Podpora C++
Name[sv]=C++ stöd
Name[uk]=Підтримка C++
Name[x-test]=xxC++ Supportxx
GenericName=Language Support
GenericName[bs]=Jezička podrška
GenericName[ca]=Implementació del llenguatge
GenericName[ca@valencia]=Implementació del llenguatge
GenericName[cs]=Podpora jazyků
GenericName[de]=Sprachunterstützung
GenericName[es]=Uso de lenguaje
GenericName[fi]=Kielituki
GenericName[hu]=Nyelvi támogatás
GenericName[nl]=Taalondersteuning
GenericName[pl]=Obsługa języków
GenericName[pt]=Suporte à Linguagem
GenericName[pt_BR]=Suporte à linguagem
GenericName[sk]=Podpora jazyka
GenericName[sv]=Språkstöd
GenericName[uk]=Підтримка мови
GenericName[x-test]=xxLanguage Supportxx
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevclangsupport
X-KDE-PluginInfo-Name=kdevclangsupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=C
X-KDevelop-Args=C
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=text/x-chdr,text/x-c++hdr,text/x-csrc,text/x-c++src
X-KDevelop-Mode=NoGUI
X-KDevelop-LoadMode=AlwaysOn
