[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=QML Language Support
Comment[bs]=QML jezička podrška
Comment[ca]=Implementació del llenguatge QML
Comment[cs]=Podpora jazyka QML
Comment[de]=Sprachunterstützung für QML
Comment[es]=Implementación del lenguaje QML
Comment[et]=QML-keele toetus
Comment[fi]=QML-kielituki
Comment[fr]=Prise en charge du langage QML
Comment[hu]=QML nyelvi támogatás
Comment[nl]=QML-taalondersteuning
Comment[pl]=Obsługa języka QML
Comment[pt]=Suporte para a Linguagem QML
Comment[pt_BR]=Suporte à linguagem QML
Comment[sk]=Podpora jazyka QML
Comment[sv]=QML-språkstöd
Comment[tr]=QML Dil Desteği
Comment[uk]=Підтримка мови QML
Comment[x-test]=xxQML Language Supportxx
Name=QML Support
Name[bs]=QML podrška
Name[ca]=Implementació per a QML
Name[cs]=Podpora QML
Name[de]=Unterstützung für QML
Name[es]=Implementación de QML
Name[et]=QML toetus
Name[fi]=QML-tuki
Name[fr]=Prise en charge de QML
Name[hu]=QML támogatás
Name[nl]=QML-ondersteuning
Name[pl]=Obsługa QML
Name[pt]=Suporte para QML
Name[pt_BR]=Suporte à QML
Name[sk]=Podpora QML
Name[sv]=QML-stöd
Name[tr]=QML Desteği
Name[uk]=Підтримка QML
Name[x-test]=xxQML Supportxx
GenericName=QML Support
GenericName[bs]=QML podrška
GenericName[ca]=Implementació per a QML
GenericName[cs]=Podpora QML
GenericName[de]=Unterstützung für QML
GenericName[es]=Implementación de QML
GenericName[et]=QML toetus
GenericName[fi]=QML-tuki
GenericName[fr]=Prise en charge de QML
GenericName[hu]=QML támogatás
GenericName[nl]=QML-ondersteuning
GenericName[pl]=Obsługa QML
GenericName[pt]=Suporte para QML
GenericName[pt_BR]=Suporte à QML
GenericName[sk]=Podpora QML
GenericName[sv]=QML-stöd
GenericName[tr]=QML Desteği
GenericName[uk]=Підтримка QML
GenericName[x-test]=xxQML Supportxx
ServiceTypes=KDevelop/Plugin
Icon=text-x-qml
X-KDE-Library=kdevqmljslanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=QML/JS
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=text/x-qml,application/javascript
X-KDE-PluginInfo-Name=KDevQmlJsSupport
X-KDevelop-Mode=NoGUI
X-KDE-PluginInfo-Category=Language Support
