[Desktop Entry]
Type=Service
Icon=kdevelop
Exec=blubb
Comment=Cppcheck is a tool that helps you find syntax problems in programs. http://cppcheck.sf.net/
Comment[bs]=Cppcheck je alat koji vam pmaže da nađete sintaksne probleme u programima. http://cppcheck.sf.net/
Comment[ca]=Cppcheck és una eina que us ajuda a trobar problemes de sintaxi en els programes. http://cppcheck.sf.net/
Comment[cs]=Cppcheck je nástroj jenž pomáhá s nalezením problémů se syntaxí v programech. http://cppcheck.sf.net/
Comment[de]=Cppcheck ist ein Werkzeug, das Ihnen hilft, Syntaxprobleme in Programmen zu finden. http://cppcheck.sf.net/
Comment[es]=Cppcheck es una herramienta que le ayuda a encontrar problemas de sintaxis en los programas. http://cppcheck.sf.net/
Comment[fr]=Cppcheck est un outil qui vous aide à trouver des problèmes de syntaxe dans les programmes. http://cppcheck.sf.net/
Comment[hu]=A Cppcheck egy olyan eszköz, amely segít megtalálni a szintaktikai hibákat a programokban. http://cppcheck.sf.net/
Comment[nl]=Cppcheck is een hulpmiddel dat helpt u bij het vinden van problemen in de syntaxis in programma's. http://cppcheck.sf.net/
Comment[pt]=O CppCheck é uma ferramenta que o ajuda a detectar problemas de sintaxe nos programas. http://cppcheck.sf.net/
Comment[pt_BR]=O Cppcheck é uma ferramenta que auxilia a detecção de problemas de sintaxe nos programas. http://cppcheck.sf.net/
Comment[sk]=CPPCheck je nástroj, ktorý vám pomôže nájsť problémy so syntaxou v programoch. http://cppcheck.sf.net/
Comment[sv]=Cppcheck är ett verktyg som hjälper till att hitta syntaxproblem i program. http://cppcheck.sf.net/
Comment[uk]=Cppcheck — це інструмент, що допомагатиме вам знаходити проблеми з синтаксичними конструкціями, що виникають у програмах. http://cppcheck.sf.net/
Comment[x-test]=xxCppcheck is a tool that helps you find syntax problems in programs. http://cppcheck.sf.net/xx
Name=Cppcheck Support
Name[bs]=Cppcheck podrška
Name[ca]=Implementació del Cppcheck
Name[cs]=Podpora Cppcheck
Name[de]=Cppcheck-Unterstützung
Name[es]=Uso de Cppcheck
Name[fr]=Prise en charge de Cppcheck
Name[hu]=Cppcheck támogatás
Name[nl]=Ondersteuning van CPPCheck
Name[pt]=Suporte para o Cppcheck
Name[pt_BR]=Suporte ao Cppcheck
Name[sk]=Podpora Cppcheck
Name[sv]=Stöd för Cppcheck
Name[uk]=Підтримка Cppcheck
Name[x-test]=xxCppcheck Supportxx
GenericName=Syntax check
GenericName[bs]=Provjera sintakse
GenericName[ca]=Comprova la sintaxi
GenericName[cs]=Kontrola syntaxe
GenericName[de]=Syntaxprüfung
GenericName[es]=Comprobación de sintaxis
GenericName[fr]=Vérification de la syntaxe
GenericName[hu]=Szintaxis-ellenőrzés
GenericName[nl]=Controle op syntaxis
GenericName[pt]=Verificação de sintaxe
GenericName[pt_BR]=Verificação de sintaxe
GenericName[sk]=Kontrola syntaxe
GenericName[sv]=Syntaxkontroll
GenericName[uk]=Перевірка синтаксису
GenericName[x-test]=xxSyntax checkxx
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevcppcheck
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDE-PluginInfo-Name=kdevcppcheck
X-KDE-PluginInfo-Author=Christoph Thielecke
X-KDE-PluginInfo-License=GPL
X-KDevelop-Category=Global
X-KDevelop-IRequired=org.kdevelop.IExecutePlugin
X-KDevelop-Mode=GUI


