[Desktop Entry]
Type=Service
Name=Ninja Project Builder
Name[cs]=Překladač projektů Ninja
Name[de]=Ninja-Projekterstellung
Name[es]=Constructor de proyectos Ninja
Name[et]=Ninja projektiehitaja
Name[fr]=Compilateur de projets Ninja
Name[ga]=Tógálaí Tionscadal Ninja
Name[gl]=Construtor de proxectos que usen Ninja
Name[hu]=Ninja projektfordító
Name[nl]=Ninja-project bouwprogramma
Name[pt]=Construtor de Projectos Ninja
Name[pt_BR]=Compilador de projetos Ninja
Name[sk]=Prekladač projektov Ninja
Name[sv]=Ninja projektbyggare
Name[tr]=Ninja Proje Oluşturucu
Name[uk]=Збирач проектів Ninja
Name[x-test]=xxNinja Project Builderxx
GenericName=Project Builder
GenericName[bs]=Graditelj projekta
GenericName[cs]=Překladač projektů
GenericName[de]=Projekterstellung
GenericName[es]=Constructor de proyectos
GenericName[et]=Projektiehitaja
GenericName[fr]=Compilateur de projets
GenericName[ga]=Tógálaí Tionscadal
GenericName[hu]=Projektfordító
GenericName[nl]=Projectbouwer
GenericName[pt]=Construtor de Projectos
GenericName[pt_BR]=Compilador de projetos
GenericName[sk]=Prekladač projektov
GenericName[sv]=Projektbyggare
GenericName[tr]=Proje Oluşturucu
GenericName[uk]=Збирання проектів
GenericName[x-test]=xxProject Builderxx
Comment=KDevelop Ninja Builder
Comment[de]=KDevelop-Ninja-Erstellung
Comment[es]=Constructor Ninja para KDevelop
Comment[et]=KDevelopi Ninja ehitaja
Comment[fr]=Compilateur de projets Ninja pour KDevelop
Comment[ga]=Tógálaí Ninja KDevelop
Comment[gl]=Construtor de proxectos de Ninja para KDevelop
Comment[hu]=KDevelop Ninja fordító
Comment[nl]=KDevelop Ninja-bouwprogramma
Comment[pt]=Construtor Ninja do KDevelop
Comment[pt_BR]=Compilador Ninja do KDevelop
Comment[sk]=Prekladač KDevelop Ninja
Comment[sv]=KDevelop Ninja byggverktyg
Comment[tr]=KDevelop Ninja Oluşturucu
Comment[uk]=Збирач Ninja для KDevelop
Comment[x-test]=xxKDevelop Ninja Builderxx
Icon=gear
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevninja
X-KDE-PluginInfo-Name=KDevNinjaBuilder
X-KDE-PluginInfo-Category=Project Management
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Project
X-KDevelop-Interfaces=org.kdevelop.IProjectBuilder
X-KDevelop-IRequired=org.kdevelop.IOutputView
X-KDevelop-Mode=NoGUI
