[Desktop Entry]
Type=Service
Name=QMake Project Manager
Name[bs]=QMake projekt menadžer
Name[ca]=Gestor de projectes QMake
Name[ca@valencia]=Gestor de projectes QMake
Name[de]=QMake-Projektverwaltung
Name[en_GB]=QMake Project Manager
Name[es]=Gestor de proyectos QMake
Name[fi]=QMake-projektinhallinta
Name[fr]=Gestionnaire de projets QMake
Name[ga]=Bainisteoir Tionscadail QMake
Name[gl]=Xestor de proxectos que usen QMake
Name[hu]=QMake projektkezelő
Name[it]=Gestore progetti QMake
Name[nds]=QMake-Projektpleger
Name[nl]=QMake-projectmanager
Name[pa]=QMake ਪਰੋਜੈਕਟ ਮੈਨੇਜਰ
Name[pl]=Menadżer projektu QMake
Name[pt]=Gestor de Projectos do QMake
Name[pt_BR]=Gerenciador de projetos do QMake
Name[sk]=Správca projektov QMake
Name[sv]=QMake-projekthantering
Name[tr]=QMake Proje Yöneticisi
Name[uk]=Керування проектами QMake
Name[x-test]=xxQMake Project Managerxx
Comment=Imports and edits QMake projects
Comment[bs]=Uvozi i uređuje QMake projekte
Comment[ca]=Importa i edita projectes de QMake
Comment[ca@valencia]=Importa i edita projectes de QMake
Comment[de]=Importiert und bearbeitet QMake-Projekte
Comment[en_GB]=Imports and edits QMake projects
Comment[es]=Importa y edita proyectos de QMake
Comment[fi]=Tuo ja muokkaa QMake-projekteja
Comment[fr]=Importe et modifie des projets QMake
Comment[ga]=Iompórtáil tionscadail qmake agus cuir in eagar iad
Comment[hu]=QMake projektek importálása és szerkesztése
Comment[nl]=Importeert en bewerkt QMake-projecten
Comment[pl]=Importuje i edytuje projekty QMake
Comment[pt]=Importa e edita os projectos do QMake
Comment[pt_BR]=Importa e edita os projetos do QMake
Comment[sk]=Importuje a upravuje projekty QMake
Comment[sv]=Importerar och redigerar QMake-projekt
Comment[tr]=QMake projelerini içeriye aktarır ve düzenler
Comment[uk]=Імпортує і змінює проекти QMake
Comment[x-test]=xxImports and edits QMake projectsxx
Icon=qtlogo
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevqmakemanager
X-KDE-PluginInfo-Name=KDevQMakeManager
X-KDE-PluginInfo-Category=Project Management
X-KDevelop-FileManager=QMake
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Interfaces=org.kdevelop.IBuildSystemManager,org.kdevelop.IProjectFileManager
X-KDevelop-IRequired=org.kdevelop.IQMakeBuilder
X-KDevelop-Mode=NoGUI
X-KDevelop-ProjectFilesFilter=*.pro
X-KDevelop-ProjectFilesFilterDescription=QMake Project Files
