// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef VERSION_H
#define VERSION_H

#include <kdeversion.h>

#define MAJOR_VERSION @VERSION_MAJOR@
#define MINOR_VERSION @VERSION_MINOR@
#define PATCH_VERSION @VERSION_PATCH@

#define VERSION_STR "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@"

#define VERSION KDE_MAKE_VERSION(@VERSION_MAJOR@, @VERSION_MINOR@, @VERSION_PATCH@)

#endif
