// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVQMAKE_VERSION_H
#define KDEVQMAKE_VERSION_H

#include <kdeversion.h>

#define KDEVQMAKE_MAJOR_VERSION @KDEVQMAKE_VERSION_MAJOR@
#define KDEVQMAKE_MINOR_VERSION @KDEVQMAKE_VERSION_MINOR@
#define KDEVQMAKE_PATCH_VERSION @KDEVQMAKE_VERSION_PATCH@

#define KDEVQMAKE_VERSION_STR "@KDEVQMAKE_VERSION_MAJOR@.@KDEVQMAKE_VERSION_MINOR@.@KDEVQMAKE_VERSION_PATCH@"

#define KDEVQMAKE_VERSION KDE_MAKE_VERSION(@KDEVQMAKE_VERSION_MAJOR@, @KDEVQMAKE_VERSION_MINOR@, @KDEVQMAKE_VERSION_PATCH@)

#endif
