#!/usr/bin/perl

use kdevelop;

initKDevelop();

print "Installing project file\n";
install( "${src}/template-rubyhello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-rubyhello/app.rb",       "${dest}/${APPNAMELC}.rb" );

print "Finished\n";
