[Desktop Entry]
Type=Service
Icon=applications-engineering
Exec=blubb
Comment=This plugin allows reviewing patches directly in the editor.
Comment[bg]=Тази приставка позволява преглеждане на кръпки направо в редактора.
Comment[bs]=Ovaj dodatak omogućava pregled zakrpa direktno u uredniku.
Comment[ca]=Aquest connector permet revisar pedaços directament en l'editor.
Comment[ca@valencia]=Este connector permet revisar pedaços directament en l'editor.
Comment[da]=Dette plugin tillader at gennemgå rettelser direkte i editoren.
Comment[de]=Dieses Modul ermöglich es, Patches direkt im Editor durchzusehen.
Comment[el]=Αυτό το πρόσθετο σάς επιτρέπει να επιθεωρείτε διορθώσεις απευθείας από τον κειμενογράφο.
Comment[en_GB]=This plugin allows reviewing patches directly in the editor.
Comment[es]=Este complemento permite revisar parches directamente en el editor.
Comment[et]=See plugin võimaldab paiku üle vaadata otse redaktoris.
Comment[fi]=Tämä liitännäinen salli korjausten katselmoinnin suoraan editorissa.
Comment[fr]=Ce module externe permet de réviser des correctifs directement dans l'éditeur.
Comment[gl]=Este complemento permite revisar parches directamente no editor.
Comment[hu]=Ez a bővítmény lehetővé teszi a javítócsomagok átnézését közvetlenül a szerkesztőben.
Comment[it]=Questa estensione permette di rivedere le patch direttamente nell'editor.
Comment[kk]=Бұл плагиніжамауларды тікелей редакторда шолуға мүмкіндік береді.
Comment[nb]=Dette programtillegget kan gjennomgå programlapper direkte i redigeringen.
Comment[nds]=Mit dit Moduul laat sik Kodeplasters direktemang binnen den Editor nakieken.
Comment[nl]=Deze plugin laat patches herzien direct in de editor.
Comment[pl]=Ta wtyczka pozwala na przeglądanie poprawek bezpośrednio w edytorze.
Comment[pt]=Este 'plugin' permite obter as modificações directamente no editor.
Comment[pt_BR]=Este plugin permite obter as modificações diretamente no editor.
Comment[ru]=Это расширение позволяет просматривать патчи непосредственно в редакторе.
Comment[sk]=Tento plugin umožňuje zhodnotenie záplat priamo v editore.
Comment[sl]=Vstavek omogoča pregled popravkov neposredno v urejevalniku.
Comment[sv]=Insticksprogrammet gör det möjligt att direkt granska programfixar i editorn.
Comment[tr]=Bu eklenti, yamaların doğrudan düzenleyici içerisinde gözden geçirilmesini sağlar.
Comment[uk]=За допомогою цього додатка ви зможете рецензувати латки безпосередньо у редакторі.
Comment[x-test]=xxThis plugin allows reviewing patches directly in the editor.xx
Comment[zh_CN]=此插件允许在编辑器中直接审阅补丁。
Comment[zh_TW]=此外掛程式任您可以直接在編輯器裡檢視修補。
Name=Patch Review
Name[bg]=Преглед на кръпки
Name[bs]=Pregled zakrpa
Name[ca]=Revisa pedaç
Name[ca@valencia]=Revisa pedaç
Name[da]=Gennemgang af rettelser
Name[de]=Patch-Durchsicht
Name[el]=Επιθεώρηση διορθώσεων
Name[en_GB]=Patch Review
Name[es]=Revisión de parches
Name[et]=Paikade ülevaatamine
Name[fi]=Korjauksen katselmointi
Name[fr]=Révision de correctifs
Name[gl]=Revisor de parches
Name[hu]=Javítócsomag átnézés
Name[it]=Revisione patch
Name[ja]=パッチレビュー
Name[kk]=Жамау шолуы
Name[nb]=Lappegjennomgang
Name[nds]=Plasternakiek
Name[nl]=Patchoverzicht
Name[pl]=Przeglądanie poprawek
Name[pt]=Revisão da Modificação
Name[pt_BR]=Revisão da Modificação
Name[ru]=Рецензирование патчей
Name[sk]=Zhodnotenie záplaty
Name[sl]=Pregled popravkov
Name[sv]=Granska programfixar
Name[tr]=Yama Gözden Geçirmesi
Name[ug]=ياماق باھالاش
Name[uk]=Рецензування латки
Name[x-test]=xxPatch Reviewxx
Name[zh_CN]=补丁审阅
Name[zh_TW]=修補檢視
GenericName=Patch Review
GenericName[bg]=Преглед на кръпки
GenericName[bs]=Pregled zakrpa
GenericName[ca]=Revisa pedaç
GenericName[ca@valencia]=Revisa pedaç
GenericName[da]=Gennemgang af rettelser
GenericName[de]=Patch-Durchsicht
GenericName[el]=Επιθεώρηση διορθώσεων
GenericName[en_GB]=Patch Review
GenericName[es]=Revisión de parches
GenericName[et]=Paikade ülevaatamine
GenericName[fi]=Korjauksen katselmointi
GenericName[fr]=Révision de correctifs
GenericName[gl]=Revisor de parches
GenericName[hu]=Javítócsomag átnézés
GenericName[it]=Revisione patch
GenericName[ja]=パッチレビュー
GenericName[kk]=Жамау шолуы
GenericName[nb]=Lappegjennomgang
GenericName[nds]=Plasternakiek
GenericName[nl]=Patchoverzicht
GenericName[pl]=Przeglądanie poprawek
GenericName[pt]=Revisão da Modificação
GenericName[pt_BR]=Revisão da Modificação
GenericName[ru]=Рецензирование патчей
GenericName[sk]=Zhodnotenie záplaty
GenericName[sl]=Pregled popravkov
GenericName[sv]=Granska programfixar
GenericName[tr]=Yama Gözden Geçirmesi
GenericName[ug]=ياماق باھالاش
GenericName[uk]=Рецензування латки
GenericName[x-test]=xxPatch Reviewxx
GenericName[zh_CN]=补丁审阅
GenericName[zh_TW]=修補檢視
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevpatchreview
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDevelop-Interfaces=org.kdevelop.IPatchReview
X-KDE-PluginInfo-Name=kdevpatchreview
X-KDE-PluginInfo-Author=David Nolden
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-Category=Utilities
X-KDevelop-Mode=GUI
