#include "cmakecachemodel.h"
#include <QFile>
#include <QRegExp>
#include <KDebug>
#include <KLocale>

//4 columns: name, type, value, comment
//name:type=value - comment
CMakeCacheModel::CMakeCacheModel(QObject *parent, const KUrl &path)
    : QStandardItemModel(parent), m_filePath(path), m_changed(false)
{
    QStringList labels;
    labels.append(i18n("Name"));
    labels.append(i18n("Type"));
    labels.append(i18n("Value"));
    labels.append(i18n("Comment"));
    setHorizontalHeaderLabels(labels);
    
    int currentIdx=0;
    QStringList currentComment;
    QFile file(path.toLocalFile());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
    {
        kDebug(9032) << "error. Could not find the file";
        return;
    }

    QTextStream in(&file);
    while (!in.atEnd())
    {
        QString line = in.readLine().trimmed();
        if(line.startsWith("//"))
            currentComment += line.right(line.count()-2);
        else if(!line.isEmpty()) //it is a variable
        {
            QRegExp rx(QString("(%1+):?(%1*)=(%1*)").arg("[0-9a-zA-Z_/; \\+'.\\-]"));
            if(rx.exactMatch(line))
            {
                QString isInternal;
                rx.indexIn(line);
                QStringList info = rx.capturedTexts();
                QList<QStandardItem*> lineItems;
                lineItems.append(new QStandardItem(info[1]));
                lineItems.append(new QStandardItem(info[2]));
                lineItems.append(new QStandardItem(info[3]));
                lineItems.append(new QStandardItem(currentComment.join("\n")));
                insertRow(currentIdx, lineItems);
//                 kDebug(9032) << "CacheLine: " << info;
                currentComment.clear();
                currentIdx++;
            }
            else if(line.startsWith('#'))
            {
                if(line.contains("INTERNAL"))
                    m_internalBegin=currentIdx;
                kDebug(9032) << "Comment: " << line << " -.- " << currentIdx;
            }
            else
	    {
                kDebug(9032) << "unrecognized cache line: " << line;
            }
        }
    }
}

bool CMakeCacheModel::writeBack(const KUrl & path) const
{
    kDebug(9032) << "writing CMakeCache.txt at " << path;
    QFile file(path.toLocalFile());
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
    {
        kDebug(9032) << "Could not open the file for writing";
        return false;
    }

    KUrl dir(path);
    dir.upUrl();
    QTextStream out(&file);
    out << "# This is the CMakeCache file." << endl;
    out << "# For build in directory: " << dir.prettyUrl() << endl;
    out << "# It was generated by KDevelop 4" << endl;
    out << "# You can edit this file to change values found and used by cmake." << endl;
    out << "# If you do not want to change any of the values, simply exit the editor." << endl;
    out << "# If you do want to change a value, simply edit, save, and exit the editor." << endl;
    out << "# The syntax for the file is as follows:" << endl;
    out << "# KEY:TYPE=VALUE" << endl;
    out << "# KEY is the name of a variable in the cache." << endl;
    out << "# TYPE is a hint to GUI's for the type of VALUE, DO NOT EDIT TYPE!." << endl;
    out << "# VALUE is the current value for the KEY." << endl << endl;

    out << "########################" << endl;
    out << "# EXTERNAL cache entries" << endl;
    out << "########################" << endl << endl;
    for(int i=0; i<rowCount(); i++)
    {
        if(i==m_internalBegin)
        {
            out << endl;
            out << "########################" << endl;
            out << "# INTERNAL cache entries" << endl;
            out << "########################" << endl << endl;
        }
        
        QStandardItem* name = item(i, 0);
        QStandardItem* type = item(i, 1);
        QStandardItem* valu = item(i, 2);
        QStandardItem* comm = item(i, 3);
        if(!name || !type || !comm || !valu)
            continue;
        if(!comm->text().isEmpty())
        {
            QStringList comments=comm->text().split("\n");
            foreach(QString commLine, comments)
            {
                out << "//";
                out << commLine;
                out << endl;
            }
        }
        QString var=name->text();
        if(!type->text().isEmpty())
            var += ':'+type->text();
        var+='='+valu->text();
        out << var << endl;
        if(i<m_internalBegin)
            out << endl;
    }
    out << endl;
    return true;
}

#include "cmakecachemodel.moc"

//kate: space-indent on; indent-width 4; replace-tabs on;

