#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();

print "Installing project file\n";
install( "${src}/template-gtk2mmapp/app.kdevelop",            "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/pixmaps", 0777 );
install( "${src}/template-gtk2mmapp/app-Makefile.am",         "${dest}/Makefile.am" );
install( "${src}/template-gtk2mmapp/configure.in",            "${dest}/configure.in" );
install( "${src}/template-gtk2mmapp/acconfig.h",              "${dest}/acconfig.h" );
install( "${src}/template-gtk2mmapp/config.h",              "${dest}/config.h" );
install( "${src}/template-gtk2mmapp/autogen.sh",              "${dest}/autogen.sh" );
install( "${src}/template-gtk2mmapp/gtk2mm.glade",            "${dest}/${APPNAMELC}.glade" );
install( "${src}/template-gtk2mmapp/gtk2mm.gladep",           "${dest}/${APPNAMELC}.gladep" );
chmod(0755,"${dest}/autogen.sh");

print "Installing application sources\n";
install( "${src}/template-gtk2mmapp/src-Makefile.am",         "${dest}/src/Makefile.am" );
install( "${src}/template-gtk2mmapp/gtk2mm.cc",              "${dest}/src/${APPNAMELC}.cc" );
install( "${src}/template-gtk2mmapp/main_window.hh",           "${dest}/src/main_window.hh" );
install( "${src}/template-gtk2mmapp/main_window.cc",         "${dest}/src/main_window.cc" );
install( "${src}/template-gtk2mmapp/main_window_glade.hh",     "${dest}/src/main_window_glade.hh" );
install( "${src}/template-gtk2mmapp/main_window_glade.cc",   "${dest}/src/main_window_glade.cc" );

print "Finished\n";
