#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
# install the kdevelop project file
install( "${src}/template-clanlib/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application\n";
install( "${src}/template-clanlib/app-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-clanlib/app-configure.in", "${dest}/configure.in" );
install( "${src}/template-clanlib/app-autogen.sh", "${dest}/autogen.sh" );
chmod(0755,"${dest}/autogen.sh");

print "Installing application sources\n";
mkdir("${dest}/src", 0755 );
install( "${src}/template-clanlib/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-clanlib/main.cpp",          "${dest}/src/main.cpp" );

print "Finished\n";
