[Desktop Entry]
Type=Service
Icon=x-office-address-book
Comment=This plugin provides Manual Pages integration
Comment[ar]=توفّر هذه الملحقة تكامل صفحات الكتيّب
Comment[bs]=Ovaj dodatak omogućava integraciju sa stranicama uputstava
Comment[ca]=Aquest connector proporciona la integració de les pàgines del manual
Comment[ca@valencia]=Este connector proporciona la integració de les pàgines del manual
Comment[da]=Dette plugin giver integration af manualsider
Comment[de]=Dieses Modul integriert Handbuch-Seiten
Comment[el]=Αυτό το πρόσθετο παρέχει ενσωμάτωση σελίδων εγχειριδίου
Comment[en_GB]=This plugin provides Manual Pages integration
Comment[es]=Este complemento proporciona integración de las páginas de manual
Comment[et]=See plugin pakub manuaalilehekülgede lõimimist
Comment[fi]=Tämä liitännäinen tarjoaa integraation manuaalisivuille
Comment[fr]=Ce module externe fournit l'intégration des pages de manuel
Comment[gl]=Este engadido fornece integración coas páxinas de manual
Comment[hu]=Ez a bővítmény a Man oldalak integrációját biztosítja
Comment[it]=Questa estensione fornisce l'integrazione delle pagine del manuale
Comment[kk]=Бұл плагині man-парақтармен біріктіруін қамтамасыз етеді
Comment[nb]=Dette programtillegget gir integrering med manualsider
Comment[nds]=Dit Moduul stellt de Inbetten vun de Handbooksieden praat
Comment[nl]=Deze plugin biedt integratie met man-pagina's
Comment[pl]=Wtyczka ta zapewnia integrację stron instrukcji
Comment[pt]=Este 'plugin' oferece a integração com as páginas de manual
Comment[pt_BR]=Este plugin fornece integração com as páginas de manuais
Comment[ru]=Это расширение интегрирует руководства man
Comment[sk]=Tento modul poskytuje integráciu manuálových stránok
Comment[sl]=Ta vstavek omogoči podporo za strani man
Comment[sv]=Insticksprogrammet tillhandahåller integrering av manualsidor
Comment[tr]=Bu eklenti Kılavuz Sayfaları bütünleşmesini sağlar
Comment[ug]=بۇ قىستۇرما ‹قوللانما بەتلىرى› نى يۈرۈشلەشتۈرۈشنى ئەمەلگە ئاشۇرىدۇ
Comment[uk]=За допомогою цього додатка здійснюється інтеграція з системою сторінок підручника (man)
Comment[x-test]=xxThis plugin provides Manual Pages integrationxx
Comment[zh_CN]=此插件提供了帮助手册整合
Comment[zh_TW]=此外掛程式提供 Man Page 整合
Name=Man Pages
Name[ar]=صفحات Man
Name[bs]=Man stgranice
Name[ca]=Pàgines man
Name[ca@valencia]=Pàgines man
Name[cs]=Manuálové stránky
Name[da]=Man-sider
Name[de]=Handbuch-Seiten
Name[el]=Man Pages
Name[en_GB]=Man Pages
Name[es]=Páginas man
Name[et]=Man-leheküljed
Name[fi]=Mansivut
Name[fr]=Pages de manuel
Name[gl]=Páxinas de manuais
Name[hu]=Man oldalak
Name[it]=Pagine man
Name[kk]=Man парақтары
Name[mr]=Man पाने
Name[nb]=Man-sider
Name[nds]=Handbooksieden
Name[nl]=Man-pagina's
Name[pl]=Strony instrukcji
Name[pt]=Páginas do 'Man'
Name[pt_BR]=Páginas de manuais
Name[ru]=Страницы man
Name[sk]=Manuálové stránky
Name[sl]=Strani man
Name[sv]=Manualsidor
Name[tr]=Kılavuz Sayfaları
Name[ug]=قوللانما بەتلىرى
Name[uk]=Сторінки man
Name[x-test]=xxMan Pagesxx
Name[zh_CN]=Man 手册
Name[zh_TW]=Man Pages
GenericName=Documentation Support
GenericName[ar]=دعم التّوثيق
GenericName[bs]=Podrška za dokumentaciju
GenericName[ca]=Implementació de la documentació
GenericName[ca@valencia]=Implementació de la documentació
GenericName[cs]=Podpora dokumentace
GenericName[da]=Dokumentationsunderstøttelse
GenericName[de]=Dokumentationsunterstützung
GenericName[el]=Υποστήριξη τεκμηρίωσης
GenericName[en_GB]=Documentation Support
GenericName[es]=Implementación de la documentación
GenericName[et]=Dokumentatsiooni toetus
GenericName[fi]=Dokumentaatiotuki
GenericName[fr]=Prise en charge de la documentation
GenericName[ga]=Tacaíocht Doiciméadaithe
GenericName[gl]=Soporte de documentación
GenericName[hu]=Dokumentáció támogatás
GenericName[it]=Supporto documentazione
GenericName[kk]=Құжаттаманы біріктіру
GenericName[km]=គាំទ្រ​ឯកសារ
GenericName[nb]=Dokumentasjonsstøtte
GenericName[nds]=Dokmentatschoon-Ünnerstütten
GenericName[nl]=Documentatie-ondersteuning
GenericName[pl]=Obsługa dokumentacji
GenericName[pt]=Suporte à Documentação
GenericName[pt_BR]=Suporte à Documentação
GenericName[ru]=Поддержка документации
GenericName[sk]=Podpora dokumentácie
GenericName[sl]=Podpora za dokumentacijo
GenericName[sv]=Dokumentationsstöd
GenericName[tr]=Belgelendirme Desteği
GenericName[ug]=پۈتۈك قوللىشى
GenericName[uk]=Підтримка роботи з документацією
GenericName[x-test]=xxDocumentation Supportxx
GenericName[zh_CN]=文档支持
GenericName[zh_TW]=文件支援
ServiceTypes=KDevelop/Plugin

X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kdevmanpage
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDE-PluginInfo-Name=KDevManPage
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-Category=Documentation
X-KDevelop-Mode=GUI
X-KDevelop-Interfaces=org.kdevelop.IDocumentationProvider

X-KDE-PluginInfo-EnabledByDefault=false
