#ifndef KDEVPLATFORM_KROSSDUCONTEXT_H
#define KDEVPLATFORM_KROSSDUCONTEXT_H

#include<QtCore/QVariant>

//This is file has been generated by xmltokross, you should not edit this file but the files used to generate it.

namespace KDevelop { class IndexedDUContext; }
namespace KDevelop { class LocalIndexedDUContext; }
namespace KDevelop { class ImportTraceItem; }
namespace KDevelop { class ImportTrace; }
namespace KDevelop { class DUContext; }
namespace KDevelop { class Import; }
namespace KDevelop { class SearchItem; }
namespace Handlers
{
	QVariant kDevelopDUContextSearchItemHandler(KDevelop::DUContext::SearchItem* type);
	QVariant kDevelopDUContextSearchItemHandler(const KDevelop::DUContext::SearchItem* type);

	QVariant kDevelopDUContextImportHandler(KDevelop::DUContext::Import* type);
	QVariant kDevelopDUContextImportHandler(const KDevelop::DUContext::Import* type);

	QVariant kDevelopDUContextHandler(KDevelop::DUContext* type);
	QVariant kDevelopDUContextHandler(const KDevelop::DUContext* type);

	QVariant kDevelopImportTraceHandler(KDevelop::ImportTrace* type);
	QVariant kDevelopImportTraceHandler(const KDevelop::ImportTrace* type);

	QVariant kDevelopImportTraceItemHandler(KDevelop::ImportTraceItem* type);
	QVariant kDevelopImportTraceItemHandler(const KDevelop::ImportTraceItem* type);

	QVariant kDevelopLocalIndexedDUContextHandler(KDevelop::LocalIndexedDUContext* type);
	QVariant kDevelopLocalIndexedDUContextHandler(const KDevelop::LocalIndexedDUContext* type);

	QVariant kDevelopIndexedDUContextHandler(KDevelop::IndexedDUContext* type);
	QVariant kDevelopIndexedDUContextHandler(const KDevelop::IndexedDUContext* type);

}

#endif
