#ifndef KDEVPLATFORM_KROSSEDITORCONTEXT_H
#define KDEVPLATFORM_KROSSEDITORCONTEXT_H

#include<QtCore/QVariant>

//This is file has been generated by xmltokross, you should not edit this file but the files used to generate it.

namespace KDevelop { class EditorContext; }
namespace Handlers
{
	QVariant kDevelopEditorContextHandler(KDevelop::EditorContext* type);
	QVariant kDevelopEditorContextHandler(const KDevelop::EditorContext* type);

}

#endif
