#!/usr/bin/perl

use kdevelop;

initKDevelop();

print "Installing project file\n";
installHTML( "${src}/template-perlhello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-perlhello/app.pl",       "${dest}/${APPNAMELC}.pl" );

print "Finished\n";
