[General]
Name=Testing C++ Template
Name[ca]=Plantilla C++ de prova
Name[ca@valencia]=Plantilla C++ de prova
Name[da]=Tester C++-skabelon
Name[el]=Δοκιμή C++ Template
Name[es]=Prueba de plantilla C++
Name[et]=C++ malli testimine
Name[fi]=Testi-C++-malli
Name[fr]=Modèle C++ pour tester
Name[gl]=Modelo de C++ de probas
Name[hu]=C++ sablon tesztelése
Name[it]=Modello di test C++
Name[nb]=Mal for C++-testing
Name[nl]=C++-sjabloon testen
Name[pl]=Szablon testowy C++
Name[pt]=Modelo de Testes em C++
Name[pt_BR]=Modelo de testes em C++
Name[sk]=Testovanie C++ šablóny
Name[sl]=Preizkusna predloga C++
Name[sv]=C++ mall för test
Name[tr]=C++ şablonu testi
Name[uk]=Тестовий шаблон C++
Name[x-test]=xxTesting C++ Templatexx
Name[zh_CN]=C++ 测试模板
Name[zh_TW]=測試 C++ 樣本
Comment=A unit test using the QTest library without a graphical user interface
Comment[ca]=Una prova unitària utilitzant la biblioteca QTest sense interfície gràfica d'usuari
Comment[ca@valencia]=Una prova unitària utilitzant la biblioteca QTest sense interfície gràfica d'usuari
Comment[da]=En unittest som bruger biblioteket QTest uden en grafisk brugerflade
Comment[el]=Ένα unit test με χρήση βιβλιοθήκης QTest χωρίς γραφικό περιβάλλον χρήστη
Comment[es]=Una prueba unitaria que usa la biblioteca QTest sin una interfaz gráfica de usuario
Comment[et]=Ühiktest QTesti teegi abil ilma graafilise kasutajaliideseta
Comment[fi]=Yksikkötesti, joka käyttää QTest-kirjastoa ilman graafista käyttöliittymää.
Comment[fr]=Un test unitaire utilisant la bibliothèque QTest sans interface graphique utilisateur
Comment[gl]=Unha proba unitaria que emprega a biblioteca QTest sen interface gráfica de usuario
Comment[hu]=Egy egységteszt a QTest könyvtár használatával grafikus felhasználói felület nélkül
Comment[it]=Un test d'unità che usa la libreria QTest senza un'interfaccia grafica utente
Comment[nb]=En enhetstest som bruker QTest-biblioteket uten en grafisk brukerflate
Comment[nl]=Een test van een eenheid met gebruik van de QTest-bibliotheek zonder een grafisch gebruikersinterface
Comment[pl]=Jednostkowy test wykorzystujący bibliotekę QTest bez graficznego interfejsu użytkownika
Comment[pt]=Um teste unitário, com a biblioteca QTest, sem uma interface gráfica do utilizador
Comment[pt_BR]=Teste unitário que usa a biblioteca QTest sem uma interface gráfica do usuário
Comment[sk]=Unit test pomocou knižnice QTest bez grafického rozhrania
Comment[sl]=Preizkus enot z uporabo knjižnice QTest brez grafičnega vmesnika
Comment[sv]=En enhetstest som använder QTest-biblioteket utan grafiskt gränssnitt
Comment[tr]=Grafiksel bir kullanıcı arayüzü olmadan QTest kütüphanesi testi için kullanılan bir birim
Comment[uk]=Перевірка модулів за допомогою бібліотеки QTest без графічного інтерфейсу користувача
Comment[x-test]=xxA unit test using the QTest library without a graphical user interfacexx
Comment[zh_CN]=一个使用 QTest 库且不含图形界面的单元测试
Comment[zh_TW]=單元測試，用 QTest 函式庫，但不含使用者介面
Category=Test/Test/C++
Files=Header,Implementation

[Header]
Name=Header
Name[ca]=Capçalera
Name[ca@valencia]=Capçalera
Name[da]=Header
Name[de]=Header
Name[el]=Header
Name[es]=Cabecera
Name[et]=Päis
Name[fi]=Otsikkotiedosto
Name[fr]=En-tête
Name[gl]=Cabeceira
Name[hu]=Fejléc
Name[it]=Intestazione
Name[kk]=Айдар
Name[mr]=हेडर
Name[nb]=Hode
Name[nl]=Kop
Name[pl]=Nagłówek
Name[pt]=Inclusão
Name[pt_BR]=Cabeçalho
Name[sk]=Hlavička
Name[sl]=Glava
Name[sv]=Deklaration
Name[tr]=Başlık
Name[uk]=Заголовок
Name[x-test]=xxHeaderxx
Name[zh_CN]=头文件
Name[zh_TW]=標頭
File=class.h
OutputFile={{ name }}.h

[Implementation]
Name=Implementation
Name[ca]=Implementació
Name[ca@valencia]=Implementació
Name[cs]=Implementace
Name[da]=Implementering
Name[de]=Implementation
Name[el]=Υλοποίηση
Name[es]=Implementación
Name[et]=Teostus
Name[fi]=Toteutus
Name[fr]=Implémentation
Name[gl]=Implementación
Name[hu]=Megvalósítás
Name[it]=Implementazione
Name[kk]=Іске асыруы
Name[nb]=Implementering
Name[nl]=Implementatie
Name[pl]=Implementacja
Name[pt]=Implementação
Name[pt_BR]=Implementação
Name[sk]=Implementácia
Name[sl]=Izvedba
Name[sv]=Implementering
Name[tr]=Gerçekleme
Name[uk]=Реалізація
Name[x-test]=xxImplementationxx
Name[zh_CN]=实现
Name[zh_TW]=實作
File=class.cpp
OutputFile={{ name }}.cpp

