#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-kmod/kmod.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
install( "${src}/template-kmod/src-Makefile",  "${dest}/Makefile" );

print "Installing application sources\n";
install( "${src}/template-kmod/kmod-driver.c", "${dest}/${APPNAMELC}-driver.c" );
print "Finished\n";
