#!perl -I/usr/kde/3.1/share/apps/kdevappwizard/template-common

use kdevelop;

initKDevelop();

print "Installing project file\n";
installHTML( "${src}/template-xulhello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-xulhello/app.xul",       "${dest}/${APPNAMELC}.xul" );

print "Finished\n";
