#!/usr/bin/perl
use gideon;
initGideon();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-dcopservice/dcopservice.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-app.lsm",             "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-dcopservice/subdirs",           "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-dcopservice/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-dcopservice/dcopservice.cpp",         "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-dcopservice/dcopservice.h",           "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-dcopservice/dcopservice.desktop",           "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-dcopservice/main.cpp",           "${dest}/src/main.cpp" );
#install( "${src}/template-dcopservice/dcopserviceclient.cpp",         "${dest}/src/${APPNAMELC}client.cpp" );
#install( "${src}/template-dcopservice/dcopserviceclient.h",           "${dest}/src/${APPNAMELC}client.h" );

print "Finished\n";
