#!/usr/bin/perl

use kdevelop;

initKDevelop();
installLicense();

print "Installing project file\n";
install( "${src}/template-kpartapp/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-kdevpart/src-Makefile.am", "${dest}/Makefile.am" );
install( "${src}/template-kdevpart/kdevpart_part.cpp",  "${dest}/${APPNAMELC}_part.cpp" );
install( "${src}/template-kdevpart/kdevpart_part.h",    "${dest}/${APPNAMELC}_part.h" );
install( "${src}/template-kdevpart/kdevpart_widget.cpp",  "${dest}/${APPNAMELC}_widget.cpp" );
install( "${src}/template-kdevpart/kdevpart_widget.h",    "${dest}/${APPNAMELC}_widget.h" );
install( "${src}/template-kdevpart/kdevpart_part.rc",   "${dest}/kdevpart_${APPNAMELC}.rc" );
install( "${src}/template-kdevpart/kdevpart.desktop",   "${dest}/kdevpart_${APPNAMELC}.desktop" );
install( "${src}/template-kdevpart/README.dox",   "${dest}/README.dox" );

print "Finished\n";
