#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();

print "Installing project file\n";
install( "${src}/template-kbearplugin/plugin.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-kbearplugin/subdirs",        "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kbearplugin/kbearplugin-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kbearplugin/src-Makefile.am",             "${dest}/src/Makefile.am" );
install( "${src}/template-kbearplugin/plugin.cpp",                  "${dest}/src/kbear${APPNAMELC}plugin.cpp" );
install( "${src}/template-kbearplugin/plugin.h",                    "${dest}/src/kbear${APPNAMELC}plugin.h" );
install( "${src}/template-kbearplugin/configwidget.cpp",            "${dest}/src/kbear${APPNAMELC}configwidget.cpp" );
install( "${src}/template-kbearplugin/configwidget.h",              "${dest}/src/kbear${APPNAMELC}configwidget.h" );
install( "${src}/template-kbearplugin/outputwidget.cpp",            "${dest}/src/kbear${APPNAMELC}outputwidget.cpp" );
install( "${src}/template-kbearplugin/outputwidget.h",              "${dest}/src/kbear${APPNAMELC}outputwidget.h" );
install( "${src}/template-kbearplugin/plugin.rc",                   "${dest}/src/kbear${APPNAMELC}.rc" );
install( "${src}/template-kbearplugin/kbearplugin.desktop",         "${dest}/src/kbear${APPNAMELC}.desktop" );
install( "${src}/template-kbearplugin/hi32-action-plugin.png",      "${dest}/src/hi32-action-kbear${APPNAMELC}.png");

print "Finished\n";
