#!/usr/bin/perl

use gideon;
use File::Copy;

initGideon();
installFileTemplate();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-pyqt/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-pyqt/app.py",       "${dest}/${APPNAMELC}.py" );
install( "${src}/template-pyqt/documentdetails.ui",       "${dest}/documentdetails.ui" );
install( "${src}/template-pyqt/app-Makefile.am",       "${dest}/Makefile.am" );
install( "${src}/template-pyqt/app-configure.ac",       "${dest}/configure.ac" );
install( "${src}/template-pyqt/app-autogen.sh",       "${dest}/autogen.sh" );
install( "${src}/template-pyqt/mkinstalldirs",       "${dest}/mkinstalldirs" );
install( "${src}/template-pyqt/missing",       "${dest}/missing" );
install( "${src}/template-pyqt/install-sh",       "${dest}/install-sh" );
install( "${src}/template-pyqt/pyqt-am-preproc.py", "${dest}/pyqt-am-preproc.py");
chmod 0764,"${dest}/autogen.sh";
chmod 0764,"${dest}/${APPNAMELC}.py";


print "Installing application data files\n";
install( "${src}/template-pyqt/fileopen.pyxpm", "${dest}/fileopen.pyxpm" );
install( "${src}/template-pyqt/fileprint.pyxpm", "${dest}/fileprint.pyxpm" );
install( "${src}/template-pyqt/filesave.pyxpm", "${dest}/filesave.pyxpm" );

print "Installing application file templates\n";
copy( "${src}/template-pyqt/templates-ui-dialog", "${dest}/templates/ui" );
copy( "${src}/template-pyqt/templates-ui-dialog", "${dest}/templates/ui-dialog" );
copy( "${src}/template-pyqt/templates-ui-mainwin", "${dest}/templates/ui-mainwin" );



print "Finished\n";
