//commands
i18n("Cursor Movement")
i18n("Left")
i18n("Right")
i18n("Word Left")
i18n("Word Right")
i18n("Home")
i18n("End")
i18n("Up")
i18n("Down")
i18n("Scroll Up")
i18n("Scroll Down")
i18n("Top Of View")
i18n("Bottom Of View")
i18n("Page Up")
i18n("Page Down")
i18n("Cursor Page Up")
i18n("Cursor Page Down")
i18n("Top")
i18n("Bottom")

i18n("File Commands")
i18n("&New...")
i18n("&Open...")
i18n("&Insert...")
i18n("&Save")
i18n("Save &As...")
i18n("&Print...")
i18n("New &Window")
i18n("New &View")
i18n("&Close")

i18n("Edit Commands")
i18n("Return")
i18n("Delete")
i18n("Backspace")
i18n("Kill Line")
i18n("U&ndo")
i18n("R&edo")
i18n("C&ut")
i18n("&Copy")
i18n("&Paste")
i18n("&Indent")
i18n("Uninden&t")
i18n("&Select All")
i18n("&Deselect All")
i18n("In&vert Selection")

i18n("Find Commands")
i18n("&Find...")
i18n("&Replace...")
i18n("Find &Again")
i18n("&Goto Line...")

i18n("Bookmark Commands")
i18n("&Set Bookmark...")
i18n("&Add Bookmark")
i18n("&ClearBookmarks")
i18n("Set Bookmark 1")
i18n("Set Bookmark 2")
i18n("Set Bookmark 3")
i18n("Set Bookmark 4")
i18n("Set Bookmark 5")
i18n("Set Bookmark 6")
i18n("Set Bookmark 7")
i18n("Set Bookmark 8")
i18n("Set Bookmark 9")
i18n("Set Bookmark 10")
i18n("Goto Bookmark 1")
i18n("Goto Bookmark 2")
i18n("Goto Bookmark 3")
i18n("Goto Bookmark 4")
i18n("Goto Bookmark 5")
i18n("Goto Bookmark 6")
i18n("Goto Bookmark 7")
i18n("Goto Bookmark 8")
i18n("Goto Bookmark 9")
i18n("Goto Bookmark 10")

i18n("State Commands")
i18n("Insert Mode")
i18n("&Vertical Selections")

//syntax highlight
i18n("Normal"              )
i18n("Keyword"             )
i18n("Data Type"           )
i18n("Decimal/Value"       )
i18n("Base-N Integer"      )
i18n("Floating Point"      )
i18n("Character"           )
i18n("String"              )
i18n("Comment"             )
i18n("Others"              )

i18n("Normal"              )
i18n("C"                   )
i18n("C++"                 )
i18n("Java"                )
i18n("HTML"                )
i18n("Bash"                )
i18n("Modula 2"            )
i18n("Ada"                 )
i18n("Python"              )
i18n("Perl"                )
i18n("Sather"              )
i18n("Latex"               )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Data Type"           )
i18n("Decimal"             )
i18n("Octal"               )
i18n("Hex"                 )
i18n("Float"               )
i18n("Char"                )
i18n("String"              )
i18n("String Char"         )
i18n("Comment"             )
i18n("Preprocessor"        )
i18n("Prep. Lib"           )

i18n("Normal Text"         )
i18n("Char"                )
i18n("Comment"             )
i18n("Tag Text"            )
i18n("Tag"                 )
i18n("Tag Value"           )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Integer"             )
i18n("String"              )
i18n("Substitution"        )
i18n("Comment"             )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Decimal"             )
i18n("Hex"                 )
i18n("Float"               )
i18n("String"              )
i18n("Comment"             )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Decimal"             )
i18n("Base-N"              )
i18n("Float"               )
i18n("Char"                )
i18n("String"              )
i18n("Comment"             )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Decimal"             )
i18n("Octal"               )
i18n("Hex"                 )
i18n("Float"               )
i18n("Char"                )
i18n("String"              )
i18n("String Char"         )
i18n("Comment"             )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Variable"            )
i18n("Operator"            )
i18n("String"              )
i18n("String Char"         )
i18n("Comment"             )
i18n("Pod"                 )

i18n("Normal Text"         )
i18n("Keyword"             )
i18n("Special Classname"   )
i18n("Classname"           )
i18n("Special Featurename" )
i18n("Identifier"          )
i18n("Decimal"             )
i18n("Base-N"              )
i18n("Float"               )
i18n("Char"                )
i18n("String"              )
i18n("Comment"             )

i18n("Normal Text"         )
i18n("Tag/Keyword"         )
i18n("Char"                )
i18n("Parameter"           )
i18n("Comment"             )

//Keys
i18n("Shift")
i18n("Ctrl")
i18n("Alt")
i18n("Meta")

i18n("Escape")
i18n("Tab")
i18n("Backtab")
i18n("Backspace")
i18n("Return")
i18n("Enter")
i18n("Insert")
i18n("Delete")
i18n("Pause")
i18n("Print")
i18n("SysReq")
i18n("Home")
i18n("End")
i18n("Left")
i18n("Up")
i18n("Right")
i18n("Down")
i18n("Prior")
i18n("PageUp")
i18n("Next")
i18n("PageDown")
i18n("Menu")
i18n("Space")
i18n("Exclam")
i18n("QuoteDbl")
i18n("NumberSign")
i18n("Dollar")
i18n("Percent")
i18n("Ampersand")
i18n("Apostrophe")
i18n("ParenLeft")
i18n("ParenRight")
i18n("Asterisk")
i18n("Plus")
i18n("Comma")
i18n("Minus")
i18n("Period")
i18n("Slash")
i18n("Colon")
i18n("Semicolon")
i18n("Less")
i18n("Equal")
i18n("Greater")
i18n("Question")
i18n("BracketLeft")
i18n("Backslash")
i18n("BracketRight")
i18n("AsciiCircum")
i18n("Underscore")
i18n("QuoteLeft")
i18n("BraceLeft")
i18n("Bar")
i18n("BraceRight")
i18n("AsciiTilde")
