#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();


print "Installing project file\n";
install( "${src}/template-pythonhello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-pythonhello/app.py",       "${dest}/${APPNAMELC}.py" );

print "Finished\n";
