/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kde_koala_Core */

#ifndef _Included_org_kde_koala_Core
#define _Included_org_kde_koala_Core
#ifdef __cplusplus
extern "C" {
#endif
#undef org_kde_koala_Core_NoButton
#define org_kde_koala_Core_NoButton 0L
#undef org_kde_koala_Core_LeftButton
#define org_kde_koala_Core_LeftButton 1L
#undef org_kde_koala_Core_RightButton
#define org_kde_koala_Core_RightButton 2L
#undef org_kde_koala_Core_MidButton
#define org_kde_koala_Core_MidButton 4L
#undef org_kde_koala_Core_MouseButtonMask
#define org_kde_koala_Core_MouseButtonMask 7L
#undef org_kde_koala_Core_ShiftButton
#define org_kde_koala_Core_ShiftButton 8L
#undef org_kde_koala_Core_ControlButton
#define org_kde_koala_Core_ControlButton 16L
#undef org_kde_koala_Core_AltButton
#define org_kde_koala_Core_AltButton 32L
#undef org_kde_koala_Core_KeyButtonMask
#define org_kde_koala_Core_KeyButtonMask 56L
#undef org_kde_koala_Core_Keypad
#define org_kde_koala_Core_Keypad 16384L
#undef org_kde_koala_Core_Horizontal
#define org_kde_koala_Core_Horizontal 0L
#undef org_kde_koala_Core_Vertical
#define org_kde_koala_Core_Vertical 1L
#undef org_kde_koala_Core_AlignLeft
#define org_kde_koala_Core_AlignLeft 1L
#undef org_kde_koala_Core_AlignRight
#define org_kde_koala_Core_AlignRight 2L
#undef org_kde_koala_Core_AlignHCenter
#define org_kde_koala_Core_AlignHCenter 4L
#undef org_kde_koala_Core_AlignTop
#define org_kde_koala_Core_AlignTop 8L
#undef org_kde_koala_Core_AlignBottom
#define org_kde_koala_Core_AlignBottom 16L
#undef org_kde_koala_Core_AlignVCenter
#define org_kde_koala_Core_AlignVCenter 32L
#undef org_kde_koala_Core_AlignCenter
#define org_kde_koala_Core_AlignCenter 36L
#undef org_kde_koala_Core_SingleLine
#define org_kde_koala_Core_SingleLine 64L
#undef org_kde_koala_Core_DontClip
#define org_kde_koala_Core_DontClip 128L
#undef org_kde_koala_Core_ExpandTabs
#define org_kde_koala_Core_ExpandTabs 256L
#undef org_kde_koala_Core_ShowPrefix
#define org_kde_koala_Core_ShowPrefix 512L
#undef org_kde_koala_Core_WordBreak
#define org_kde_koala_Core_WordBreak 1024L
#undef org_kde_koala_Core_DontPrint
#define org_kde_koala_Core_DontPrint 4096L
#undef org_kde_koala_Core_WState_Created
#define org_kde_koala_Core_WState_Created 1L
#undef org_kde_koala_Core_WState_Disabled
#define org_kde_koala_Core_WState_Disabled 2L
#undef org_kde_koala_Core_WState_Visible
#define org_kde_koala_Core_WState_Visible 4L
#undef org_kde_koala_Core_WState_ForceHide
#define org_kde_koala_Core_WState_ForceHide 8L
#undef org_kde_koala_Core_WState_OwnCursor
#define org_kde_koala_Core_WState_OwnCursor 16L
#undef org_kde_koala_Core_WState_MouseTracking
#define org_kde_koala_Core_WState_MouseTracking 32L
#undef org_kde_koala_Core_WState_CompressKeys
#define org_kde_koala_Core_WState_CompressKeys 64L
#undef org_kde_koala_Core_WState_BlockUpdates
#define org_kde_koala_Core_WState_BlockUpdates 128L
#undef org_kde_koala_Core_WState_InPaintEvent
#define org_kde_koala_Core_WState_InPaintEvent 256L
#undef org_kde_koala_Core_WState_Reparented
#define org_kde_koala_Core_WState_Reparented 512L
#undef org_kde_koala_Core_WState_ConfigPending
#define org_kde_koala_Core_WState_ConfigPending 1024L
#undef org_kde_koala_Core_WState_Resized
#define org_kde_koala_Core_WState_Resized 2048L
#undef org_kde_koala_Core_WState_AutoMask
#define org_kde_koala_Core_WState_AutoMask 4096L
#undef org_kde_koala_Core_WState_Polished
#define org_kde_koala_Core_WState_Polished 8192L
#undef org_kde_koala_Core_WState_DND
#define org_kde_koala_Core_WState_DND 16384L
#undef org_kde_koala_Core_WState_Modal
#define org_kde_koala_Core_WState_Modal 32768L
#undef org_kde_koala_Core_WState_Reserved1
#define org_kde_koala_Core_WState_Reserved1 65536L
#undef org_kde_koala_Core_WState_Reserved2
#define org_kde_koala_Core_WState_Reserved2 131072L
#undef org_kde_koala_Core_WState_Reserved3
#define org_kde_koala_Core_WState_Reserved3 262144L
#undef org_kde_koala_Core_WState_Maximized
#define org_kde_koala_Core_WState_Maximized 524288L
#undef org_kde_koala_Core_WState_TranslateBackground
#define org_kde_koala_Core_WState_TranslateBackground 1048576L
#undef org_kde_koala_Core_WState_ForceDisabled
#define org_kde_koala_Core_WState_ForceDisabled 2097152L
#undef org_kde_koala_Core_WState_Exposed
#define org_kde_koala_Core_WState_Exposed 4194304L
#undef org_kde_koala_Core_WType_TopLevel
#define org_kde_koala_Core_WType_TopLevel 1L
#undef org_kde_koala_Core_WType_Modal
#define org_kde_koala_Core_WType_Modal 2L
#undef org_kde_koala_Core_WType_Popup
#define org_kde_koala_Core_WType_Popup 4L
#undef org_kde_koala_Core_WType_Desktop
#define org_kde_koala_Core_WType_Desktop 8L
#undef org_kde_koala_Core_WType_Mask
#define org_kde_koala_Core_WType_Mask 15L
#undef org_kde_koala_Core_WStyle_Customize
#define org_kde_koala_Core_WStyle_Customize 16L
#undef org_kde_koala_Core_WStyle_NormalBorder
#define org_kde_koala_Core_WStyle_NormalBorder 32L
#undef org_kde_koala_Core_WStyle_DialogBorder
#define org_kde_koala_Core_WStyle_DialogBorder 64L
#undef org_kde_koala_Core_WStyle_NoBorder
#define org_kde_koala_Core_WStyle_NoBorder 0L
#undef org_kde_koala_Core_WStyle_Title
#define org_kde_koala_Core_WStyle_Title 128L
#undef org_kde_koala_Core_WStyle_SysMenu
#define org_kde_koala_Core_WStyle_SysMenu 256L
#undef org_kde_koala_Core_WStyle_Minimize
#define org_kde_koala_Core_WStyle_Minimize 512L
#undef org_kde_koala_Core_WStyle_Maximize
#define org_kde_koala_Core_WStyle_Maximize 1024L
#undef org_kde_koala_Core_WStyle_MinMax
#define org_kde_koala_Core_WStyle_MinMax 1536L
#undef org_kde_koala_Core_WStyle_Tool
#define org_kde_koala_Core_WStyle_Tool 2048L
#undef org_kde_koala_Core_WStyle_StaysOnTop
#define org_kde_koala_Core_WStyle_StaysOnTop 4096L
#undef org_kde_koala_Core_WStyle_Dialog
#define org_kde_koala_Core_WStyle_Dialog 8192L
#undef org_kde_koala_Core_WStyle_ContextHelp
#define org_kde_koala_Core_WStyle_ContextHelp 16384L
#undef org_kde_koala_Core_WStyle_NoBorderEx
#define org_kde_koala_Core_WStyle_NoBorderEx 32768L
#undef org_kde_koala_Core_WStyle_Mask
#define org_kde_koala_Core_WStyle_Mask 65520L
#undef org_kde_koala_Core_WDestructiveClose
#define org_kde_koala_Core_WDestructiveClose 65536L
#undef org_kde_koala_Core_WPaintDesktop
#define org_kde_koala_Core_WPaintDesktop 131072L
#undef org_kde_koala_Core_WPaintUnclipped
#define org_kde_koala_Core_WPaintUnclipped 262144L
#undef org_kde_koala_Core_WPaintClever
#define org_kde_koala_Core_WPaintClever 524288L
#undef org_kde_koala_Core_WResizeNoErase
#define org_kde_koala_Core_WResizeNoErase 1048576L
#undef org_kde_koala_Core_WMouseNoMask
#define org_kde_koala_Core_WMouseNoMask 2097152L
#undef org_kde_koala_Core_WNorthWestGravity
#define org_kde_koala_Core_WNorthWestGravity 4194304L
#undef org_kde_koala_Core_WRepaintNoErase
#define org_kde_koala_Core_WRepaintNoErase 8388608L
#undef org_kde_koala_Core_WX11BypassWM
#define org_kde_koala_Core_WX11BypassWM 16777216L
#undef org_kde_koala_Core_WGroupLeader
#define org_kde_koala_Core_WGroupLeader 33554432L
#undef org_kde_koala_Core_ColorMode_Mask
#define org_kde_koala_Core_ColorMode_Mask 3L
#undef org_kde_koala_Core_AutoColor
#define org_kde_koala_Core_AutoColor 0L
#undef org_kde_koala_Core_ColorOnly
#define org_kde_koala_Core_ColorOnly 3L
#undef org_kde_koala_Core_MonoOnly
#define org_kde_koala_Core_MonoOnly 2L
#undef org_kde_koala_Core_AlphaDither_Mask
#define org_kde_koala_Core_AlphaDither_Mask 12L
#undef org_kde_koala_Core_ThresholdAlphaDither
#define org_kde_koala_Core_ThresholdAlphaDither 0L
#undef org_kde_koala_Core_OrderedAlphaDither
#define org_kde_koala_Core_OrderedAlphaDither 4L
#undef org_kde_koala_Core_DiffuseAlphaDither
#define org_kde_koala_Core_DiffuseAlphaDither 8L
#undef org_kde_koala_Core_NoAlpha
#define org_kde_koala_Core_NoAlpha 12L
#undef org_kde_koala_Core_Dither_Mask
#define org_kde_koala_Core_Dither_Mask 48L
#undef org_kde_koala_Core_DiffuseDither
#define org_kde_koala_Core_DiffuseDither 0L
#undef org_kde_koala_Core_OrderedDither
#define org_kde_koala_Core_OrderedDither 16L
#undef org_kde_koala_Core_ThresholdDither
#define org_kde_koala_Core_ThresholdDither 32L
#undef org_kde_koala_Core_DitherMode_Mask
#define org_kde_koala_Core_DitherMode_Mask 192L
#undef org_kde_koala_Core_AutoDither
#define org_kde_koala_Core_AutoDither 0L
#undef org_kde_koala_Core_PreferDither
#define org_kde_koala_Core_PreferDither 64L
#undef org_kde_koala_Core_AvoidDither
#define org_kde_koala_Core_AvoidDither 128L
#undef org_kde_koala_Core_TransparentMode
#define org_kde_koala_Core_TransparentMode 0L
#undef org_kde_koala_Core_OpaqueMode
#define org_kde_koala_Core_OpaqueMode 1L
#undef org_kde_koala_Core_PixelUnit
#define org_kde_koala_Core_PixelUnit 0L
#undef org_kde_koala_Core_LoMetricUnit
#define org_kde_koala_Core_LoMetricUnit 1L
#undef org_kde_koala_Core_HiMetricUnit
#define org_kde_koala_Core_HiMetricUnit 2L
#undef org_kde_koala_Core_LoEnglishUnit
#define org_kde_koala_Core_LoEnglishUnit 3L
#undef org_kde_koala_Core_HiEnglishUnit
#define org_kde_koala_Core_HiEnglishUnit 4L
#undef org_kde_koala_Core_TwipsUnit
#define org_kde_koala_Core_TwipsUnit 5L
#undef org_kde_koala_Core_MacStyle
#define org_kde_koala_Core_MacStyle 0L
#undef org_kde_koala_Core_WindowsStyle
#define org_kde_koala_Core_WindowsStyle 1L
#undef org_kde_koala_Core_Win3Style
#define org_kde_koala_Core_Win3Style 2L
#undef org_kde_koala_Core_PMStyle
#define org_kde_koala_Core_PMStyle 3L
#undef org_kde_koala_Core_MotifStyle
#define org_kde_koala_Core_MotifStyle 4L
#undef org_kde_koala_Core_SHIFT
#define org_kde_koala_Core_SHIFT 2097152L
#undef org_kde_koala_Core_CTRL
#define org_kde_koala_Core_CTRL 4194304L
#undef org_kde_koala_Core_ALT
#define org_kde_koala_Core_ALT 8388608L
#undef org_kde_koala_Core_MODIFIER_MASK
#define org_kde_koala_Core_MODIFIER_MASK 14680064L
#undef org_kde_koala_Core_UNICODE_ACCEL
#define org_kde_koala_Core_UNICODE_ACCEL 268435456L
#undef org_kde_koala_Core_ASCII_ACCEL
#define org_kde_koala_Core_ASCII_ACCEL 268435456L
#undef org_kde_koala_Core_Key_Escape
#define org_kde_koala_Core_Key_Escape 4096L
#undef org_kde_koala_Core_Key_Tab
#define org_kde_koala_Core_Key_Tab 4097L
#undef org_kde_koala_Core_Key_Backtab
#define org_kde_koala_Core_Key_Backtab 4098L
#undef org_kde_koala_Core_Key_BackTab
#define org_kde_koala_Core_Key_BackTab 4098L
#undef org_kde_koala_Core_Key_Backspace
#define org_kde_koala_Core_Key_Backspace 4099L
#undef org_kde_koala_Core_Key_BackSpace
#define org_kde_koala_Core_Key_BackSpace 4099L
#undef org_kde_koala_Core_Key_Return
#define org_kde_koala_Core_Key_Return 4100L
#undef org_kde_koala_Core_Key_Enter
#define org_kde_koala_Core_Key_Enter 4101L
#undef org_kde_koala_Core_Key_Insert
#define org_kde_koala_Core_Key_Insert 4102L
#undef org_kde_koala_Core_Key_Delete
#define org_kde_koala_Core_Key_Delete 4103L
#undef org_kde_koala_Core_Key_Pause
#define org_kde_koala_Core_Key_Pause 4104L
#undef org_kde_koala_Core_Key_Print
#define org_kde_koala_Core_Key_Print 4105L
#undef org_kde_koala_Core_Key_SysReq
#define org_kde_koala_Core_Key_SysReq 4106L
#undef org_kde_koala_Core_Key_Home
#define org_kde_koala_Core_Key_Home 4112L
#undef org_kde_koala_Core_Key_End
#define org_kde_koala_Core_Key_End 4113L
#undef org_kde_koala_Core_Key_Left
#define org_kde_koala_Core_Key_Left 4114L
#undef org_kde_koala_Core_Key_Up
#define org_kde_koala_Core_Key_Up 4115L
#undef org_kde_koala_Core_Key_Right
#define org_kde_koala_Core_Key_Right 4116L
#undef org_kde_koala_Core_Key_Down
#define org_kde_koala_Core_Key_Down 4117L
#undef org_kde_koala_Core_Key_Prior
#define org_kde_koala_Core_Key_Prior 4118L
#undef org_kde_koala_Core_Key_PageUp
#define org_kde_koala_Core_Key_PageUp 4118L
#undef org_kde_koala_Core_Key_Next
#define org_kde_koala_Core_Key_Next 4119L
#undef org_kde_koala_Core_Key_PageDown
#define org_kde_koala_Core_Key_PageDown 4119L
#undef org_kde_koala_Core_Key_Shift
#define org_kde_koala_Core_Key_Shift 4128L
#undef org_kde_koala_Core_Key_Control
#define org_kde_koala_Core_Key_Control 4129L
#undef org_kde_koala_Core_Key_Meta
#define org_kde_koala_Core_Key_Meta 4130L
#undef org_kde_koala_Core_Key_Alt
#define org_kde_koala_Core_Key_Alt 4131L
#undef org_kde_koala_Core_Key_CapsLock
#define org_kde_koala_Core_Key_CapsLock 4132L
#undef org_kde_koala_Core_Key_NumLock
#define org_kde_koala_Core_Key_NumLock 4133L
#undef org_kde_koala_Core_Key_ScrollLock
#define org_kde_koala_Core_Key_ScrollLock 4134L
#undef org_kde_koala_Core_Key_F1
#define org_kde_koala_Core_Key_F1 4144L
#undef org_kde_koala_Core_Key_F2
#define org_kde_koala_Core_Key_F2 4145L
#undef org_kde_koala_Core_Key_F3
#define org_kde_koala_Core_Key_F3 4146L
#undef org_kde_koala_Core_Key_F4
#define org_kde_koala_Core_Key_F4 4147L
#undef org_kde_koala_Core_Key_F5
#define org_kde_koala_Core_Key_F5 4148L
#undef org_kde_koala_Core_Key_F6
#define org_kde_koala_Core_Key_F6 4149L
#undef org_kde_koala_Core_Key_F7
#define org_kde_koala_Core_Key_F7 4150L
#undef org_kde_koala_Core_Key_F8
#define org_kde_koala_Core_Key_F8 4151L
#undef org_kde_koala_Core_Key_F9
#define org_kde_koala_Core_Key_F9 4152L
#undef org_kde_koala_Core_Key_F10
#define org_kde_koala_Core_Key_F10 4153L
#undef org_kde_koala_Core_Key_F11
#define org_kde_koala_Core_Key_F11 4154L
#undef org_kde_koala_Core_Key_F12
#define org_kde_koala_Core_Key_F12 4155L
#undef org_kde_koala_Core_Key_F13
#define org_kde_koala_Core_Key_F13 4156L
#undef org_kde_koala_Core_Key_F14
#define org_kde_koala_Core_Key_F14 4157L
#undef org_kde_koala_Core_Key_F15
#define org_kde_koala_Core_Key_F15 4158L
#undef org_kde_koala_Core_Key_F16
#define org_kde_koala_Core_Key_F16 4159L
#undef org_kde_koala_Core_Key_F17
#define org_kde_koala_Core_Key_F17 4160L
#undef org_kde_koala_Core_Key_F18
#define org_kde_koala_Core_Key_F18 4161L
#undef org_kde_koala_Core_Key_F19
#define org_kde_koala_Core_Key_F19 4162L
#undef org_kde_koala_Core_Key_F20
#define org_kde_koala_Core_Key_F20 4163L
#undef org_kde_koala_Core_Key_F21
#define org_kde_koala_Core_Key_F21 4164L
#undef org_kde_koala_Core_Key_F22
#define org_kde_koala_Core_Key_F22 4165L
#undef org_kde_koala_Core_Key_F23
#define org_kde_koala_Core_Key_F23 4166L
#undef org_kde_koala_Core_Key_F24
#define org_kde_koala_Core_Key_F24 4167L
#undef org_kde_koala_Core_Key_F25
#define org_kde_koala_Core_Key_F25 4168L
#undef org_kde_koala_Core_Key_F26
#define org_kde_koala_Core_Key_F26 4169L
#undef org_kde_koala_Core_Key_F27
#define org_kde_koala_Core_Key_F27 4170L
#undef org_kde_koala_Core_Key_F28
#define org_kde_koala_Core_Key_F28 4171L
#undef org_kde_koala_Core_Key_F29
#define org_kde_koala_Core_Key_F29 4172L
#undef org_kde_koala_Core_Key_F30
#define org_kde_koala_Core_Key_F30 4173L
#undef org_kde_koala_Core_Key_F31
#define org_kde_koala_Core_Key_F31 4174L
#undef org_kde_koala_Core_Key_F32
#define org_kde_koala_Core_Key_F32 4175L
#undef org_kde_koala_Core_Key_F33
#define org_kde_koala_Core_Key_F33 4176L
#undef org_kde_koala_Core_Key_F34
#define org_kde_koala_Core_Key_F34 4177L
#undef org_kde_koala_Core_Key_F35
#define org_kde_koala_Core_Key_F35 4178L
#undef org_kde_koala_Core_Key_Super_L
#define org_kde_koala_Core_Key_Super_L 4179L
#undef org_kde_koala_Core_Key_Super_R
#define org_kde_koala_Core_Key_Super_R 4180L
#undef org_kde_koala_Core_Key_Menu
#define org_kde_koala_Core_Key_Menu 4181L
#undef org_kde_koala_Core_Key_Hyper_L
#define org_kde_koala_Core_Key_Hyper_L 4182L
#undef org_kde_koala_Core_Key_Hyper_R
#define org_kde_koala_Core_Key_Hyper_R 4183L
#undef org_kde_koala_Core_Key_Help
#define org_kde_koala_Core_Key_Help 4184L
#undef org_kde_koala_Core_Key_Space
#define org_kde_koala_Core_Key_Space 32L
#undef org_kde_koala_Core_Key_Any
#define org_kde_koala_Core_Key_Any 32L
#undef org_kde_koala_Core_Key_Exclam
#define org_kde_koala_Core_Key_Exclam 33L
#undef org_kde_koala_Core_Key_QuoteDbl
#define org_kde_koala_Core_Key_QuoteDbl 34L
#undef org_kde_koala_Core_Key_NumberSign
#define org_kde_koala_Core_Key_NumberSign 35L
#undef org_kde_koala_Core_Key_Dollar
#define org_kde_koala_Core_Key_Dollar 36L
#undef org_kde_koala_Core_Key_Percent
#define org_kde_koala_Core_Key_Percent 37L
#undef org_kde_koala_Core_Key_Ampersand
#define org_kde_koala_Core_Key_Ampersand 38L
#undef org_kde_koala_Core_Key_Apostrophe
#define org_kde_koala_Core_Key_Apostrophe 39L
#undef org_kde_koala_Core_Key_ParenLeft
#define org_kde_koala_Core_Key_ParenLeft 40L
#undef org_kde_koala_Core_Key_ParenRight
#define org_kde_koala_Core_Key_ParenRight 41L
#undef org_kde_koala_Core_Key_Asterisk
#define org_kde_koala_Core_Key_Asterisk 42L
#undef org_kde_koala_Core_Key_Plus
#define org_kde_koala_Core_Key_Plus 43L
#undef org_kde_koala_Core_Key_Comma
#define org_kde_koala_Core_Key_Comma 44L
#undef org_kde_koala_Core_Key_Minus
#define org_kde_koala_Core_Key_Minus 45L
#undef org_kde_koala_Core_Key_Period
#define org_kde_koala_Core_Key_Period 46L
#undef org_kde_koala_Core_Key_Slash
#define org_kde_koala_Core_Key_Slash 47L
#undef org_kde_koala_Core_Key_0
#define org_kde_koala_Core_Key_0 48L
#undef org_kde_koala_Core_Key_1
#define org_kde_koala_Core_Key_1 49L
#undef org_kde_koala_Core_Key_2
#define org_kde_koala_Core_Key_2 50L
#undef org_kde_koala_Core_Key_3
#define org_kde_koala_Core_Key_3 51L
#undef org_kde_koala_Core_Key_4
#define org_kde_koala_Core_Key_4 52L
#undef org_kde_koala_Core_Key_5
#define org_kde_koala_Core_Key_5 53L
#undef org_kde_koala_Core_Key_6
#define org_kde_koala_Core_Key_6 54L
#undef org_kde_koala_Core_Key_7
#define org_kde_koala_Core_Key_7 55L
#undef org_kde_koala_Core_Key_8
#define org_kde_koala_Core_Key_8 56L
#undef org_kde_koala_Core_Key_9
#define org_kde_koala_Core_Key_9 57L
#undef org_kde_koala_Core_Key_Colon
#define org_kde_koala_Core_Key_Colon 58L
#undef org_kde_koala_Core_Key_Semicolon
#define org_kde_koala_Core_Key_Semicolon 59L
#undef org_kde_koala_Core_Key_Less
#define org_kde_koala_Core_Key_Less 60L
#undef org_kde_koala_Core_Key_Equal
#define org_kde_koala_Core_Key_Equal 61L
#undef org_kde_koala_Core_Key_Greater
#define org_kde_koala_Core_Key_Greater 62L
#undef org_kde_koala_Core_Key_Question
#define org_kde_koala_Core_Key_Question 63L
#undef org_kde_koala_Core_Key_At
#define org_kde_koala_Core_Key_At 64L
#undef org_kde_koala_Core_Key_A
#define org_kde_koala_Core_Key_A 65L
#undef org_kde_koala_Core_Key_B
#define org_kde_koala_Core_Key_B 66L
#undef org_kde_koala_Core_Key_C
#define org_kde_koala_Core_Key_C 67L
#undef org_kde_koala_Core_Key_D
#define org_kde_koala_Core_Key_D 68L
#undef org_kde_koala_Core_Key_E
#define org_kde_koala_Core_Key_E 69L
#undef org_kde_koala_Core_Key_F
#define org_kde_koala_Core_Key_F 70L
#undef org_kde_koala_Core_Key_G
#define org_kde_koala_Core_Key_G 71L
#undef org_kde_koala_Core_Key_H
#define org_kde_koala_Core_Key_H 72L
#undef org_kde_koala_Core_Key_I
#define org_kde_koala_Core_Key_I 73L
#undef org_kde_koala_Core_Key_J
#define org_kde_koala_Core_Key_J 74L
#undef org_kde_koala_Core_Key_K
#define org_kde_koala_Core_Key_K 75L
#undef org_kde_koala_Core_Key_L
#define org_kde_koala_Core_Key_L 76L
#undef org_kde_koala_Core_Key_M
#define org_kde_koala_Core_Key_M 77L
#undef org_kde_koala_Core_Key_N
#define org_kde_koala_Core_Key_N 78L
#undef org_kde_koala_Core_Key_O
#define org_kde_koala_Core_Key_O 79L
#undef org_kde_koala_Core_Key_P
#define org_kde_koala_Core_Key_P 80L
#undef org_kde_koala_Core_Key_Q
#define org_kde_koala_Core_Key_Q 81L
#undef org_kde_koala_Core_Key_R
#define org_kde_koala_Core_Key_R 82L
#undef org_kde_koala_Core_Key_S
#define org_kde_koala_Core_Key_S 83L
#undef org_kde_koala_Core_Key_T
#define org_kde_koala_Core_Key_T 84L
#undef org_kde_koala_Core_Key_U
#define org_kde_koala_Core_Key_U 85L
#undef org_kde_koala_Core_Key_V
#define org_kde_koala_Core_Key_V 86L
#undef org_kde_koala_Core_Key_W
#define org_kde_koala_Core_Key_W 87L
#undef org_kde_koala_Core_Key_X
#define org_kde_koala_Core_Key_X 88L
#undef org_kde_koala_Core_Key_Y
#define org_kde_koala_Core_Key_Y 89L
#undef org_kde_koala_Core_Key_Z
#define org_kde_koala_Core_Key_Z 90L
#undef org_kde_koala_Core_Key_BracketLeft
#define org_kde_koala_Core_Key_BracketLeft 91L
#undef org_kde_koala_Core_Key_Backslash
#define org_kde_koala_Core_Key_Backslash 92L
#undef org_kde_koala_Core_Key_BracketRight
#define org_kde_koala_Core_Key_BracketRight 93L
#undef org_kde_koala_Core_Key_AsciiCircum
#define org_kde_koala_Core_Key_AsciiCircum 94L
#undef org_kde_koala_Core_Key_Underscore
#define org_kde_koala_Core_Key_Underscore 95L
#undef org_kde_koala_Core_Key_QuoteLeft
#define org_kde_koala_Core_Key_QuoteLeft 96L
#undef org_kde_koala_Core_Key_BraceLeft
#define org_kde_koala_Core_Key_BraceLeft 123L
#undef org_kde_koala_Core_Key_Bar
#define org_kde_koala_Core_Key_Bar 124L
#undef org_kde_koala_Core_Key_BraceRight
#define org_kde_koala_Core_Key_BraceRight 125L
#undef org_kde_koala_Core_Key_AsciiTilde
#define org_kde_koala_Core_Key_AsciiTilde 126L
#undef org_kde_koala_Core_Key_nobreakspace
#define org_kde_koala_Core_Key_nobreakspace 160L
#undef org_kde_koala_Core_Key_exclamdown
#define org_kde_koala_Core_Key_exclamdown 161L
#undef org_kde_koala_Core_Key_cent
#define org_kde_koala_Core_Key_cent 162L
#undef org_kde_koala_Core_Key_sterling
#define org_kde_koala_Core_Key_sterling 163L
#undef org_kde_koala_Core_Key_currency
#define org_kde_koala_Core_Key_currency 164L
#undef org_kde_koala_Core_Key_yen
#define org_kde_koala_Core_Key_yen 165L
#undef org_kde_koala_Core_Key_brokenbar
#define org_kde_koala_Core_Key_brokenbar 166L
#undef org_kde_koala_Core_Key_section
#define org_kde_koala_Core_Key_section 167L
#undef org_kde_koala_Core_Key_diaeresis
#define org_kde_koala_Core_Key_diaeresis 168L
#undef org_kde_koala_Core_Key_copyright
#define org_kde_koala_Core_Key_copyright 169L
#undef org_kde_koala_Core_Key_ordfeminine
#define org_kde_koala_Core_Key_ordfeminine 170L
#undef org_kde_koala_Core_Key_guillemotleft
#define org_kde_koala_Core_Key_guillemotleft 171L
#undef org_kde_koala_Core_Key_notsign
#define org_kde_koala_Core_Key_notsign 172L
#undef org_kde_koala_Core_Key_hyphen
#define org_kde_koala_Core_Key_hyphen 173L
#undef org_kde_koala_Core_Key_registered
#define org_kde_koala_Core_Key_registered 174L
#undef org_kde_koala_Core_Key_macron
#define org_kde_koala_Core_Key_macron 175L
#undef org_kde_koala_Core_Key_degree
#define org_kde_koala_Core_Key_degree 176L
#undef org_kde_koala_Core_Key_plusminus
#define org_kde_koala_Core_Key_plusminus 177L
#undef org_kde_koala_Core_Key_twosuperior
#define org_kde_koala_Core_Key_twosuperior 178L
#undef org_kde_koala_Core_Key_threesuperior
#define org_kde_koala_Core_Key_threesuperior 179L
#undef org_kde_koala_Core_Key_acute
#define org_kde_koala_Core_Key_acute 180L
#undef org_kde_koala_Core_Key_mu
#define org_kde_koala_Core_Key_mu 181L
#undef org_kde_koala_Core_Key_paragraph
#define org_kde_koala_Core_Key_paragraph 182L
#undef org_kde_koala_Core_Key_periodcentered
#define org_kde_koala_Core_Key_periodcentered 183L
#undef org_kde_koala_Core_Key_cedilla
#define org_kde_koala_Core_Key_cedilla 184L
#undef org_kde_koala_Core_Key_onesuperior
#define org_kde_koala_Core_Key_onesuperior 185L
#undef org_kde_koala_Core_Key_masculine
#define org_kde_koala_Core_Key_masculine 186L
#undef org_kde_koala_Core_Key_guillemotright
#define org_kde_koala_Core_Key_guillemotright 187L
#undef org_kde_koala_Core_Key_onequarter
#define org_kde_koala_Core_Key_onequarter 188L
#undef org_kde_koala_Core_Key_onehalf
#define org_kde_koala_Core_Key_onehalf 189L
#undef org_kde_koala_Core_Key_threequarters
#define org_kde_koala_Core_Key_threequarters 190L
#undef org_kde_koala_Core_Key_questiondown
#define org_kde_koala_Core_Key_questiondown 191L
#undef org_kde_koala_Core_Key_Agrave
#define org_kde_koala_Core_Key_Agrave 192L
#undef org_kde_koala_Core_Key_Aacute
#define org_kde_koala_Core_Key_Aacute 193L
#undef org_kde_koala_Core_Key_Acircumflex
#define org_kde_koala_Core_Key_Acircumflex 194L
#undef org_kde_koala_Core_Key_Atilde
#define org_kde_koala_Core_Key_Atilde 195L
#undef org_kde_koala_Core_Key_Adiaeresis
#define org_kde_koala_Core_Key_Adiaeresis 196L
#undef org_kde_koala_Core_Key_Aring
#define org_kde_koala_Core_Key_Aring 197L
#undef org_kde_koala_Core_Key_AE
#define org_kde_koala_Core_Key_AE 198L
#undef org_kde_koala_Core_Key_Ccedilla
#define org_kde_koala_Core_Key_Ccedilla 199L
#undef org_kde_koala_Core_Key_Egrave
#define org_kde_koala_Core_Key_Egrave 200L
#undef org_kde_koala_Core_Key_Eacute
#define org_kde_koala_Core_Key_Eacute 201L
#undef org_kde_koala_Core_Key_Ecircumflex
#define org_kde_koala_Core_Key_Ecircumflex 202L
#undef org_kde_koala_Core_Key_Ediaeresis
#define org_kde_koala_Core_Key_Ediaeresis 203L
#undef org_kde_koala_Core_Key_Igrave
#define org_kde_koala_Core_Key_Igrave 204L
#undef org_kde_koala_Core_Key_Iacute
#define org_kde_koala_Core_Key_Iacute 205L
#undef org_kde_koala_Core_Key_Icircumflex
#define org_kde_koala_Core_Key_Icircumflex 206L
#undef org_kde_koala_Core_Key_Idiaeresis
#define org_kde_koala_Core_Key_Idiaeresis 207L
#undef org_kde_koala_Core_Key_ETH
#define org_kde_koala_Core_Key_ETH 208L
#undef org_kde_koala_Core_Key_Ntilde
#define org_kde_koala_Core_Key_Ntilde 209L
#undef org_kde_koala_Core_Key_Ograve
#define org_kde_koala_Core_Key_Ograve 210L
#undef org_kde_koala_Core_Key_Oacute
#define org_kde_koala_Core_Key_Oacute 211L
#undef org_kde_koala_Core_Key_Ocircumflex
#define org_kde_koala_Core_Key_Ocircumflex 212L
#undef org_kde_koala_Core_Key_Otilde
#define org_kde_koala_Core_Key_Otilde 213L
#undef org_kde_koala_Core_Key_Odiaeresis
#define org_kde_koala_Core_Key_Odiaeresis 214L
#undef org_kde_koala_Core_Key_multiply
#define org_kde_koala_Core_Key_multiply 215L
#undef org_kde_koala_Core_Key_Ooblique
#define org_kde_koala_Core_Key_Ooblique 216L
#undef org_kde_koala_Core_Key_Ugrave
#define org_kde_koala_Core_Key_Ugrave 217L
#undef org_kde_koala_Core_Key_Uacute
#define org_kde_koala_Core_Key_Uacute 218L
#undef org_kde_koala_Core_Key_Ucircumflex
#define org_kde_koala_Core_Key_Ucircumflex 219L
#undef org_kde_koala_Core_Key_Udiaeresis
#define org_kde_koala_Core_Key_Udiaeresis 220L
#undef org_kde_koala_Core_Key_Yacute
#define org_kde_koala_Core_Key_Yacute 221L
#undef org_kde_koala_Core_Key_THORN
#define org_kde_koala_Core_Key_THORN 222L
#undef org_kde_koala_Core_Key_ssharp
#define org_kde_koala_Core_Key_ssharp 223L
#undef org_kde_koala_Core_Key_agrave
#define org_kde_koala_Core_Key_agrave 224L
#undef org_kde_koala_Core_Key_aacute
#define org_kde_koala_Core_Key_aacute 225L
#undef org_kde_koala_Core_Key_acircumflex
#define org_kde_koala_Core_Key_acircumflex 226L
#undef org_kde_koala_Core_Key_atilde
#define org_kde_koala_Core_Key_atilde 227L
#undef org_kde_koala_Core_Key_adiaeresis
#define org_kde_koala_Core_Key_adiaeresis 228L
#undef org_kde_koala_Core_Key_aring
#define org_kde_koala_Core_Key_aring 229L
#undef org_kde_koala_Core_Key_ae
#define org_kde_koala_Core_Key_ae 230L
#undef org_kde_koala_Core_Key_ccedilla
#define org_kde_koala_Core_Key_ccedilla 231L
#undef org_kde_koala_Core_Key_egrave
#define org_kde_koala_Core_Key_egrave 232L
#undef org_kde_koala_Core_Key_eacute
#define org_kde_koala_Core_Key_eacute 233L
#undef org_kde_koala_Core_Key_ecircumflex
#define org_kde_koala_Core_Key_ecircumflex 234L
#undef org_kde_koala_Core_Key_ediaeresis
#define org_kde_koala_Core_Key_ediaeresis 235L
#undef org_kde_koala_Core_Key_igrave
#define org_kde_koala_Core_Key_igrave 236L
#undef org_kde_koala_Core_Key_iacute
#define org_kde_koala_Core_Key_iacute 237L
#undef org_kde_koala_Core_Key_icircumflex
#define org_kde_koala_Core_Key_icircumflex 238L
#undef org_kde_koala_Core_Key_idiaeresis
#define org_kde_koala_Core_Key_idiaeresis 239L
#undef org_kde_koala_Core_Key_eth
#define org_kde_koala_Core_Key_eth 240L
#undef org_kde_koala_Core_Key_ntilde
#define org_kde_koala_Core_Key_ntilde 241L
#undef org_kde_koala_Core_Key_ograve
#define org_kde_koala_Core_Key_ograve 242L
#undef org_kde_koala_Core_Key_oacute
#define org_kde_koala_Core_Key_oacute 243L
#undef org_kde_koala_Core_Key_ocircumflex
#define org_kde_koala_Core_Key_ocircumflex 244L
#undef org_kde_koala_Core_Key_otilde
#define org_kde_koala_Core_Key_otilde 245L
#undef org_kde_koala_Core_Key_odiaeresis
#define org_kde_koala_Core_Key_odiaeresis 246L
#undef org_kde_koala_Core_Key_division
#define org_kde_koala_Core_Key_division 247L
#undef org_kde_koala_Core_Key_oslash
#define org_kde_koala_Core_Key_oslash 248L
#undef org_kde_koala_Core_Key_ugrave
#define org_kde_koala_Core_Key_ugrave 249L
#undef org_kde_koala_Core_Key_uacute
#define org_kde_koala_Core_Key_uacute 250L
#undef org_kde_koala_Core_Key_ucircumflex
#define org_kde_koala_Core_Key_ucircumflex 251L
#undef org_kde_koala_Core_Key_udiaeresis
#define org_kde_koala_Core_Key_udiaeresis 252L
#undef org_kde_koala_Core_Key_yacute
#define org_kde_koala_Core_Key_yacute 253L
#undef org_kde_koala_Core_Key_thorn
#define org_kde_koala_Core_Key_thorn 254L
#undef org_kde_koala_Core_Key_ydiaeresis
#define org_kde_koala_Core_Key_ydiaeresis 255L
#undef org_kde_koala_Core_Key_unknown
#define org_kde_koala_Core_Key_unknown 65535L
#undef org_kde_koala_Core_UpArrow
#define org_kde_koala_Core_UpArrow 0L
#undef org_kde_koala_Core_DownArrow
#define org_kde_koala_Core_DownArrow 1L
#undef org_kde_koala_Core_LeftArrow
#define org_kde_koala_Core_LeftArrow 2L
#undef org_kde_koala_Core_RightArrow
#define org_kde_koala_Core_RightArrow 3L
#undef org_kde_koala_Core_CopyROP
#define org_kde_koala_Core_CopyROP 0L
#undef org_kde_koala_Core_OrROP
#define org_kde_koala_Core_OrROP 1L
#undef org_kde_koala_Core_XorROP
#define org_kde_koala_Core_XorROP 2L
#undef org_kde_koala_Core_NotAndROP
#define org_kde_koala_Core_NotAndROP 3L
#undef org_kde_koala_Core_EraseROP
#define org_kde_koala_Core_EraseROP 3L
#undef org_kde_koala_Core_NotCopyROP
#define org_kde_koala_Core_NotCopyROP 4L
#undef org_kde_koala_Core_NotOrROP
#define org_kde_koala_Core_NotOrROP 5L
#undef org_kde_koala_Core_NotXorROP
#define org_kde_koala_Core_NotXorROP 6L
#undef org_kde_koala_Core_AndROP
#define org_kde_koala_Core_AndROP 7L
#undef org_kde_koala_Core_NotEraseROP
#define org_kde_koala_Core_NotEraseROP 7L
#undef org_kde_koala_Core_NotROP
#define org_kde_koala_Core_NotROP 8L
#undef org_kde_koala_Core_ClearROP
#define org_kde_koala_Core_ClearROP 9L
#undef org_kde_koala_Core_SetROP
#define org_kde_koala_Core_SetROP 10L
#undef org_kde_koala_Core_NopROP
#define org_kde_koala_Core_NopROP 11L
#undef org_kde_koala_Core_AndNotROP
#define org_kde_koala_Core_AndNotROP 12L
#undef org_kde_koala_Core_OrNotROP
#define org_kde_koala_Core_OrNotROP 13L
#undef org_kde_koala_Core_NandROP
#define org_kde_koala_Core_NandROP 14L
#undef org_kde_koala_Core_NorROP
#define org_kde_koala_Core_NorROP 15L
#undef org_kde_koala_Core_LastROP
#define org_kde_koala_Core_LastROP 15L
#undef org_kde_koala_Core_NoPen
#define org_kde_koala_Core_NoPen 0L
#undef org_kde_koala_Core_SolidLine
#define org_kde_koala_Core_SolidLine 1L
#undef org_kde_koala_Core_DashLine
#define org_kde_koala_Core_DashLine 2L
#undef org_kde_koala_Core_DotLine
#define org_kde_koala_Core_DotLine 3L
#undef org_kde_koala_Core_DashDotLine
#define org_kde_koala_Core_DashDotLine 4L
#undef org_kde_koala_Core_DashDotDotLine
#define org_kde_koala_Core_DashDotDotLine 5L
#undef org_kde_koala_Core_MPenStyle
#define org_kde_koala_Core_MPenStyle 15L
#undef org_kde_koala_Core_FlatCap
#define org_kde_koala_Core_FlatCap 0L
#undef org_kde_koala_Core_SquareCap
#define org_kde_koala_Core_SquareCap 16L
#undef org_kde_koala_Core_RoundCap
#define org_kde_koala_Core_RoundCap 32L
#undef org_kde_koala_Core_MPenCapStyle
#define org_kde_koala_Core_MPenCapStyle 48L
#undef org_kde_koala_Core_MiterJoin
#define org_kde_koala_Core_MiterJoin 0L
#undef org_kde_koala_Core_BevelJoin
#define org_kde_koala_Core_BevelJoin 64L
#undef org_kde_koala_Core_RoundJoin
#define org_kde_koala_Core_RoundJoin 128L
#undef org_kde_koala_Core_MPenJoinStyle
#define org_kde_koala_Core_MPenJoinStyle 192L
#undef org_kde_koala_Core_NoBrush
#define org_kde_koala_Core_NoBrush 0L
#undef org_kde_koala_Core_SolidPattern
#define org_kde_koala_Core_SolidPattern 1L
#undef org_kde_koala_Core_Dense1Pattern
#define org_kde_koala_Core_Dense1Pattern 2L
#undef org_kde_koala_Core_Dense2Pattern
#define org_kde_koala_Core_Dense2Pattern 3L
#undef org_kde_koala_Core_Dense3Pattern
#define org_kde_koala_Core_Dense3Pattern 4L
#undef org_kde_koala_Core_Dense4Pattern
#define org_kde_koala_Core_Dense4Pattern 5L
#undef org_kde_koala_Core_Dense5Pattern
#define org_kde_koala_Core_Dense5Pattern 6L
#undef org_kde_koala_Core_Dense6Pattern
#define org_kde_koala_Core_Dense6Pattern 7L
#undef org_kde_koala_Core_Dense7Pattern
#define org_kde_koala_Core_Dense7Pattern 8L
#undef org_kde_koala_Core_HorPattern
#define org_kde_koala_Core_HorPattern 9L
#undef org_kde_koala_Core_VerPattern
#define org_kde_koala_Core_VerPattern 10L
#undef org_kde_koala_Core_CrossPattern
#define org_kde_koala_Core_CrossPattern 11L
#undef org_kde_koala_Core_BDiagPattern
#define org_kde_koala_Core_BDiagPattern 12L
#undef org_kde_koala_Core_FDiagPattern
#define org_kde_koala_Core_FDiagPattern 13L
#undef org_kde_koala_Core_DiagCrossPattern
#define org_kde_koala_Core_DiagCrossPattern 14L
#undef org_kde_koala_Core_CustomPattern
#define org_kde_koala_Core_CustomPattern 24L
#undef org_kde_koala_Core_WV_32s
#define org_kde_koala_Core_WV_32s 1L
#undef org_kde_koala_Core_WV_95
#define org_kde_koala_Core_WV_95 2L
#undef org_kde_koala_Core_WV_98
#define org_kde_koala_Core_WV_98 3L
#undef org_kde_koala_Core_WV_DOS_based
#define org_kde_koala_Core_WV_DOS_based 15L
#undef org_kde_koala_Core_WV_NT
#define org_kde_koala_Core_WV_NT 16L
#undef org_kde_koala_Core_WV_2000
#define org_kde_koala_Core_WV_2000 32L
#undef org_kde_koala_Core_WV_NT_based
#define org_kde_koala_Core_WV_NT_based 240L
#undef org_kde_koala_Core_UI_General
#define org_kde_koala_Core_UI_General 0L
#undef org_kde_koala_Core_UI_AnimateMenu
#define org_kde_koala_Core_UI_AnimateMenu 1L
#undef org_kde_koala_Core_UI_FadeMenu
#define org_kde_koala_Core_UI_FadeMenu 2L
#undef org_kde_koala_Core_UI_AnimateCombo
#define org_kde_koala_Core_UI_AnimateCombo 3L
#undef org_kde_koala_Core_UI_AnimateTooltip
#define org_kde_koala_Core_UI_AnimateTooltip 4L
#undef org_kde_koala_Core_UI_FadeTooltip
#define org_kde_koala_Core_UI_FadeTooltip 5L
#undef org_kde_koala_Core_PlainText
#define org_kde_koala_Core_PlainText 0L
#undef org_kde_koala_Core_RichText
#define org_kde_koala_Core_RichText 1L
#undef org_kde_koala_Core_AutoText
#define org_kde_koala_Core_AutoText 2L
/*
 * Class:     org_kde_koala_Core
 * Method:    editor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kde_koala_Core_editor
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    embedWidget
 * Signature: (Lorg/kde/qt/QWidget;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_embedWidget
  (JNIEnv *, jobject, jobject, jint, jstring);

/*
 * Class:     org_kde_koala_Core
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoDocumentationFile
 * Signature: (Lorg/kde/koala/KURL;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoDocumentationFile__Lorg_kde_koala_KURL_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoDocumentationFile
 * Signature: (Lorg/kde/koala/KURL;I)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoDocumentationFile__Lorg_kde_koala_KURL_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoExecutionPoint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoExecutionPoint__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoExecutionPoint
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoExecutionPoint__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoFile
 * Signature: (Lorg/kde/koala/KURL;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoFile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoSourceFile
 * Signature: (Lorg/kde/koala/KURL;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoSourceFile__Lorg_kde_koala_KURL_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    gotoSourceFile
 * Signature: (Lorg/kde/koala/KURL;II)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_gotoSourceFile__Lorg_kde_koala_KURL_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_kde_koala_Core
 * Method:    message
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_message
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kde_koala_Core
 * Method:    newCore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_newCore
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    partManager
 * Signature: ()Lorg/kde/koala/PartManager;
 */
JNIEXPORT jobject JNICALL Java_org_kde_koala_Core_partManager
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    raiseWidget
 * Signature: (Lorg/kde/qt/QWidget;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_raiseWidget
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    revertAllFiles
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_revertAllFiles
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    running
 * Signature: (Lorg/kde/koala/KDevPart;Z)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_running
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_kde_koala_Core
 * Method:    saveAllFiles
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_saveAllFiles
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_Core
 * Method:    setBreakpoint
 * Signature: (Ljava/lang/String;IIZZ)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_Core_setBreakpoint
  (JNIEnv *, jobject, jstring, jint, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
