/***************************************************************************
                            KDevProject.cpp -  description
                             -------------------
    begin                : Wed Dec 19 15:43:05 2001
    copyright            : (C) 2000-2001 Lost Highway Ltd.
    email                : Richard_Dale@tipitina.demon.co.uk
    generated by         : duke@tipitina on Wed Dec 19 15:43:05 2001, using kalyptus 0.91.
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
***************************************************************************/

#define _BOOL_H_
#include <kdevproject.h>
#include <qstring.h>
#include <qcstring.h>

#include <qtjava/QtSupport.h>
#include <kdejava/KDESupport.h>
#include <kdejava/KDevProject.h>

JNIEXPORT void JNICALL
Java_org_kde_koala_KDevProject_finalize(JNIEnv *env, jobject obj)
{
	if (QtSupport::allocatedInJavaWorld(env, obj)) {
		delete (KDevProject*)QtSupport::getQt(env, obj);
		QtSupport::setQt(env, obj, 0);
	}
	return;
}

JNIEXPORT void JNICALL
Java_org_kde_koala_KDevProject_openProject(JNIEnv *env, jobject obj, jstring dirName)
{
static QString * _qstring_dirName = 0;
	((KDevProject*) QtSupport::getQt(env, obj))->openProject((QString&) * (QString *) QtSupport::toQString(env, dirName, &_qstring_dirName));
	return;
}

JNIEXPORT void JNICALL
Java_org_kde_koala_KDevProject_closeProject(JNIEnv *env, jobject obj)
{
	((KDevProject*) QtSupport::getQt(env, obj))->closeProject();
	return;
}

JNIEXPORT jstring JNICALL
Java_org_kde_koala_KDevProject_mainProgram(JNIEnv *env, jobject obj)
{
	QString  _qstring;
	_qstring = ((KDevProject*) QtSupport::getQt(env, obj))->mainProgram();
	return QtSupport::fromQString(env, &_qstring);
}

JNIEXPORT jstring JNICALL
Java_org_kde_koala_KDevProject_projectDirectory(JNIEnv *env, jobject obj)
{
	QString  _qstring;
	_qstring = ((KDevProject*) QtSupport::getQt(env, obj))->projectDirectory();
	return QtSupport::fromQString(env, &_qstring);
}

JNIEXPORT jobject JNICALL
Java_org_kde_koala_KDevProject_allSourceFiles(JNIEnv *env, jobject obj)
{
	QStringList  _qlist;
	_qlist = ((KDevProject*) QtSupport::getQt(env, obj))->allSourceFiles();
	return (jobject) QtSupport::arrayWithQStringList(env, (QStringList *) &_qlist);
}

