/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kde_koala_ParsedAttribute */

#ifndef _Included_org_kde_koala_ParsedAttribute
#define _Included_org_kde_koala_ParsedAttribute
#ifdef __cplusplus
extern "C" {
#endif
#undef org_kde_koala_ParsedAttribute_PIT_UNKNOWN
#define org_kde_koala_ParsedAttribute_PIT_UNKNOWN 0L
#undef org_kde_koala_ParsedAttribute_PIT_CLASS
#define org_kde_koala_ParsedAttribute_PIT_CLASS 1L
#undef org_kde_koala_ParsedAttribute_PIT_METHOD
#define org_kde_koala_ParsedAttribute_PIT_METHOD 2L
#undef org_kde_koala_ParsedAttribute_PIT_ATTRIBUTE
#define org_kde_koala_ParsedAttribute_PIT_ATTRIBUTE 3L
#undef org_kde_koala_ParsedAttribute_PIT_STRUCT
#define org_kde_koala_ParsedAttribute_PIT_STRUCT 4L
#undef org_kde_koala_ParsedAttribute_PIT_SCOPE
#define org_kde_koala_ParsedAttribute_PIT_SCOPE 5L
#undef org_kde_koala_ParsedAttribute_PIE_GLOBAL
#define org_kde_koala_ParsedAttribute_PIE_GLOBAL 0L
#undef org_kde_koala_ParsedAttribute_PIE_PUBLIC
#define org_kde_koala_ParsedAttribute_PIE_PUBLIC 1L
#undef org_kde_koala_ParsedAttribute_PIE_PROTECTED
#define org_kde_koala_ParsedAttribute_PIE_PROTECTED 2L
#undef org_kde_koala_ParsedAttribute_PIE_PRIVATE
#define org_kde_koala_ParsedAttribute_PIE_PRIVATE 3L
/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    asString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kde_koala_ParsedAttribute_asString
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    copy
 * Signature: (Lorg/kde/koala/ParsedAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_copy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    isConst
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kde_koala_ParsedAttribute_isConst
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    isEqual
 * Signature: (Lorg/kde/koala/ParsedAttribute;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kde_koala_ParsedAttribute_isEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    isInHFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kde_koala_ParsedAttribute_isInHFile
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    isStatic
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kde_koala_ParsedAttribute_isStatic
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    namePos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kde_koala_ParsedAttribute_namePos
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    newParsedAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_newParsedAttribute
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    out
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_out
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setIsConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setIsConst__
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setIsConst
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setIsConst__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setIsInHFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setIsInHFile__
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setIsInHFile
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setIsInHFile__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setIsStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setIsStatic__
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setIsStatic
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setIsStatic__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setNamePos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setNamePos
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    setType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_ParsedAttribute_setType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kde_koala_ParsedAttribute
 * Method:    type
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kde_koala_ParsedAttribute_type
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
