/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kde_koala_PersistantClassStore */

#ifndef _Included_org_kde_koala_PersistantClassStore
#define _Included_org_kde_koala_PersistantClassStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_close
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    exists
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kde_koala_PersistantClassStore_exists
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    newPersistantClassStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_newPersistantClassStore
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    open
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kde_koala_PersistantClassStore_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    restoreAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_restoreAll
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    setFileName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_setFileName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    setPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_setPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    storeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_storeAll
  (JNIEnv *, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    storeAttribute
 * Signature: (Lorg/kde/koala/ParsedAttribute;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_storeAttribute
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    storeClass
 * Signature: (Lorg/kde/koala/ParsedClass;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_storeClass
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    storeMethod
 * Signature: (Lorg/kde/koala/ParsedMethod;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_storeMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    storeScope
 * Signature: (Lorg/kde/koala/ParsedScopeContainer;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_storeScope
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kde_koala_PersistantClassStore
 * Method:    storeStruct
 * Signature: (Lorg/kde/koala/ParsedStruct;)V
 */
JNIEXPORT void JNICALL Java_org_kde_koala_PersistantClassStore_storeStruct
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
