{
    "KPlugin": {
        "Authors": [
            {
                "Email": "powerfox@kde.ru",
                "Name": "Evgeniy Ivanov"
            }
        ],
        "Category": "Version Control",
        "Name": "Git Support",
        "Name[bg]": "Поддръжка на Git",
        "Name[bs]": "Git podrška",
        "Name[ca@valencia]": "Implementació de Git",
        "Name[ca]": "Implementació de Git",
        "Name[cs]": "Podpora Git",
        "Name[da]": "Git-understøttelse",
        "Name[de]": "Git-Unterstützung",
        "Name[el]": "Υποστήριξη Git",
        "Name[en_GB]": "Git Support",
        "Name[es]": "Implementación de Git",
        "Name[et]": "Giti toetus",
        "Name[fi]": "Git-tuki",
        "Name[fr]": "Prise en charge de Git",
        "Name[ga]": "Tacaíocht Git",
        "Name[gl]": "Soporte de GIT",
        "Name[hu]": "Git támogatás",
        "Name[it]": "Supporto Git",
        "Name[ja]": "Git サポート",
        "Name[kk]": "Git қолдауы",
        "Name[nb]": "Git-støtte",
        "Name[nds]": "Git-Ünnerstütten",
        "Name[nl]": "Git-ondersteuning",
        "Name[pa]": "Git ਸਹਿਯੋਗ",
        "Name[pl]": "Obsługa Git",
        "Name[pt]": "Suporte para o Git",
        "Name[pt_BR]": "Suporte ao Git",
        "Name[ru]": "Поддержка Git",
        "Name[sk]": "Podpora GIT",
        "Name[sl]": "Podpora za Git",
        "Name[sv]": "Stöd för Git",
        "Name[tr]": "Git Desteği",
        "Name[ug]": "Git قوللىشى",
        "Name[uk]": "Підтримка Git",
        "Name[x-test]": "xxGit Supportxx",
        "Name[zh_CN]": "Git 支持",
        "Name[zh_TW]": "Git 支援",
        "Description": "This plugin integrates Git to KDevelop",
        "Description[bg]": "Тaзи приставка вгражда Git в KDevelop",
        "Description[bs]": "Ovaj dodatak integriše Git u KDevelop",
        "Description[ca@valencia]": "Este connector integra Git en KDevelop",
        "Description[ca]": "Aquest connector integra Git en KDevelop",
        "Description[da]": "Dette plugin integrerer Git med KDevelop",
        "Description[de]": "Dieses Modul integriert Git in KDevelop.",
        "Description[el]": "Αυτό το πρόσθετο ενσωματώνει το Git στο KDevelop",
        "Description[en_GB]": "This plugin integrates Git to KDevelop",
        "Description[es]": "Este complemento integra Git en KDevelop",
        "Description[et]": "See plugin lõimib Giti KDevelopiga",
        "Description[fi]": "Tämä liitännäinen integroi Git-ohjelman KDevelop-ympäristöön",
        "Description[fr]": "Ce module externe intègre Git dans KDevelop",
        "Description[gl]": "Este complemento integra Git en KDevelop",
        "Description[hu]": "Ez a bővítmény integrálja a Gitet a KDevelopba",
        "Description[it]": "Questa estensione integra Git in KDevelop",
        "Description[ja]": "このプラグインは Git を KDevelop に統合します",
        "Description[kk]": "Бұл Git-ті KDevelop-пен біріктіретін плагині",
        "Description[lv]": "Šis spraudnis integrē Git iekš KDevelop",
        "Description[nb]": "Dette programtillegget integrerer Git i KDevelop",
        "Description[nds]": "Dit Moduul bett Git na KDevelop in",
        "Description[nl]": "Deze plugin integreert Git in KDevelop",
        "Description[pl]": "Wtyczka ta integruje Git z KDevelop",
        "Description[pt]": "Este 'plugin' integra o Git no KDevelop",
        "Description[pt_BR]": "Este plugin integra o Git ao KDevelop",
        "Description[ro]": "Acest modul integrează Git în KDevelop",
        "Description[ru]": "Это расширение интегрирует Git в KDevelop",
        "Description[sk]": "Tento plugin integruje GIT do KDevelop.",
        "Description[sl]": "Vstavek v KDevelop vgradi Git",
        "Description[sv]": "Insticksprogrammet integrerar Git i KDevelop",
        "Description[tr]": "Bu eklenti Git uygulamasını KDevelop ile bütünleştirir",
        "Description[ug]": "بۇ قىستۇرما Git  نى KDevelop قا يۈرۈشلەشتۈرىدۇ",
        "Description[uk]": "Цей додаток призначено для забезпечення підтримки Git у KDevelop",
        "Description[x-test]": "xxThis plugin integrates Git to KDevelopxx",
        "Description[zh_CN]": "此插件对 KDevelop 整合 Git",
        "Description[zh_TW]": "此外掛程式將 Git 整合進 KDevelop",
        "Icon": "git",
        "Id": "kdevgit",
        "License": "GPL",
        "ServiceTypes": [
            "KDevelop/Plugin"
        ],
        "Version": "0.9"
    },
    "X-KDevelop-Category": "Global",
    "X-KDevelop-Mode": "GUI",
    "X-KDevelop-Interfaces": [
        "org.kdevelop.IBasicVersionControl", "org.kdevelop.IDistributedVersionControl"
    ],
    "X-KDevelop-Version": "@KDEV_PLUGIN_VERSION@"
}
