#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-noatunui/plugin.kdevelop",        "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.cvs",            "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-Makefile.am",             "${dest}/Makefile.am" );
install( "${src}/template-common/kde-configure.in.in",         "${dest}/configure.in.in" );
install( "${src}/template-common/kde-app.lsm",                 "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",          "${dest}/po/Makefile.am" );
install( "${src}/template-noatunui/subdirs",               "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-noatunui/src-Makefile.am",       "${dest}/src/Makefile.am" );
install( "${src}/template-noatunui/plugin_app.cpp",        "${dest}/src/plugin_${APPNAMELC}.cpp" );
install( "${src}/template-noatunui/plugin_impl.cpp",       "${dest}/src/plugin_${APPNAMELC}_impl.cpp" );
install( "${src}/template-noatunui/plugin_impl.h",         "${dest}/src/plugin_${APPNAMELC}_impl.h" );
install( "${src}/template-noatunui/plugin.plugin",         "${dest}/src/${APPNAMELC}.plugin" );

print "Finished\n";
