#ifndef KDEVELOP_DEBUG_LOG_H
#define KDEVELOP_DEBUG_LOG_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(DEBUGGERCOMMON)
Q_DECLARE_LOGGING_CATEGORY(DEBUGGERGDB)
Q_DECLARE_LOGGING_CATEGORY(DEBUGGERLLDB)

#endif
