#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();

print "Installing project file\n";
install( "${src}/template-cppcurseshello/app.kdevelop",     "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-cppcurseshello/cpp-Makefile.am",  "${dest}/Makefile.am" );
install( "${src}/template-cppcurseshello/cpp-Makefile.cvs", "${dest}/Makefile.cvs" );
install( "${src}/template-cppcurseshello/app-configure.in", "${dest}/configure.in" );


print "Installing application sources\n";
install( "${src}/template-cppcurseshello/src-Makefile.am",  "${dest}/src/Makefile.am" );
install( "${src}/template-cppcurseshello/main.cpp",         "${dest}/src/${APPNAMELC}.cpp" );

print "Finished\n";
