#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();

print "Installing project file\n";
install( "${src}/template-opienet/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/apps", 0777 );
mkdir( "${dest}/pics", 0777 );
mkdir( "${dest}/pics/${APPNAMELC}", 0777 );
mkdir( "${dest}/sounds", 0777 );
mkdir( "${dest}/sounds/${APPNAMELC}", 0777 );
mkdir( "${dest}/i18n", 0777 );

print "Installing application sources\n";
install( "${src}/template-opienet/Example.png", "${dest}/pics/${APPNAMELC}/${APPNAMELC}.png" );
install( "${src}/template-opienet/app.pro", "${dest}/${APPNAMELC}.pro" );
install( "${src}/template-opienet/simplemodule.cpp", "${dest}/${APPNAMELC}module.cpp" );
install( "${src}/template-opienet/simpleiface.cpp", "${dest}/${APPNAMELC}iface.cpp" );
install( "${src}/template-opienet/simplemodule.h", "${dest}/${APPNAMELC}module.h" );
install( "${src}/template-opienet/simpleiface.h", "${dest}/${APPNAMELC}iface.h" );

print "Finished\n";
