[General]
Name=Dockerfile
Comment=A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image
Category=Docker/Dockerfile
Language=JSON
Files=Implementation
OptionsFile=options.kcfg

[Implementation]
Name=Implementation
File=Dockerfile
OutputFile=Dockerfile

