#!/usr/bin/perl

use kdevelop;

initKDevelop();

print "Installing project file\n";
install( "${src}/template-sqlsimple/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-sqlsimple/app.sql",       "${dest}/${APPNAMELC}.sql" );

print "Finished\n";
