[Desktop Entry]
Icon=preferences-desktop-theme
Type=Service
ServiceTypes=KCModule

X-KDE-ModuleType=Library
X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kcm/kcm_kdev_uisettings
X-KDE-FactoryName=kcm_kdev_uisettings
X-KDE-ParentApp=kdevplatform
X-KDE-ParentComponents=kdevplatform
X-KDE-CfgDlgHierarchy=USERINTERFACE
X-KDE-Weight=2

Name=User Interface
Name[bg]=Потребителски интерфейс
Name[bs]=Korisnički interfejs
Name[ca]=Interfície d'usuari
Name[ca@valencia]=Interfície d'usuari
Name[cs]=Uživatelské rozhraní
Name[da]=Brugerflade
Name[de]=Benutzeroberfläche
Name[el]=Περιβάλλον χρήστη
Name[en_GB]=User Interface
Name[es]=Interfaz de usuario
Name[et]=Kasutajaliides
Name[fi]=Käyttöliittymä
Name[fr]=Interface utilisateur
Name[gl]=Interface de usuario
Name[hu]=Felhasználói felület
Name[it]=Interfaccia utente
Name[ja]=ユーザインターフェース
Name[kk]=Пайдаланушы интерфейсі
Name[lv]=Lietotāja saskarne
Name[mr]=वापरकर्ता संवाद
Name[nb]=Brukerflate
Name[nds]=Böversiet
Name[nl]=Gebruikersinterface
Name[pa]=ਯੂਜ਼ਰ ਇੰਟਰਫੇਸ
Name[pl]=Interfejs użytkownika
Name[pt]=Interface do Utilizador
Name[pt_BR]=Interface do usuário
Name[ro]=Interfață utilizator
Name[ru]=Пользовательский интерфейс
Name[sk]=Užívateľské rozhranie
Name[sl]=Uporabniški vmesnik
Name[sv]=Användargränssnitt
Name[tr]=Kullanıcı Arayüzü
Name[ug]=كۆرۈنمەيۈز
Name[uk]=Інтерфейс користувача
Name[x-test]=xxUser Interfacexx
Name[zh_CN]=用户界面
Name[zh_TW]=使用者介面
Comment=Configure User Interface
Comment[bg]=Настройка на потребителски интерфейс
Comment[bs]=Konfiguriši korisničko sučelje
Comment[ca]=Configura la interfície d'usuari
Comment[ca@valencia]=Configura la interfície d'usuari
Comment[da]=Indstil brugerflade
Comment[de]=Benutzeroberfläche einrichten
Comment[el]=Διαμόρφωση περιβάλλοντος χρήστη
Comment[en_GB]=Configure User Interface
Comment[es]=Configurar la interfaz de usuario
Comment[et]=Kasutajaliidese seadistamine
Comment[fi]=Käyttöliittymän asetukset
Comment[fr]=Configurer l'interface utilisateur
Comment[gl]=Configurar a interface de usuario
Comment[hu]=Felhasználói felület beállítása
Comment[it]=Configura l'intefaccia utente
Comment[ja]=ユーザインターフェースを設定します
Comment[kk]=Пайдаланушы интерфейсін баптау
Comment[nb]=Sett opp brukerflate
Comment[nds]=Böversiet instellen
Comment[nl]=Gebruikersinterface instellen
Comment[pl]=Ustawienia interfejsu użytkownika
Comment[pt]=Configurar a Interface do Utilizador
Comment[pt_BR]=Configurar a interface do usuário
Comment[ru]=Настройка пользовательского интерфейса
Comment[sk]=Nastaviť užívateľské rozhranie
Comment[sl]=Nastavite uporabniški vmesnik
Comment[sv]=Anpassa användargränssnitt
Comment[tr]=Kullanıcı Arayüzünü Yapılandır
Comment[ug]=كۆرۈنمەيۈزنى سەپلەش
Comment[uk]=Налаштування інтерфейсу користувача
Comment[x-test]=xxConfigure User Interfacexx
Comment[zh_CN]=配置用户界面
Comment[zh_TW]=設定使用者介面

