[Desktop Entry]
Icon=project-open
Type=Service
ServiceTypes=KCModule

X-KDE-ModuleType=Library
X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kcm/kcm_kdev_projectsettings
X-KDE-FactoryName=kcm_kdev_projectsettings
X-KDE-ParentApp=kdevplatform
X-KDE-ParentComponents=kdevplatform
X-KDE-CfgDlgHierarchy=GENERAL
X-KDE-Weight=3

Name=Projects
Name[bg]=Проекти
Name[bs]=Projekti
Name[ca]=Projectes
Name[ca@valencia]=Projectes
Name[cs]=Projekty
Name[da]=Projekter
Name[de]=Projekte
Name[el]=Έργα
Name[en_GB]=Projects
Name[es]=Proyectos
Name[et]=Projektid
Name[fi]=Projektit
Name[fr]=Projets
Name[ga]=Tionscadail
Name[gl]=Proxectos
Name[hu]=Projektek
Name[it]=Progetti
Name[ja]=プロジェクト
Name[kk]=Жобалар
Name[mr]=परियोजना
Name[nb]=Prosjekter
Name[nds]=Projekten
Name[nl]=Projecten
Name[pl]=Projekty
Name[pt]=Projectos
Name[pt_BR]=Projetos
Name[ru]=Проекты
Name[sk]=Projekty
Name[sl]=Projekti
Name[sv]=Projekt
Name[tr]=Projeler
Name[ug]=قۇرۇلۇشلار
Name[uk]=Проекти
Name[x-test]=xxProjectsxx
Name[zh_CN]=工程
Name[zh_TW]=專案
Comment=Configure Projects
Comment[bg]=Настройки на проекти
Comment[bs]=Konfiguriši projekte
Comment[ca]=Configura els projectes
Comment[ca@valencia]=Configura els projectes
Comment[cs]=Nastavit projekty
Comment[da]=Indstil projekter
Comment[de]=Projekte einrichten
Comment[el]=Διαμόρφωση έργων
Comment[en_GB]=Configure Projects
Comment[es]=Configurar proyectos
Comment[et]=Projektide seadistamine
Comment[fi]=Projektien asetukset
Comment[fr]=Configurer les projets
Comment[ga]=Cumraigh Tionscadail
Comment[gl]=Configurar os proxectos
Comment[hu]=Projektek beállítása
Comment[it]=Configura i progetti
Comment[ja]=プロジェクトを設定します
Comment[kk]=Жобаларын баптау
Comment[nb]=Sett opp prosjekter
Comment[nds]=Projekten instellen
Comment[nl]=Projecten instellen
Comment[pl]=Ustawienia projektów
Comment[pt]=Configurar os Projectos
Comment[pt_BR]=Configurar projetos
Comment[ru]=Параметры работы с проектами
Comment[sk]=Nastaviť projekty
Comment[sl]=Nastavite projekte
Comment[sv]=Anpassa projekt
Comment[tr]=Projeleri Yapılandır
Comment[ug]=قۇرۇلۇشلارنى سەپلەش
Comment[uk]=Налаштування проектів
Comment[x-test]=xxConfigure Projectsxx
Comment[zh_CN]=配置工程
Comment[zh_TW]=設定專案

