#!/usr/bin/perl

use gideon;

initGideon();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
installHTML( "${src}/template-kdedcop/app.kdevelop",          "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-common/kde-app.desktop",     "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-common/kde-app.lsm",         "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/hi16-app-app.png",    "${dest}/src/hi16-app-${APPNAMELC}.png");
install( "${src}/template-common/hi32-app-app.png",    "${dest}/src/hi32-app-${APPNAMELC}.png");
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-kdedcop/subdirs",               "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kdedcop/src-Makefile.am",       "${dest}/src/Makefile.am" );
install( "${src}/template-kdedcop/app.cpp",               "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-kdedcop/app.h",                 "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-kdedcop/mainclass.cpp",           "${dest}/src/mainclass.cpp" );
install( "${src}/template-kdedcop/mainclass.h",             "${dest}/src/mainclass.h" );
install( "${src}/template-kdedcop/app_iface.h",            "${dest}/src/${APPNAMELC}_iface.h" );
install( "${src}/template-kdedcop/main.cpp",              "${dest}/src/main.cpp" );

print "Finished\n";
