/* This file is part of KDevelop
Copyright (C) 2006 Adam Treat <treat@kde.org>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Library General Public License for more details.

You should have received a copy of the GNU Library General Public License
along with this library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301, USA.
*/

#include "kdevcmodule.h"

#include <kdebug.h>
#include <kglobal.h>
#include <kurl.h>

KDevCModule::KDevCModule( KDevConfigSkeleton *config,
                          KInstance *instance,
                          QWidget *parent,
                          const QStringList &args )
        : KCModule( instance, parent, args ), m_config( config )
{
    //TODO Move this to the projectmanager where it belongs instead of hardcoded
//     KGlobal::config() ->addFileToMergeStack( "/home/kde/trunk/KDE/kdevelop/local.kdevelop4" );
//     KGlobal::config() ->addFileToMergeStack( "/home/kde/trunk/KDE/kdevelop/global.kdevelop4" );


    /*HOWTO SAVE TO THE LOCAL PROJECT FILE*/
    /*
    First we use kconfigxt... to override the virtual writeConfig method in a KDevConfigSkeleton class which the clas generated by kconfig_compiler inherits from and we reimplement the method completely.  We cycle through the list of items provided by the KConfigSkeleton API and provide our own KConfig object initialized to the local project file for all items parsed from a local.kdev4 file installed by each plugin.
    */
}

KDevCModule::~KDevCModule()
{}

void KDevCModule::save()
{
    //Calls the KDevConfigSkeleton file with the return value of the pure
    //virtual function localNonShareableFile() which must be implemented
    //by every kcm that inherits this class.
    Q_ASSERT( m_config );
    m_config->parseNonShareableFile( localNonShareableFile() );

    KCModule::save();
}

void KDevCModule::load()
{
    KCModule::load();
}

#include "kdevcmodule.moc"

// kate: space-indent on; indent-width 4; tab-width 4; replace-tabs on
