# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision$ 
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /home/bernd/kde2
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gideon
pkglibdir = $(libdir)/gideon
pkgincludedir = $(includedir)/gideon

top_builddir = ../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux
target_triplet = i686-pc-linux-gnu
ARTSCCONFIG = /home/bernd/kde2/bin/artsc-config
AS = @AS@
AUTODIRS = 
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = g++ -E
DCOPIDL = /home/bernd/kde2/bin/dcopidl
DCOPIDL2CPP = /home/bernd/kde2/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
GUILE = @GUILE@
GUILE_CFLAGS = @GUILE_CFLAGS@
GUILE_LDFLAGS = @GUILE_LDFLAGS@
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
KDB2HTML = /home/bernd/kde2/bin/kdb2html
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/home/bernd/kde2/include
KDE_LDFLAGS = -L/home/bernd/kde2/lib
KDE_PLUGIN = -avoid-version -module -no-undefined
KDE_RPATH = -R $(kde_libraries) -R $(qt_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = -lpython1.6 -lm -ldl 
LIBQIMGIO = @LIBQIMGIO@
LIBSM = -lSM -lICE
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lkformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lksycoca
LIB_KWRITE = -lkwrite
LIB_QT = -lqt $(LIBPNG) $(LIBJPEG) -lXext $(LIB_X11) $(LIBSM)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = /home/bernd/kde2/bin/mcopidl
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /home/bernd/kdesrc/qt-copy/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CXXFLAGS =  -fno-exceptions -fno-check-new -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long -fno-builtin
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = gideon
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = -I/usr/local/python1.6/include/python1.6
PYTHONLIB = -L/usr/local/python1.6/lib/python1.6/config
QT_INCLUDES = -I/home/bernd/kdesrc/qt-copy/include
QT_LDFLAGS = -L/home/bernd/kdesrc/qt-copy/lib
RANLIB = ranlib
REPO = -frepo
STRIP = strip
TOPSUBDIRS =  doc lib parts pics plugins po src
UIC = /home/bernd/kdesrc/qt-copy/bin/uic
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = -frtti
USE_THREADS = @USE_THREADS@
VERSION = 0.1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/home/bernd/kde2/include -I/home/bernd/kdesrc/qt-copy/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/home/bernd/kdesrc/qt-copy/lib -L/home/bernd/kde2/lib 
idldir = @idldir@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /home/bernd/kde2/include
kde_libraries = /home/bernd/kde2/lib
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
micodir = @micodir@
qt_includes = /home/bernd/kdesrc/qt-copy/include
qt_libraries = /home/bernd/kdesrc/qt-copy/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

INCLUDES = $(all_includes)

noinst_LTLIBRARIES = libkdevinterfaces.la

#>- libkdevinterfaces_la_SOURCES = kdevfactory.cpp kdevpart.cpp kdevcore.cpp kdevproject.cpp 			       kdevlanguagesupport.cpp kdevversioncontrol.cpp 			       kdevmakefrontend.cpp kdevappfrontend.cpp kdevcompileroptions.cpp 			       KDevMakeFrontendIface.skel KDevMakeFrontendIface.cpp 			       KDevAppFrontendIface.skel KDevAppFrontendIface.cpp
#>+ 1
libkdevinterfaces_la_SOURCES=kdevfactory.cpp kdevpart.cpp kdevcore.cpp kdevproject.cpp 			       kdevlanguagesupport.cpp kdevversioncontrol.cpp 			       kdevmakefrontend.cpp kdevappfrontend.cpp kdevcompileroptions.cpp 			        KDevMakeFrontendIface.cpp 			        KDevAppFrontendIface.cpp KDevMakeFrontendIface_skel.cpp KDevAppFrontendIface_skel.cpp


kdevelopincludedir = $(includedir)/kdevelop
kdevelopinclude_HEADERS = kdevfactory.h kdevpart.h kdevcore.h kdevproject.h 			  kdevlanguagesupport.h kdevversioncontrol.h 			  kdevmakefrontend.h kdevappfrontend.h kdevcompileroptions.h


#			  KDevMakeFrontendIface.h KDevAppFrontendIface.h

noinst_HEADERS = kdevapi.h

servicetypedir = $(kde_servicetypesdir)
servicetype_DATA = kdeveloppart.desktop kdevelopcompileroptions.desktop 		   kdevelopmakefrontend.desktop kdevelopappfrontend.desktop 		   kdevelopproject.desktop kdeveloplanguagesupport.desktop


#>- METASOURCES = AUTO
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(noinst_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LDFLAGS = 
LIBS = 
libkdevinterfaces_la_LDFLAGS = 
libkdevinterfaces_la_LIBADD = 
#>- libkdevinterfaces_la_OBJECTS =  kdevfactory.lo kdevpart.lo kdevcore.lo \
#>- kdevproject.lo kdevlanguagesupport.lo kdevversioncontrol.lo \
#>- kdevmakefrontend.lo kdevappfrontend.lo kdevcompileroptions.lo \
#>- KDevMakeFrontendIface.lo KDevAppFrontendIface.lo
#>+ 9
libkdevinterfaces_la_final_OBJECTS = libkdevinterfaces_la.all_cpp.lo 
libkdevinterfaces_la_nofinal_OBJECTS = kdevfactory.lo kdevpart.lo kdevcore.lo \
kdevproject.lo kdevlanguagesupport.lo kdevversioncontrol.lo \
kdevmakefrontend.lo kdevappfrontend.lo kdevcompileroptions.lo \
KDevMakeFrontendIface.lo KDevAppFrontendIface.lo KDevMakeFrontendIface_skel.lo KDevAppFrontendIface_skel.lo\
kdevfactory.moc.lo  \
libkdevinterfaces_la_meta_unload.lo 
libkdevinterfaces_la_OBJECTS = $(libkdevinterfaces_la_nofinal_OBJECTS)
#libkdevinterfaces_la_OBJECTS = $(libkdevinterfaces_la_final_OBJECTS)
CXXFLAGS = -O2 -fno-exceptions -fno-check-new -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long -fno-builtin
#>- CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
#>+ 1
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) $(LDFLAGS) -o $@
DATA =  $(servicetype_DATA)

HEADERS =  $(kdevelopinclude_HEADERS) $(noinst_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=kdevelopappwizard.desktop kdevelopproject.desktop kdevelopcompileroptions.desktop KDevMakeFrontendIface.kidl libkdevinterfaces_la_meta_unload.cpp kdeveloppart.desktop KDevAppFrontendIface.kidl KDevMakeFrontendIface.h KDevAppFrontendIface.h kdeveloplanguagesupport.desktop kdevelopmakefrontend.desktop kdevelopversioncontrol.desktop kdevelopappfrontend.desktop 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = tar
GZIP_ENV = --best
#>- DEP_FILES =  .deps/KDevAppFrontendIface.P .deps/KDevMakeFrontendIface.P \
#>- .deps/kdevappfrontend.P .deps/kdevcompileroptions.P .deps/kdevcore.P \
#>- .deps/kdevfactory.P .deps/kdevlanguagesupport.P \
#>- .deps/kdevmakefrontend.P .deps/kdevpart.P .deps/kdevproject.P \
#>- .deps/kdevversioncontrol.P
#>+ 12
#DEP_FILES =  $(DEPDIR)/KDevMakeFrontendIface_skel.P $(DEPDIR)/KDevAppFrontendIface_skel.P $(DEPDIR)/kdevfactory.moc.P $(DEPDIR)/libkdevinterfaces_la_meta_unload.P  $(DEPDIR)/libkdevinterfaces_la.all_cpp.P \
	  .deps/KDevAppFrontendIface.P .deps/KDevMakeFrontendIface.P \
.deps/kdevappfrontend.P .deps/kdevcompileroptions.P .deps/kdevcore.P \
.deps/kdevfactory.P .deps/kdevlanguagesupport.P \
.deps/kdevmakefrontend.P .deps/kdevpart.P .deps/kdevproject.P \
.deps/kdevversioncontrol.P
DEP_FILES =  $(DEPDIR)/KDevMakeFrontendIface_skel.P $(DEPDIR)/KDevAppFrontendIface_skel.P $(DEPDIR)/kdevfactory.moc.P $(DEPDIR)/libkdevinterfaces_la_meta_unload.P   .deps/KDevAppFrontendIface.P .deps/KDevMakeFrontendIface.P \
.deps/kdevappfrontend.P .deps/kdevcompileroptions.P .deps/kdevcore.P \
.deps/kdevfactory.P .deps/kdevlanguagesupport.P \
.deps/kdevmakefrontend.P .deps/kdevpart.P .deps/kdevproject.P \
.deps/kdevversioncontrol.P

SOURCES = $(libkdevinterfaces_la_SOURCES)
OBJECTS = $(libkdevinterfaces_la_OBJECTS)

#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu lib/interfaces/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu lib/interfaces/Makefile
	cd $(top_srcdir) && perl admin/am_edit lib/interfaces/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLTLIBRARIES:

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)

distclean-noinstLTLIBRARIES:

maintainer-clean-noinstLTLIBRARIES:

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libkdevinterfaces.la: $(libkdevinterfaces_la_OBJECTS) $(libkdevinterfaces_la_DEPENDENCIES)
	$(CXXLINK)  $(libkdevinterfaces_la_LDFLAGS) $(libkdevinterfaces_la_OBJECTS) $(libkdevinterfaces_la_LIBADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

install-servicetypeDATA: $(servicetype_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(servicetypedir)
	@list='$(servicetype_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(servicetypedir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(servicetypedir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(servicetypedir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(servicetypedir)/$$p; \
	  fi; fi; \
	done

uninstall-servicetypeDATA:
	@$(NORMAL_UNINSTALL)
	list='$(servicetype_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(servicetypedir)/$$p; \
	done

install-kdevelopincludeHEADERS: $(kdevelopinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(kdevelopincludedir)
	@list='$(kdevelopinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(kdevelopincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(kdevelopincludedir)/$$p; \
	done

uninstall-kdevelopincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(kdevelopinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(kdevelopincludedir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = lib/interfaces

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu lib/interfaces/Makefile
#>- 	@for file in $(DISTFILES); do \
#>- 	  d=$(srcdir); \
#>- 	  if test -d $$d/$$file; then \
#>- 	    cp -pr $$/$$file $(distdir)/$$file; \
#>- 	  else \
#>- 	    test -f $(distdir)/$$file \
#>- 	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
#>- 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
#>- 	  fi; \
#>- 	done
#>+ 10
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp

%.o: %.cpp
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.cpp
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-servicetypeDATA install-kdevelopincludeHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-servicetypeDATA uninstall-kdevelopincludeHEADERS
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(DATA) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(servicetypedir) \
		$(DESTDIR)$(kdevelopincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-noinstLTLIBRARIES clean-compile clean-libtool \
#>- 		clean-tags clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-idl clean-moc-classes clean-final   clean-noinstLTLIBRARIES clean-compile clean-libtool \
		clean-tags clean-depend clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-noinstLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-depend \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLTLIBRARIES distclean-noinstLTLIBRARIES \
clean-noinstLTLIBRARIES maintainer-clean-noinstLTLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool uninstall-servicetypeDATA \
install-servicetypeDATA uninstall-kdevelopincludeHEADERS \
install-kdevelopincludeHEADERS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir mostlyclean-depend \
distclean-depend clean-depend maintainer-clean-depend info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 9
KDevMakeFrontendIface.kidl: $(srcdir)/KDevMakeFrontendIface.h $(DCOPIDL_DEPENDENCIES)
	$(DCOPIDL) $(srcdir)/KDevMakeFrontendIface.h > KDevMakeFrontendIface.kidl || ( rm -f KDevMakeFrontendIface.kidl ; /bin/false )
KDevMakeFrontendIface_skel.cpp: KDevMakeFrontendIface.kidl
	$(DCOPIDL2CPP) --c++-suffix cpp --no-stub KDevMakeFrontendIface.kidl
KDevAppFrontendIface.kidl: $(srcdir)/KDevAppFrontendIface.h $(DCOPIDL_DEPENDENCIES)
	$(DCOPIDL) $(srcdir)/KDevAppFrontendIface.h > KDevAppFrontendIface.kidl || ( rm -f KDevAppFrontendIface.kidl ; /bin/false )
KDevAppFrontendIface_skel.cpp: KDevAppFrontendIface.kidl
	$(DCOPIDL2CPP) --c++-suffix cpp --no-stub KDevAppFrontendIface.kidl

#>+ 3
kdevappfrontend.moc: $(srcdir)/kdevappfrontend.h
	$(MOC) $(srcdir)/kdevappfrontend.h -o kdevappfrontend.moc

#>+ 3
kdevmakefrontend.moc: $(srcdir)/kdevmakefrontend.h
	$(MOC) $(srcdir)/kdevmakefrontend.h -o kdevmakefrontend.moc

#>+ 3
kdevversioncontrol.moc: $(srcdir)/kdevversioncontrol.h
	$(MOC) $(srcdir)/kdevversioncontrol.h -o kdevversioncontrol.moc

#>+ 3
kdevpart.moc: $(srcdir)/kdevpart.h
	$(MOC) $(srcdir)/kdevpart.h -o kdevpart.moc

#>+ 3
kdevlanguagesupport.moc: $(srcdir)/kdevlanguagesupport.h
	$(MOC) $(srcdir)/kdevlanguagesupport.h -o kdevlanguagesupport.moc

#>+ 3
kdevcompileroptions.moc: $(srcdir)/kdevcompileroptions.h
	$(MOC) $(srcdir)/kdevcompileroptions.h -o kdevcompileroptions.moc

#>+ 3
kdevproject.moc: $(srcdir)/kdevproject.h
	$(MOC) $(srcdir)/kdevproject.h -o kdevproject.moc

#>+ 3
kdevcore.moc: $(srcdir)/kdevcore.h
	$(MOC) $(srcdir)/kdevcore.h -o kdevcore.moc

#>+ 3
kdevfactory.moc.cpp: $(srcdir)/kdevfactory.h
	$(MOC) $(srcdir)/kdevfactory.h -o kdevfactory.moc.cpp

#>+ 3
clean-metasources:
	-rm -f  kdevappfrontend.moc kdevmakefrontend.moc kdevversioncontrol.moc kdevpart.moc kdevlanguagesupport.moc kdevcompileroptions.moc kdevproject.moc kdevcore.moc kdevfactory.moc.cpp

#>+ 5
clean-idl:
	-rm -f \
	KDevMakeFrontendIface_skel.cpp KDevMakeFrontendIface_skel.h KDevMakeFrontendIface.kidl \
	KDevAppFrontendIface_skel.cpp KDevAppFrontendIface_skel.h KDevAppFrontendIface.kidl 

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu lib/interfaces/Makefile
	cd $(top_srcdir) && perl admin/am_edit lib/interfaces/Makefile.in


#>+ 10
libkdevinterfaces_la_meta_unload.cpp:  kdevappfrontend.moc kdevlanguagesupport.moc kdevproject.moc kdevcompileroptions.moc kdevfactory.moc.cpp kdevcore.moc kdevmakefrontend.moc kdevversioncontrol.moc kdevpart.moc
	@echo 'creating libkdevinterfaces_la_meta_unload.cpp'
	-rm -f libkdevinterfaces_la_meta_unload.cpp
	@echo 'static const char * _metalist_libkdevinterfaces_la[] = {' > libkdevinterfaces_la_meta_unload.cpp
	cat  kdevappfrontend.moc kdevlanguagesupport.moc kdevproject.moc kdevcompileroptions.moc kdevfactory.moc.cpp kdevcore.moc kdevmakefrontend.moc kdevversioncontrol.moc kdevpart.moc | grep 'char.*className' | sed -e 's/.*[^A-Za-z0-9_:]\([A-Za-z0-9_:]*\)::className.*$$/\"\1\",/' | sort | uniq >> libkdevinterfaces_la_meta_unload.cpp
	@echo '0};' >> libkdevinterfaces_la_meta_unload.cpp
	@echo '#include <kunload.h>' >> libkdevinterfaces_la_meta_unload.cpp
	@echo '_UNLOAD(libkdevinterfaces_la)' >> libkdevinterfaces_la_meta_unload.cpp


#>+ 3
clean-moc-classes:
	-rm -f  libkdevinterfaces_la_meta_unload.cpp

#>+ 11
libkdevinterfaces_la.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/kdevfactory.cpp $(srcdir)/kdevpart.cpp $(srcdir)/kdevcore.cpp $(srcdir)/kdevproject.cpp $(srcdir)/kdevlanguagesupport.cpp $(srcdir)/kdevversioncontrol.cpp $(srcdir)/kdevmakefrontend.cpp $(srcdir)/kdevappfrontend.cpp $(srcdir)/kdevcompileroptions.cpp $(srcdir)/KDevMakeFrontendIface.cpp $(srcdir)/KDevAppFrontendIface.cpp $(srcdir)/KDevMakeFrontendIface_skel.cpp $(srcdir)/KDevAppFrontendIface_skel.cpp $(srcdir)/libkdevinterfaces_la_meta_unload.cpp  kdevfactory.moc.cpp kdevappfrontend.moc kdevmakefrontend.moc kdevversioncontrol.moc kdevpart.moc kdevlanguagesupport.moc kdevcompileroptions.moc kdevproject.moc kdevcore.moc 
	@echo 'creating libkdevinterfaces_la.all_cpp.cpp ...'; \
	rm -f libkdevinterfaces_la.all_cpp.files libkdevinterfaces_la.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> libkdevinterfaces_la.all_cpp.final; \
	for file in kdevfactory.cpp kdevpart.cpp kdevcore.cpp kdevproject.cpp kdevlanguagesupport.cpp kdevversioncontrol.cpp kdevmakefrontend.cpp kdevappfrontend.cpp kdevcompileroptions.cpp KDevMakeFrontendIface.cpp KDevAppFrontendIface.cpp KDevMakeFrontendIface_skel.cpp KDevAppFrontendIface_skel.cpp libkdevinterfaces_la_meta_unload.cpp  kdevfactory.moc.cpp; do \
	  echo "#include \"$$file\"" >> libkdevinterfaces_la.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> libkdevinterfaces_la.all_cpp.final; \
	done; \
	cat libkdevinterfaces_la.all_cpp.final libkdevinterfaces_la.all_cpp.files  > libkdevinterfaces_la.all_cpp.cpp; \
	rm -f libkdevinterfaces_la.all_cpp.final libkdevinterfaces_la.all_cpp.files

#>+ 3
clean-final:
	-rm -f libkdevinterfaces_la.all_cpp.cpp

#>+ 2
final:
	$(MAKE) libkdevinterfaces_la_OBJECTS="$(libkdevinterfaces_la_final_OBJECTS)" all-am
#>+ 2
no-final:
	$(MAKE) libkdevinterfaces_la_OBJECTS="$(libkdevinterfaces_la_nofinal_OBJECTS)" all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo

#>+ 9
$(srcdir)/kdevproject.cpp: kdevproject.moc 
$(srcdir)/kdevlanguagesupport.cpp: kdevlanguagesupport.moc 
$(srcdir)/kdevversioncontrol.cpp: kdevversioncontrol.moc 
$(srcdir)/kdevcompileroptions.cpp: kdevcompileroptions.moc 
$(srcdir)/kdevcore.cpp: kdevcore.moc 
$(srcdir)/kdevappfrontend.cpp: kdevappfrontend.moc 
$(srcdir)/kdevpart.cpp: kdevpart.moc 
$(srcdir)/kdevmakefrontend.cpp: kdevmakefrontend.moc 
