#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kxt/app.kdevelop",          "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/debug", 0777 );
mkdir( "${dest}/optimized", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-common/kde-app.desktop",     "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-common/kde-app.lsm",         "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/hi16-app-app.png",    "${dest}/src/hi16-app-${APPNAMELC}.png");
install( "${src}/template-common/hi32-app-app.png",    "${dest}/src/hi32-app-${APPNAMELC}.png");
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-kxt/subdirs",               "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kxt/src-Makefile.am",       "${dest}/src/Makefile.am" );
install( "${src}/template-kxt/app.cpp",               "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-kxt/app.h",                 "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-kxt/appview_base.ui",       "${dest}/src/${APPNAMELC}view_base.ui" );
install( "${src}/template-kxt/appview.cpp",           "${dest}/src/${APPNAMELC}view.cpp" );
install( "${src}/template-kxt/appview.h",             "${dest}/src/${APPNAMELC}view.h" );
install( "${src}/template-kxt/prefs-base.ui",         "${dest}/src/prefs-base.ui" );
install( "${src}/template-kxt/prefs.cpp",             "${dest}/src/prefs.cpp" );
install( "${src}/template-kxt/prefs.h",               "${dest}/src/prefs.h" );
install( "${src}/template-kxt/main.cpp",              "${dest}/src/main.cpp" );
install( "${src}/template-kxt/appui.rc",              "${dest}/src/${APPNAMELC}ui.rc" );
install( "${src}/template-kxt/README",                "${dest}/src/README" );
install( "${src}/template-kxt/app.kcfg",              "${dest}/src/${APPNAMELC}.kcfg" );
install( "${src}/template-kxt/settings.kcfgc",        "${dest}/src/settings.kcfgc" );

install( "${src}/template-kxt/src-configure.in.in",        "${dest}/configure.in.in" );

print "Finished\n";
