#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();


print "Installing project file\n";
installHTML( "${src}/template-kappjava/app.kdevelop",          "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-common/kde-app.desktop",     "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-common/kde-app.lsm",         "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/hi16-app-app.png",    "${dest}/src/hi16-app-${APPNAMELC}.png");
install( "${src}/template-common/hi32-app-app.png",    "${dest}/src/hi32-app-${APPNAMELC}.png");
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-kapp/subdirs",               "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kappjava/src-Makefile.am",       "${dest}/src/Makefile.am" );
install( "${src}/template-kappjava/app.java",               "${dest}/src/${APPNAME}.java" );
install( "${src}/template-kappjava/appview.java",           "${dest}/src/${APPNAME}View.java" );
install( "${src}/template-kappjava/pref.java",              "${dest}/src/${APPNAME}Preferences.java" );
install( "${src}/template-kappjava/appui.rc",              "${dest}/src/${APPNAMELC}ui.rc" );

print "Finished\n";
