#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();
installGNOME();

print "Installing project file\n";
install( "${src}/template-gnomeapp/app.kdevelop",            "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/pixmaps", 0777 );
install( "${src}/template-common/gnome-app.lsm",             "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/gnome-Makefile.am",         "${dest}/Makefile.am" );
install( "${src}/template-common/gnome-Makefile.cvs",        "${dest}/Makefile.cvs" );
install( "${src}/template-common/gnome-pixmaps-Makefile.am", "${dest}/pixmaps/Makefile.am" );
install( "${src}/template-common/gnome-app.png",             "${dest}/pixmaps/${APPNAMELC}.png" );
install( "${src}/template-gnomeapp/app.desktop",             "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-gnomeapp/configure.in",            "${dest}/configure.in" );


print "Installing application sources\n";
install( "${src}/template-gnomeapp/src-Makefile.am",         "${dest}/src/Makefile.am" );
install( "${src}/template-gnomeapp/app.c",                   "${dest}/src/${APPNAMELC}.c" );
install( "${src}/template-gnomeapp/app.h",                   "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-gnomeapp/menus.c",                 "${dest}/src/menus.c" );
install( "${src}/template-gnomeapp/menus.h",                 "${dest}/src/menus.h" );
install( "${src}/template-gnomeapp/main.c",                  "${dest}/src/main.c" );

print "Finished\n";
