#!/usr/bin/perl

use gideon;

initGideon();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-fortranhello/app.kdevelop",     "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-fortranhello/fortran-Makefile.am",  "${dest}/Makefile.am" );
install( "${src}/template-fortranhello/fortran-Makefile.cvs", "${dest}/Makefile.cvs" );
install( "${src}/template-fortranhello/configure.in",     "${dest}/configure.in" );


print "Installing application sources\n";
install( "${src}/template-fortranhello/src-Makefile.am",  "${dest}/src/Makefile.am" );
install( "${src}/template-fortranhello/main.f",         "${dest}/src/${APPNAMELC}.f" );

print "Finished\n";
