#!/usr/bin/perl -I/usr/kde/3.1/share/apps/kdevappwizard/template-common

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
#installIncAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-haskellhello/app.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );

print "Installing application sources\n";
install( "${src}/template-haskellhello/Main.hs",          "${dest}/src/${APPNAMELC}.hs" );

print "Finished\n";

