#!/bin/sh

if [ -x /usr/sbin/install-docs ]; then
        /usr/sbin/install-docs -i /usr/share/doc-base/kdevelop-tutorial
        /usr/sbin/install-docs -i /usr/share/doc-base/kdevelop-user
fi

exit 0

