#!/bin/sh

set -e
case "$1" in
    configure)
    ;;
 
    abort-upgrade|abort-remove|abort-deconfigure)
 
    ;;
 
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
 
if [ "$1" = configure ] && command -v install-docs >/dev/null 2>&1; then
  install-docs -i /usr/share/doc-base/kdevelop-kdelibref
  install-docs -i /usr/share/doc-base/kdevelop-tutorial
  install-docs -i /usr/share/doc-base/kdevelop-programming
  install-docs -i /usr/share/doc-base/kdevelop-user
fi

#DEBHELPER#
 
exit 0

