#!/usr/bin/perl

use gideon;

initGideon();

print "Installing project file\n";
installHTML( "${src}/template-phphello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-phphello/app.php",       "${dest}/${APPNAMELC}.php" );

print "Finished\n";
