#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();

print "Installing project file\n";
install( "${src}/template-javahello/javahello.kdevelop",          "${dest}/${APPNAMELC}.kdevelop" );
install( "${src}/template-javahello/javahello.filelist",          "${dest}/${APPNAMELC}.filelist" );

print "Installing application sources\n";
install( "${src}/template-javahello/Main.java",               "${dest}/Main.java" );
install( "${src}/template-javahello/build.xml",               "${dest}/build.xml" );

print "Finished\n";
