#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();

print "Installing project file\n";
install( "${src}/template-opietoday/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/apps", 0777 );
mkdir( "${dest}/pics", 0777 );
mkdir( "${dest}/pics/${APPNAMELC}", 0777 );
mkdir( "${dest}/sounds", 0777 );
mkdir( "${dest}/sounds/${APPNAMELC}", 0777 );
mkdir( "${dest}/i18n", 0777 );

print "Installing application sources\n";
install( "${src}/template-opietoday/Example.png", "${dest}/pics/${APPNAMELC}/${APPNAMELC}.png" );
install( "${src}/template-opietoday/app.pro", "${dest}/${APPNAMELC}.pro" );
install( "${src}/template-opietoday/exampleplugin.cpp", "${dest}/${APPNAMELC}.cpp" );
install( "${src}/template-opietoday/examplepluginwidget.cpp", "${dest}/${APPNAMELC}widget.cpp" );
install( "${src}/template-opietoday/examplepluginimpl.cpp", "${dest}/${APPNAMELC}impl.cpp" );
install( "${src}/template-opietoday/exampleplugin.h", "${dest}/${APPNAMELC}.h" );
install( "${src}/template-opietoday/examplepluginwidget.h", "${dest}/${APPNAMELC}widget.h" );
install( "${src}/template-opietoday/examplepluginimpl.h", "${dest}/${APPNAMELC}impl.h" );

print "Finished\n";
