#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kscreensaver/kscreensaver.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-app.lsm", "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kscreensaver/subdirs",           "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kscreensaver/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-kscreensaver/kscreensaver.cpp",         "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-kscreensaver/kscreensaver.h",           "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-kscreensaver/kscreensaver.desktop",           "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-kscreensaver/kscreensaverui.ui",    "${dest}/src/${APPNAMELC}ui.ui" );

print "Finished\n";
