[Desktop Entry]
Type=Service
Name=KDevelop Welcome Page
Name[ca]=Pàgina de benvinguda del KDevelop
Name[cs]=Uvítací stránka KDevelop
Name[de]=KDevelop-Startseite
Name[en_GB]=KDevelop Welcome Page
Name[es]=Página de bienvenida de KDevelop
Name[fi]=KDevelopin tervetulosivu
Name[hu]=KDevelop üdvözlőképernyő
Name[nl]=Welkomstpagina van KDevelop
Name[pl]=Strona powitalna KDevelop
Name[pt]=Página de Boas-Vindas do KDevelop
Name[pt_BR]=Página de boas-vindas do KDevelop
Name[sk]=Uvítacia stránka KDevelop
Name[sl]=Pozdravna stran za KDevelop
Name[sv]=KDevelop välkomstsida
Name[tr]=KDevelop Karşılama Sayfası
Name[uk]=Сторінка вітання KDevelop
Name[x-test]=xxKDevelop Welcome Pagexx
GenericName=Welcome Page
GenericName[ca]=Pàgina de benvinguda
GenericName[de]=Startseite
GenericName[en_GB]=Welcome Page
GenericName[es]=Página de bienvenida
GenericName[fi]=Tervetulosivu
GenericName[hu]=Kezdőlap
GenericName[nl]=Welkomstpagina
GenericName[pl]=Strona powitalna
GenericName[pt]=Página de Boas-Vindas
GenericName[pt_BR]=Página de boas-vindas
GenericName[sk]=Uvítacia stránka
GenericName[sl]=Pozdravna stran
GenericName[sv]=Välkomstsida
GenericName[tr]=Karşılama Sayfası
GenericName[uk]=Сторінка вітання
GenericName[x-test]=xxWelcome Pagexx
Comment=Configure which macros and include directories/files will be added to the parser during project parsing.
Comment[ca]=Configura quins directoris/fitxers de macros i include seran afegits a l'analitzador durant l'anàlisi del projecte.
Comment[de]=Einstellung der Makros und Include-Ordner/-Dateien, die zum für den Parser während des Einlesens des Projekts hinzugefügt werden.
Comment[en_GB]=Configure which macros and include directories/files will be added to the parser during project parsing.
Comment[es]=Configurar las macros y los directorios/archivos a incluir que se añadirán al analizador sintáctico durante el análisis de los proyectos.
Comment[fi]=Määritä, mitkä makrot ja include-hakemistot/tiedostot lisätään jäsentimelle projektin jäsentämisen aikana.
Comment[hu]=Beállítja, hogy mely makrók és include mappák/fájlok legyenek hozzáadva a feldolgozóhoz a projekt feldolgozása során.
Comment[nl]=Stel in welke macro's en ingevoegde mappen/bestanden toegevoegd zullen worden aan de parser bij het ontleden van het project.
Comment[pl]=Ustawia jakie makra oraz katalogi/pliki dołączane zostaną dodane do programu przetwarzającego przy przetwarzaniu projektu.
Comment[pt]=Define quais as macros e ficheiros/pastas incluídos que serão adicionados ao processador durante o processamento do projecto.
Comment[pt_BR]=Configura quais macros e arquivos/pastas incluídos serão adicionados ao processador durante o processamento do projeto.
Comment[sk]=Nastaviť, ktoré makrá a zahrnuté adresáre/súbory sa pridajú do spracovača počas spracovania projektu.
Comment[sl]=Nastavite, kateri makri in mape oz. datoteke z vključitvami bodo dodane razčlenjevalniku med razčlenjevanjem projekta.
Comment[sv]=Anpassa vilka makron och filer eller kataloger att inkludera som läggs till i tolken under projekttolkning.
Comment[tr]=Projeyi ayrıştırma sırasında eklenecek dizinler/dosyalar ve makroları yapılandır.
Comment[uk]=Налаштуйте які макроси та включені каталоги або файли буде додано для обробника під час обробки проекту.
Comment[x-test]=xxConfigure which macros and include directories/files will be added to the parser during project parsing.xx

Icon=kdevelop
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kdevwelcomepage
X-KDE-PluginInfo-Name=KDevWelcomePage
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Interfaces=
X-KDevelop-Mode=GUI

#Don't set a category, we want to explicitly invoke it
# X-KDevelop-Category=
