#!/usr/bin/perl

use kdevelop;

initKDevelop();

print "Installing project file\n";
install( "${src}/template-phphello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-phphello/app.php",       "${dest}/${APPNAMELC}.php" );

print "Finished\n";
