#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-cppsdlhello/app.kdevelop",     "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-cppsdlhello/cpp-Makefile.am",  "${dest}/Makefile.am" );
install( "${src}/template-cppsdlhello/cpp-Makefile.cvs", "${dest}/Makefile.cvs" );
install( "${src}/template-cppsdlhello/configure.in",     "${dest}/configure.in" );
install( "${src}/template-cppsdlhello/acinclude.m4",     "${dest}/acinclude.m4" );

print "Installing application sources\n";
install( "${src}/template-cppsdlhello/src-Makefile.am",  "${dest}/src/Makefile.am" );
install( "${src}/template-cppsdlhello/main.cpp",         "${dest}/src/${APPNAMELC}.cpp" );

print "Finished\n";
