#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kfileplugin/plugin.kdevelop",        "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.cvs",            "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-Makefile.am",             "${dest}/Makefile.am" );
install( "${src}/template-common/kde-configure.in.in",         "${dest}/configure.in.in" );
install( "${src}/template-common/kde-app.lsm",                 "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",          "${dest}/po/Makefile.am" );
install( "${src}/template-kfileplugin/subdirs",                "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kfileplugin/src-Makefile.am",        "${dest}/src/Makefile.am" );
install( "${src}/template-kfileplugin/kfile_plugin.desktop",   "${dest}/src/kfile_${APPNAMELC}.desktop" );
install( "${src}/template-kfileplugin/kfile_plugin.cpp",       "${dest}/src/kfile_${APPNAMELC}.cpp" );
install( "${src}/template-kfileplugin/kfile_plugin.h",         "${dest}/src/kfile_${APPNAMELC}.h" );
install( "${src}/template-kfileplugin/README.devel",           "${dest}/README.devel" );

print "Finished\n";
