/***************************************************************************
                            DocumentationContext.java -  description
                             -------------------
    begin                : Wed Dec 19 12:26:58 2001
    copyright            : (C) 2000-2001 Lost Highway Ltd.
    email                : Richard_Dale@tipitina.demon.co.uk
    generated by         : duke@tipitina on Wed Dec 19 12:26:58 2001, using kalyptus 0.91.
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
***************************************************************************/

package org.kde.koala;

import org.kde.qt.*;
import java.util.*;
import java.lang.Error;

/**

 A context for the popup menu in the html widget. In this
 case, url() returns the URL of the page currently shown,
 and selection() returns the selected text.
 
 @short 
 A context for the popup menu in the html widget.
*/
public class DocumentationContext extends Context  {
	protected DocumentationContext(Class dummy){super((Class) null);}

	private native void newDocumentationContext( String url, String selection);
	public DocumentationContext( String url, String selection) {
		super((Class) null);
		newDocumentationContext( url, selection);
	}
	protected native void finalize() throws InternalError;
	public native String url();
	public native String selection();
}
