/***************************************************************************
                            KDevCompilerOptions.java -  description
                             -------------------
    begin                : Wed Jul  4 12:40:03 2001
    copyright            : (C) 2000-2001 Lost Highway Ltd.
    email                : Richard_Dale@tipitina.demon.co.uk
    generated by         : duke@tipitina on Wed Jul  4 12:40:03 2001, using kdoc parser/custom Java conversion backend.
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
***************************************************************************/

package org.kde.koala;

import org.kde.qt.*;
import java.util.*;
import java.lang.Error;

/**

 The interface to compiler options configuration
 
 @short 
 The interface to compiler options configuration
 
*/
public class KDevCompilerOptions extends QObject  {
	protected KDevCompilerOptions(Class dummy){super((Class) null);}

	protected native void finalize() throws InternalError;

/** 
 Opens a dialog which allows the user to configure the
 compiler options. The initial settings in the dialog
 will be set from the flags argument of this method.
 After the dialog is accepted, the new settings will
 be returned as a string. If the dialog was cancelled,
 String.null is returned.
     
*/
	public native String exec( QWidget parent, String flags);
}
