/***************************************************************************
                            ParsedAttribute.java -  description
                             -------------------
    begin                : Fri May 25 13:03:19 2001
    copyright            : (C) 2000-2001 Lost Highway Ltd.
    email                : Richard_Dale@tipitina.demon.co.uk
    generated by         : duke@tipitina on Fri May 25 13:03:19 2001, using kdoc parser/custom Java conversion backend.
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
***************************************************************************/

package org.kde.koala;

import org.kde.qt.*;
import java.util.*;
import java.lang.Error;

/**

 Represents an attribute and all data for the attribute. 

 @author Jonas Nordin
 
 @short 
 Represents an attribute and all data for the attribute.
*/
public class ParsedAttribute extends ParsedItem  {
	protected ParsedAttribute(Class dummy){super((Class) null);}

	private native void newParsedAttribute();
	public ParsedAttribute() {
		super((Class) null);
		newParsedAttribute();
	}
	protected native void finalize() throws InternalError;

/**  Sets the type. 
*/
	public native void setType( String aType);
	public native String attributeType();

/**  Sets the pos of the name between type 
*/
	public native void setNamePos( int pos);
	public native int namePos();

/**  Sets if it is defined in the .h file. 
*/
	public native void setIsInHFile( boolean aState);
	public native void setIsInHFile();
	public native boolean inHFile();

/**  Sets the attribute's static status 
*/
	public native void setIsStatic( boolean aState);
	public native void setIsStatic();
	public native boolean isStaticAttribute();

/**  Sets the attribute's const status 
*/
	public native void setIsConst( boolean aState);
	public native void setIsConst();
	public native boolean isConstAttribute();

/** 
 Makes this object a copy of the supplied object.

*/
	public native void copy( ParsedAttribute anAttribute);

/**  Is the supplied attribute equal to this one(regarding type and name 
*/
	public native boolean isEqual( ParsedAttribute attr);

/**  Returns the object as a string(for tooltips etc) 
*/
	public native String asString();

/**  Outputs this object to stdout 
*/
	public native void out();
}
