[Desktop Entry]
Type=Service
Icon=reviewboard
Exec=blubb
Comment=ReviewBoard integration for KDevelop
Comment[bs]=ReviewBoard integracija za KDevelop
Comment[ca]=Integració de ReviewBoard pel KDevelop
Comment[ca@valencia]=Integració de ReviewBoard pel KDevelop
Comment[da]=Integration af ReviewBoard med KDevelop
Comment[de]=ReviewBoard-Integration für KDevelop
Comment[el]=Ενσωμάτωση ReviewBoard για το KDevelop
Comment[en_GB]=ReviewBoard integration for KDevelop
Comment[es]=Integración de ReviewBoard en KDevelop
Comment[et]=ReviewBoardi lõimimine KDevelopiga
Comment[fi]=ReviewBoard-integrointi KDevelop-ympäristöön
Comment[fr]=Intégration de ReviewBoard pour KDevelop
Comment[gl]=Integración do ReviewBoard para KDevelop
Comment[hu]=ReviewBoard integráció a KDevelophoz
Comment[it]=Integrazione ReviewBoard per KDevelop
Comment[kk]=ReviewBoard-ты KDevelop-пен біріктіру
Comment[nb]=ReviewBoard-integrering for KDevelop
Comment[nds]=ReviewBoard-Inbinnen för KDevelop
Comment[nl]=ReviewBoard-integratie voor KDevelop
Comment[pl]=Integracja tablic przeglądu dla KDevelop
Comment[pt]=Integração do ReviewBoard para o KDevelop
Comment[pt_BR]=Integração do ReviewBoard para o KDevelop
Comment[ru]=Интеграция ReviewBoard в KDevelop
Comment[sk]=Integrácia ReviewBoard pre KDevelop
Comment[sl]=Vgradnja orodja ReviewBoard v KDevelop
Comment[sv]=Integrering av Reviewboard i KDevelop
Comment[tr]=KDevelop için Gözden Geçirme Tahtası bütünleşmesi
Comment[uk]=Інтеграція ReviewBoard з KDevelop
Comment[x-test]=xxReviewBoard integration for KDevelopxx
Comment[zh_CN]=KDevelop 的 ReviewBoard 集成
Comment[zh_TW]=ReviewBoard 與 KDevelop 整合
Name=ReviewBoard
Name[bs]=ReviewBoard
Name[ca]=ReviewBoard
Name[ca@valencia]=ReviewBoard
Name[da]=ReviewBoard
Name[de]=ReviewBoard
Name[el]=ReviewBoard
Name[en_GB]=ReviewBoard
Name[es]=ReviewBoard
Name[et]=ReviewBoard
Name[fi]=ReviewBoard
Name[fr]=ReviewBoard
Name[gl]=ReviewBoard
Name[hu]=ReviewBoard
Name[it]=ReviewBoard
Name[kk]=ReviewBoard
Name[nb]=ReviewBoard
Name[nds]=ReviewBoard
Name[nl]=ReviewBoard
Name[pl]=Tablica przeglądowa
Name[pt]=ReviewBoard
Name[pt_BR]=ReviewBoard
Name[ru]=ReviewBoard
Name[sk]=ReviewBoard
Name[sl]=ReviewBoard
Name[sv]=Reviewboard
Name[tr]=Gözden Geçirme Tahtası
Name[ug]=ReviewBoard
Name[uk]=ReviewBoard
Name[x-test]=xxReviewBoardxx
Name[zh_CN]=ReviewBoard
Name[zh_TW]=ReviewBoard
GenericName=ReviewBoard
GenericName[bs]=ReviewBoard
GenericName[ca]=ReviewBoard
GenericName[ca@valencia]=ReviewBoard
GenericName[da]=ReviewBoard
GenericName[de]=ReviewBoard
GenericName[el]=ReviewBoard
GenericName[en_GB]=ReviewBoard
GenericName[es]=ReviewBoard
GenericName[et]=ReviewBoard
GenericName[fi]=ReviewBoard
GenericName[fr]=ReviewBoard
GenericName[gl]=ReviewBoard
GenericName[hu]=ReviewBoard
GenericName[it]=ReviewBoard
GenericName[kk]=ReviewBoard
GenericName[nb]=ReviewBoard
GenericName[nds]=ReviewBoard
GenericName[nl]=ReviewBoard
GenericName[pl]=Tablica przeglądowa
GenericName[pt]=ReviewBoard
GenericName[pt_BR]=ReviewBoard
GenericName[ru]=ReviewBoard
GenericName[sk]=ReviewBoard
GenericName[sl]=ReviewBoard
GenericName[sv]=Reviewboard
GenericName[tr]=Gözden Geçirme Tahtası
GenericName[ug]=ReviewBoard
GenericName[uk]=ReviewBoard
GenericName[x-test]=xxReviewBoardxx
GenericName[zh_CN]=ReviewBoard
GenericName[zh_TW]=ReviewBoard
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kdevreviewboard
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDE-PluginInfo-Name=kdevreviewboard
X-KDE-PluginInfo-Author=Aleix Pol
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-Category=Utilities
X-KDevelop-Mode=GUI
X-KDevelop-Interfaces=org.kdevelop.IPatchExporter
