#!/usr/bin/perl

use gideon;

initGideon();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-konqnavpanel/konqnavpanel.kdevelop",     "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-app.desktop",     "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-common/kde-app.lsm",         "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kicker/subdirs",             "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-konqnavpanel/src-Makefile.am",     "${dest}/src/Makefile.am" );
install( "${src}/template-konqnavpanel/konqnavpanel.cpp",          "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-konqnavpanel/konqnavpanel.h",            "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-konqnavpanel/konqnavpanel.desktop",      "${dest}/src/${APPNAMELC}.desktop" );

print "Finished\n";
