#!perl -I/opt/kde3/share/apps/kdevappwizard/template-common

use gideon;

initGideon();
installLicense();
installAdmin();
installGNU();

print "Installing project file\n";
install( "${src}/template-kbearimportfilter/plugin.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-kbearimportfilter/subdirs",  "${dest}/subdirs");

print "Installing application sources\n";
install( "${src}/template-kbearimportfilter/kbearimportfilter-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kbearimportfilter/src-Makefile.am",           "${dest}/src/Makefile.am" );
install( "${src}/template-kbearimportfilter/plugin.cpp",                "${dest}/src/${APPNAMELC}importfilterplugin.cpp" );
install( "${src}/template-kbearimportfilter/plugin.h",                  "${dest}/src/${APPNAMELC}importfilterplugin.h" );
install( "${src}/template-kbearimportfilter/kbearimportfilter.desktop", "${dest}/src/kbear${APPNAMELC}importfilter.desktop" );

print "Finished\n";
