[Desktop Entry]
Type=Service
Icon=edit-paste
Exec=blubb
Comment=This plugin helps you upload your patches to Pastebin service
Comment[bs]=Ovaj dodatak vam pomaže da pošaljete svoje zakrpe na pastebin servis
Comment[ca]=Aquest connector ajuda a exportar pedaços al servei Pastebin
Comment[ca@valencia]=Este connector ajuda a exportar pedaços al servei Pastebin
Comment[da]=Dette plugin hjælper dig med at uploade dine rettelser til en pastebin-tjeneste
Comment[de]=Dieses Modul hilft Ihnen, Ihre Patches zu einen Pastebin-Dienst hochzuladen.
Comment[el]=Αυτό το πρόσθετο σάς βοηθάει να φορτώνετε διορθώσεις στην υπηρεσία Pastebin
Comment[en_GB]=This plugin helps you upload your patches to Pastebin service
Comment[es]=Este complemento le ayuda a enviar sus parches al servicio Pastebin
Comment[et]=See plugin aitab üles laadida paiku Pastebini teenusesse
Comment[fi]=Tämä liitännäinen opastaa sinua kopioidessasi korjauksiasi Pastebin-palveluun
Comment[fr]=Ce module externe vous aide à envoyer vos correctifs au service Pastebin
Comment[gl]=Este engadido facilítalle enviar os seus parches ao servizo Pastebin
Comment[hu]=Ez a bővítmény segít önnek feltölteni a javítócsomagokat a Pastebin szolgáltatásba
Comment[it]=Questa estensione consente di caricare le tue patch su Pastebin
Comment[kk]=Pastebin қызметіне жамауларыңызды жүктеп беруге көмек ететін плагині
Comment[nb]=Med dette programtillegget kan du laste opp lappene dine til Pastebin-tjenesten
Comment[nds]=Mit dit Moduul laat sik Kodeplasters na den Pastebin-Deenst hoochladen.
Comment[nl]=Deze plugin helpt u om uw patches naar de Pastebin-service te uploaden
Comment[pl]=Wtyczka ta pomaga ci wysyłać swoje łatki do usługi Pastebin
Comment[pt]=Este 'plugin' ajuda-o a enviar as suas modificações para o serviço Pastebin
Comment[pt_BR]=Este plugin o auxilia a enviar suas modificações para o serviço Pastebin
Comment[ru]=Это расширение помогает загружать фрагменты кода на сайт Pastebin
Comment[sk]=Tento plugin vám pomôže nahrať vaše záplaty na službu Pastebin
Comment[sl]=Vstavek vam pomaga pri pošiljanju popravkov na storitev Pastebin
Comment[sv]=Det här insticksprogrammet hjälper till att ladda upp programfixar till tjänsten Pastebin
Comment[tr]=Bu eklenti yamalarınızı Pastebin servisine göndermenizi sağlar
Comment[uk]=За допомогою цього додатка ви зможете вивантажувати ваші латки до служби Pastebin
Comment[x-test]=xxThis plugin helps you upload your patches to Pastebin servicexx
Comment[zh_CN]=此插件帮助您将补丁上传到 Pastebin 服务
Comment[zh_TW]=此外掛程式讓您上傳您的修補到 Pastebin 服務內
Name=Pastebin
Name[bs]=Pastebin
Name[ca]=Pastebin
Name[ca@valencia]=Pastebin
Name[cs]=Vkládací koš
Name[da]=Pastebin
Name[de]=Pastebin
Name[el]=Pastebin
Name[en_GB]=Pastebin
Name[es]=Pastebin
Name[et]=Pastebin
Name[fi]=Pastebin
Name[fr]=Pastebin
Name[ga]=Pastebin
Name[gl]=Pastebin
Name[hu]=Pastebin
Name[it]=Pastebin
Name[ja]=Pastebin
Name[kk]=Pastebin
Name[mr]=पेस्टबिन
Name[nb]=Pastebin
Name[nds]=Pastebin
Name[nl]=Pastebin
Name[pl]=Pastebin
Name[pt]=Colagem
Name[pt_BR]=Colagem
Name[ru]=Pastebin
Name[sk]=Pastebin
Name[sl]=Pastebin
Name[sv]=Pastebin
Name[tr]=Pastebin
Name[ug]=Pastebin
Name[uk]=Pastebin
Name[x-test]=xxPastebinxx
Name[zh_CN]=Pastebin
Name[zh_TW]=Pastebin
GenericName=Pastebin
GenericName[bs]=Pastebin
GenericName[ca]=Pastebin
GenericName[ca@valencia]=Pastebin
GenericName[da]=Pastebin
GenericName[de]=Pastebin
GenericName[el]=Pastebin
GenericName[en_GB]=Pastebin
GenericName[es]=Pastebin
GenericName[et]=Pastebin
GenericName[fi]=Pastebin
GenericName[fr]=Pastebin
GenericName[gl]=Pastebin
GenericName[hu]=Pastebin
GenericName[it]=Pastebin
GenericName[ja]=Pastebin
GenericName[kk]=Pastebin
GenericName[mr]=पेस्टबिन
GenericName[nb]=Pastebin
GenericName[nds]=Pastebin
GenericName[nl]=Pastebin
GenericName[pl]=Pastebin
GenericName[pt]=Colagem
GenericName[pt_BR]=Colagem
GenericName[ru]=Pastebin
GenericName[sk]=Pastebin
GenericName[sl]=Pastebin
GenericName[sv]=Pastebin
GenericName[tr]=Pastebin
GenericName[ug]=Pastebin
GenericName[uk]=Pastebin
GenericName[x-test]=xxPastebinxx
GenericName[zh_CN]=Pastebin
GenericName[zh_TW]=Pastebin
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevpastebin
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDE-PluginInfo-Name=kdevpastebin
X-KDE-PluginInfo-Author=Aleix Pol
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-Category=Utilities
X-KDevelop-Mode=GUI
X-KDevelop-Interfaces=org.kdevelop.IPatchExporter
