#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installIncAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-chello/app.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
install( "${src}/template-chello/c-Makefile.am",   "${dest}/Makefile.am" );
install( "${src}/template-chello/c-Makefile.cvs",  "${dest}/Makefile.cvs" );
install( "${src}/template-chello/configure.in",    "${dest}/configure.in" );


print "Installing application sources\n";
install( "${src}/template-chello/src-Makefile.am", "${dest}/src/Makefile.am" );
install( "${src}/template-chello/main.c",          "${dest}/src/${APPNAMELC}.c" );

print "Finished\n";
