#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
#installIncAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-pascalhello/app.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );

print "Installing application sources\n";
install( "${src}/template-pascalhello/main.pp",          "${dest}/src/${APPNAMELC}.pp" );

print "Finished\n";
