#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();

print "Installing project file\n";
install( "${src}/template-opieapp/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/apps", 0777 );
mkdir( "${dest}/pics", 0777 );
mkdir( "${dest}/pics/${APPNAMELC}", 0777 );
mkdir( "${dest}/sounds", 0777 );
mkdir( "${dest}/sounds/${APPNAMELC}", 0777 );
mkdir( "${dest}/i18n", 0777 );

print "Installing application sources\n";
install( "${src}/template-opieapp/Example.png", "${dest}/pics/${APPNAMELC}/${APPNAMELC}.png" );
install( "${src}/template-opieapp/app.pro", "${dest}/${APPNAMELC}.pro" );
install( "${src}/template-opieapp/example.cpp", "${dest}/${APPNAMELC}.cpp" );
install( "${src}/template-opieapp/example.h", "${dest}/${APPNAMELC}.h" );
install( "${src}/template-opieapp/examplebase.ui", "${dest}/${APPNAMELC}base.ui" );
install( "${src}/template-opieapp/example.desktop", "${dest}/apps/${APPNAMELC}.desktop" );

print "Finished\n";
