#!perl -I/usr/kde/3.1/share/apps/kdevappwizard/template-common

use gideon;

initGideon();

print "Installing project file\n";
install( "${src}/template-rubyhello/app.kdevelop", "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application sources\n";
install( "${src}/template-rubyhello/app.rb",       "${dest}/${APPNAMELC}.rb" );

print "Finished\n";
