# - Try to find libcommoncpp2
# Once done this will define
#
#  COMMONCPP2_FOUND - system has libcommoncpp2
#  COMMONCPP2_INCLUDE_DIRS - the commoncpp2 include directory
#  COMMONCPP2_LIBRARIES - The libraries needed to use commoncpp2



IF(COMMONCPP2_INCLUDE_DIRS AND COMMONCPP2_LIBRARIES)
    # Already in cache, be silent
    SET(Commoncpp_FIND_QUIETLY TRUE)
ENDIF(COMMONCPP2_INCLUDE_DIRS AND COMMONCPP2_LIBRARIES)

FIND_PATH(COMMONCPP2_INCLUDE_DIRS network.h
    PATH_SUFFIXES
    cc++
    PATHS
    /usr/include/cc++
    /usr/include/
    /usr/local/include/
)

FIND_LIBRARY(COMMONCPP2_GNU_LIBRARY NAMES ccgnu2 libccgnu2
    /usr/lib
    /usr/local/lib
)

FIND_LIBRARY(COMMONCPP2_EXT_LIBRARY NAMES ccext2 libccext2
    /usr/lib
    /usr/local/lib
)

IF(COMMONCPP2_INCLUDE_DIRS AND COMMONCPP2_GNU_LIBRARY)
    SET(COMMONCPP2_FOUND TRUE)
    SET(COMMONCPP2_LIBRARIES ${COMMONCPP2_GNU_LIBRARY} ${COMMONCPP2_EXT_LIBRARY})
ELSE(COMMONCPP2_INCLUDE_DIRS AND COMMONCPP2_GNU_LIBRARY)
    SET(COMMONCPP2_FOUND FALSE)
ENDIF(COMMONCPP2_INCLUDE_DIRS AND COMMONCPP2_GNU_LIBRARY)

IF(COMMONCPP2_FOUND)
  IF(NOT Commoncpp_FIND_QUIETLY)
    MESSAGE(STATUS "Found libcommoncpp2 ${COMMONCPP2_LIBRARIES}")
  ENDIF(NOT Commoncpp_FIND_QUIETLY)
ELSE(COMMONCPP2_FOUND)
  IF(Commoncpp_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Commoncpp lib")
  ENDIF(Commoncpp_FIND_REQUIRED)
ENDIF(COMMONCPP2_FOUND)

MARK_AS_ADVANCED( COMMONCPP2_INCLUDE_DIRS COMMONCPP2_GNU_LIBRARY COMMONCPP2_EXT_LIBRARY COMMONCPP2_LIBRARIES )
