# Try to find Kompare includes

set(KOMPARE_FOUND FALSE)
find_path(KOMPARE_INCLUDES kompareinterface.h HINTS ${KDE4_INCLUDE_DIR}/kompare)

#FIXME: Remove the version_greater once KDevelop has moved to 4.3
if(KOMPARE_INCLUDES AND ${KDE_VERSION} VERSION_GREATER 4.3.61)
    set(KOMPARE_FOUND TRUE)
endif(KOMPARE_INCLUDES AND ${KDE_VERSION} VERSION_GREATER 4.3.61)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Kompare DEFAULT_MSG KOMPARE_INCLUDES)

MARK_AS_ADVANCED(KOMPARE_INCLUDES)

