# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision$ 
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Hack
#PYTHONINC = -I/usr/include/python2.0
#PYTHONLIB = -L/usr/lib/python2.0/config -lpython2.0 -lpthread -ldb-3


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /home/bernd/kde2
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gideon
pkglibdir = $(libdir)/gideon
pkgincludedir = $(includedir)/gideon

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux
target_triplet = i686-pc-linux-gnu
ARTSCCONFIG = /home/bernd/kde2/bin/artsc-config
AS = @AS@
AUTODIRS = 
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = g++ -E
DCOPIDL = /home/bernd/kde2/bin/dcopidl
DCOPIDL2CPP = /home/bernd/kde2/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
GUILE = @GUILE@
GUILE_CFLAGS = @GUILE_CFLAGS@
GUILE_LDFLAGS = @GUILE_LDFLAGS@
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
KDB2HTML = /home/bernd/kde2/bin/kdb2html
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/home/bernd/kde2/include
KDE_LDFLAGS = -L/home/bernd/kde2/lib
KDE_PLUGIN = -avoid-version -module -no-undefined
KDE_RPATH = -R $(kde_libraries) -R $(qt_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = -lpython1.6 -lm -ldl 
LIBQIMGIO = @LIBQIMGIO@
LIBSM = -lSM -lICE
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lkformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lksycoca
LIB_KWRITE = -lkwrite
LIB_QT = -lqt $(LIBPNG) $(LIBJPEG) -lXext $(LIB_X11) $(LIBSM)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = /home/bernd/kde2/bin/mcopidl
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /home/bernd/kdesrc/qt-copy/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CXXFLAGS =  -fno-exceptions -fno-check-new -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long -fno-builtin
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = gideon
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = -I/usr/local/python1.6/include/python1.6
PYTHONLIB = -L/usr/local/python1.6/lib/python1.6/config
QT_INCLUDES = -I/home/bernd/kdesrc/qt-copy/include
QT_LDFLAGS = -L/home/bernd/kdesrc/qt-copy/lib
RANLIB = ranlib
REPO = -frepo
STRIP = strip
TOPSUBDIRS =  doc lib parts pics plugins po src
UIC = /home/bernd/kdesrc/qt-copy/bin/uic
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = -frtti
USE_THREADS = @USE_THREADS@
VERSION = 0.1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/home/bernd/kde2/include -I/home/bernd/kdesrc/qt-copy/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/home/bernd/kdesrc/qt-copy/lib -L/home/bernd/kde2/lib 
idldir = @idldir@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /home/bernd/kde2/include
kde_libraries = /home/bernd/kde2/lib
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
micodir = @micodir@
qt_includes = /home/bernd/kdesrc/qt-copy/include
qt_libraries = /home/bernd/kdesrc/qt-copy/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

INCLUDES = -I$(top_srcdir)/lib/interfaces 	   -I$(top_srcdir)/lib/sourceinfo 	   -I$(top_srcdir)/lib/kwrite 	   -I$(top_srcdir)/lib/util 	   $(all_includes)


bin_PROGRAMS = gideon

gideon_SOURCES = main.cpp core.cpp toplevel.cpp partloader.cpp documentationpart.cpp 		 editorpart.cpp importdlg.cpp splitter.cpp filenameedit.cpp 		 statusbar.cpp

#>- gideon_METASOURCES = AUTO
gideon_LDFLAGS = $(all_libraries) $(KDE_RPATH) 
gideon_LDADD = $(top_builddir)/parts/doctreeview/libkdevdoctreeview.la 	       $(top_builddir)/parts/classview/libkdevclassview.la 	       $(top_builddir)/parts/grepview/libkdevgrepview.la 	       $(top_builddir)/parts/outputviews/libkdevoutputviews.la 	       $(top_builddir)/parts/appwizard/libkdevappwizard.la 	       $(top_builddir)/lib/libkdevelop.la 	       $(LIB_KHTML)


rcdir = $(kde_datadir)/gideon
rc_DATA = gideonui.rc
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
bin_PROGRAMS =  gideon$(EXEEXT)
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = 
LIBS = 
#>- gideon_OBJECTS =  main.$(OBJEXT) core.$(OBJEXT) toplevel.$(OBJEXT) \
#>- partloader.$(OBJEXT) documentationpart.$(OBJEXT) editorpart.$(OBJEXT) \
#>- importdlg.$(OBJEXT) splitter.$(OBJEXT) filenameedit.$(OBJEXT) \
#>- statusbar.$(OBJEXT)
#>+ 9
gideon_final_OBJECTS = gideon.all_cpp.o 
gideon_nofinal_OBJECTS = main.$(OBJEXT) core.$(OBJEXT) toplevel.$(OBJEXT) \
partloader.$(OBJEXT) documentationpart.$(OBJEXT) editorpart.$(OBJEXT) \
importdlg.$(OBJEXT) splitter.$(OBJEXT) filenameedit.$(OBJEXT) \
statusbar.$(OBJEXT)\
splitter.moc.o importdlg.moc.o statusbar.moc.o documentationpart.moc.o editorpart.moc.o filenameedit.moc.o toplevel.moc.o core.moc.o  \
gideon_meta_unload.o 
gideon_OBJECTS = $(gideon_nofinal_OBJECTS)
#gideon_OBJECTS = $(gideon_final_OBJECTS)
gideon_DEPENDENCIES =  \
$(top_builddir)/parts/doctreeview/libkdevdoctreeview.la \
$(top_builddir)/parts/classview/libkdevclassview.la \
$(top_builddir)/parts/grepview/libkdevgrepview.la \
$(top_builddir)/parts/outputviews/libkdevoutputviews.la \
$(top_builddir)/parts/appwizard/libkdevappwizard.la \
$(top_builddir)/lib/libkdevelop.la
CXXFLAGS = -O2 -fno-exceptions -fno-check-new -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long -fno-builtin
#>- CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
#>+ 1
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) $(LDFLAGS) -o $@
DATA =  $(rc_DATA)

DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=filenameedit.h statusbar.h Makefile.am$ toplevel.h core.h documentationpart.h importdlg.h splitter.h partloader.h gideonui.rc editorpart.h gideon gideon_meta_unload.cpp 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = tar
GZIP_ENV = --best
#>- DEP_FILES =  .deps/core.P .deps/documentationpart.P .deps/editorpart.P \
#>- .deps/filenameedit.P .deps/importdlg.P .deps/main.P .deps/partloader.P \
#>- .deps/splitter.P .deps/statusbar.P .deps/toplevel.P
#>+ 8
#DEP_FILES =  $(DEPDIR)/splitter.moc.P $(DEPDIR)/importdlg.moc.P $(DEPDIR)/statusbar.moc.P $(DEPDIR)/documentationpart.moc.P $(DEPDIR)/editorpart.moc.P $(DEPDIR)/filenameedit.moc.P $(DEPDIR)/toplevel.moc.P $(DEPDIR)/core.moc.P $(DEPDIR)/gideon_meta_unload.P  $(DEPDIR)/gideon.all_cpp.P \
	  .deps/core.P .deps/documentationpart.P .deps/editorpart.P \
.deps/filenameedit.P .deps/importdlg.P .deps/main.P .deps/partloader.P \
.deps/splitter.P .deps/statusbar.P .deps/toplevel.P
DEP_FILES =  $(DEPDIR)/splitter.moc.P $(DEPDIR)/importdlg.moc.P $(DEPDIR)/statusbar.moc.P $(DEPDIR)/documentationpart.moc.P $(DEPDIR)/editorpart.moc.P $(DEPDIR)/filenameedit.moc.P $(DEPDIR)/toplevel.moc.P $(DEPDIR)/core.moc.P $(DEPDIR)/gideon_meta_unload.P   .deps/core.P .deps/documentationpart.P .deps/editorpart.P \
.deps/filenameedit.P .deps/importdlg.P .deps/main.P .deps/partloader.P \
.deps/splitter.P .deps/statusbar.P .deps/toplevel.P

SOURCES = $(gideon_SOURCES)
OBJECTS = $(gideon_OBJECTS)

#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/Makefile
	cd $(top_srcdir) && perl admin/am_edit src/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

gideon$(EXEEXT): $(gideon_OBJECTS) $(gideon_DEPENDENCIES)
	@rm -f gideon$(EXEEXT)
	$(CXXLINK) $(gideon_LDFLAGS) $(gideon_OBJECTS) $(gideon_LDADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

install-rcDATA: $(rc_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(rcdir)
	@list='$(rc_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(rcdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(rcdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(rcdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(rcdir)/$$p; \
	  fi; fi; \
	done

uninstall-rcDATA:
	@$(NORMAL_UNINSTALL)
	list='$(rc_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(rcdir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = src

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu src/Makefile
#>- 	@for file in $(DISTFILES); do \
#>- 	  d=$(srcdir); \
#>- 	  if test -d $$d/$$file; then \
#>- 	    cp -pr $$/$$file $(distdir)/$$file; \
#>- 	  else \
#>- 	    test -f $(distdir)/$$file \
#>- 	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
#>- 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
#>- 	  fi; \
#>- 	done
#>+ 10
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp

%.o: %.cpp
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.cpp
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am: install-rcDATA
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS uninstall-rcDATA
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir) $(DESTDIR)$(rcdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-binPROGRAMS clean-compile clean-libtool clean-tags \
#>- 		clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-moc-classes clean-final   clean-binPROGRAMS clean-compile clean-libtool clean-tags \
		clean-depend clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-libtool \
		distclean-tags distclean-depend distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool uninstall-rcDATA install-rcDATA \
tags mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
distdir mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


messages: 
	$(XGETTEXT) `find . -name \*.h -o -name \*.cpp` -o $(podir)/gideon.pot

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 3
splitter.moc.cpp: $(srcdir)/splitter.h
	$(MOC) $(srcdir)/splitter.h -o splitter.moc.cpp

#>+ 3
importdlg.moc.cpp: $(srcdir)/importdlg.h
	$(MOC) $(srcdir)/importdlg.h -o importdlg.moc.cpp

#>+ 3
statusbar.moc.cpp: $(srcdir)/statusbar.h
	$(MOC) $(srcdir)/statusbar.h -o statusbar.moc.cpp

#>+ 3
documentationpart.moc.cpp: $(srcdir)/documentationpart.h
	$(MOC) $(srcdir)/documentationpart.h -o documentationpart.moc.cpp

#>+ 3
editorpart.moc.cpp: $(srcdir)/editorpart.h
	$(MOC) $(srcdir)/editorpart.h -o editorpart.moc.cpp

#>+ 3
filenameedit.moc.cpp: $(srcdir)/filenameedit.h
	$(MOC) $(srcdir)/filenameedit.h -o filenameedit.moc.cpp

#>+ 3
toplevel.moc.cpp: $(srcdir)/toplevel.h
	$(MOC) $(srcdir)/toplevel.h -o toplevel.moc.cpp

#>+ 3
core.moc.cpp: $(srcdir)/core.h
	$(MOC) $(srcdir)/core.h -o core.moc.cpp

#>+ 3
clean-metasources:
	-rm -f  splitter.moc.cpp importdlg.moc.cpp statusbar.moc.cpp documentationpart.moc.cpp editorpart.moc.cpp filenameedit.moc.cpp toplevel.moc.cpp core.moc.cpp

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu src/Makefile
	cd $(top_srcdir) && perl admin/am_edit src/Makefile.in


#>+ 10
gideon_meta_unload.cpp:  splitter.moc.cpp editorpart.moc.cpp documentationpart.moc.cpp filenameedit.moc.cpp toplevel.moc.cpp importdlg.moc.cpp core.moc.cpp statusbar.moc.cpp
	@echo 'creating gideon_meta_unload.cpp'
	-rm -f gideon_meta_unload.cpp
	@echo 'static const char * _metalist_gideon[] = {' > gideon_meta_unload.cpp
	cat  splitter.moc.cpp editorpart.moc.cpp documentationpart.moc.cpp filenameedit.moc.cpp toplevel.moc.cpp importdlg.moc.cpp core.moc.cpp statusbar.moc.cpp | grep 'char.*className' | sed -e 's/.*[^A-Za-z0-9_:]\([A-Za-z0-9_:]*\)::className.*$$/\"\1\",/' | sort | uniq >> gideon_meta_unload.cpp
	@echo '0};' >> gideon_meta_unload.cpp
	@echo '#include <kunload.h>' >> gideon_meta_unload.cpp
	@echo '_UNLOAD(gideon)' >> gideon_meta_unload.cpp


#>+ 3
clean-moc-classes:
	-rm -f  gideon_meta_unload.cpp

#>+ 11
gideon.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/main.cpp $(srcdir)/core.cpp $(srcdir)/toplevel.cpp $(srcdir)/partloader.cpp $(srcdir)/documentationpart.cpp $(srcdir)/editorpart.cpp $(srcdir)/importdlg.cpp $(srcdir)/splitter.cpp $(srcdir)/filenameedit.cpp $(srcdir)/statusbar.cpp $(srcdir)/gideon_meta_unload.cpp  splitter.moc.cpp importdlg.moc.cpp statusbar.moc.cpp documentationpart.moc.cpp editorpart.moc.cpp filenameedit.moc.cpp toplevel.moc.cpp core.moc.cpp
	@echo 'creating gideon.all_cpp.cpp ...'; \
	rm -f gideon.all_cpp.files gideon.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> gideon.all_cpp.final; \
	for file in main.cpp core.cpp toplevel.cpp partloader.cpp documentationpart.cpp editorpart.cpp importdlg.cpp splitter.cpp filenameedit.cpp statusbar.cpp gideon_meta_unload.cpp  splitter.moc.cpp importdlg.moc.cpp statusbar.moc.cpp documentationpart.moc.cpp editorpart.moc.cpp filenameedit.moc.cpp toplevel.moc.cpp core.moc.cpp; do \
	  echo "#include \"$$file\"" >> gideon.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> gideon.all_cpp.final; \
	done; \
	cat gideon.all_cpp.final gideon.all_cpp.files  > gideon.all_cpp.cpp; \
	rm -f gideon.all_cpp.final gideon.all_cpp.files

#>+ 3
clean-final:
	-rm -f gideon.all_cpp.cpp

#>+ 2
final:
	$(MAKE) gideon_OBJECTS="$(gideon_final_OBJECTS)" all-am
#>+ 2
no-final:
	$(MAKE) gideon_OBJECTS="$(gideon_nofinal_OBJECTS)" all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
