#!/usr/bin/perl

use gideon;

initGideon();
installLicense();
installAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-kpartapp/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-kapp/subdirs",               "${dest}/subdirs");

print "Installing application sources\n";
install( "${src}/template-kdevlang/kdevpart-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kdevlang/src-Makefile.am", "${dest}/src/Makefile.am" );
install( "${src}/template-kdevlang/kdevlang_part.cpp",  "${dest}/src/${APPNAMELC}_part.cpp" );
install( "${src}/template-kdevlang/kdevlang_part.h",    "${dest}/src/${APPNAMELC}_part.h" );
install( "${src}/template-kdevlang/kdevlang.rc",   "${dest}/src/kdevlang_${APPNAMELC}.rc" );
install( "${src}/template-kdevlang/kdevlang.desktop",   "${dest}/src/kdevlang_${APPNAMELC}.desktop" );

print "Finished\n";
