#!/usr/bin/perl

use kdevelop;

initKDevelop();
installLicense();
installAdmin();
installGNU();

print "Installing project file\n";
installHTML( "${src}/template-kpartapp/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-kapp/subdirs",               "${dest}/subdirs");

print "Installing application sources\n";
install( "${src}/template-kdevpart2/kdevpart-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-kdevpart2/src-Makefile.am", "${dest}/src/Makefile.am" );
install( "${src}/template-kdevpart2/kdevpart_part.cpp",  "${dest}/src/${APPNAMELC}_part.cpp" );
install( "${src}/template-kdevpart2/kdevpart_part.h",    "${dest}/src/${APPNAMELC}_part.h" );
install( "${src}/template-kdevpart2/kdevpart_widget.cpp",  "${dest}/src/${APPNAMELC}_widget.cpp" );
install( "${src}/template-kdevpart2/kdevpart_widget.h",    "${dest}/src/${APPNAMELC}_widget.h" );
install( "${src}/template-kdevpart2/kdevpart_part.rc",   "${dest}/src/kdevpart_${APPNAMELC}.rc" );
install( "${src}/template-kdevpart2/kdevpart.desktop",   "${dest}/src/kdevpart_${APPNAMELC}.desktop" );

print "Finished\n";
