#!/usr/bin/env ruby


NoTarget   = 0
Executable = 1
StaticLib  = 2
SharedLib  = 3
Part       = 4

class BuildTarget
   def initialize(name, type)
      @name=name
      @type=type
      @sources=Array.new
      @uis=Array.new
      @am=Array.new
   end
   
   def addSourceFiles(files)
      files.split.each do |currentSource|
         if currentSource =~ /^\S+\.ui$/
            @uis.push(currentSource)
         else
            @sources.push(currentSource)
         end
      end
   end
   
   attr_reader :name, :type, :sources, :uis
   
end

class CMakeFile
   def initialize(amFile)
      @amFile=amFile
      amFile =~ /(.*)Makefile.am/
      @path=$1
      @listsFile=@path+"CMakeLists.txt.x"

      @targets=Array.new
      
      @includeDirs=""
      @subDirs=""
      
      parseFile
   end
   
   def parseFile
      @lines=IO.readlines(@amFile)
      cummLine=""
      appendNextLine=false
      for line in @lines do
         appendNextLine=(line[line.length-2, 1]=='\\')
         
         if appendNextLine
            cummLine+=line[0, line.length-2]
         else
            cummLine+=line[0, line.length-1]
            if not cummLine.empty? 
               evalLine(cummLine)
               cummLine=""
            end
         end
      end   
   end

   def findTarget(line)
      type=SharedLib
      if line =~ /^\s*lib(\S+)_la_\S+\s*=\s*\S+.*$/
         targetName=$1
         type=SharedLib
      elsif line =~ /^\s*(\S+)_\S+\s*=\s*\S+.*$/
         targetName=$1
         type=Executable
      end
      
      @targets.each do |buildTarget|
         if (type==Executable)
            if (buildTarget.type==Executable) && (buildTarget.name==targetName)
               return buildTarget
            end
         else
            if (buildTarget.name==targetName)
               return buildTarget
            end
         end
      end
      
      return BuildTarget.new("Dummy", NoTarget)
   end
   
   def addTarget(line)
      type=NoTarget
      targets=""
      
      if line =~ /^\s*lib_LTLIBRARIES\s*=\s*(\S+.*)/
         targets=$1
         type=SharedLib
      elsif line =~ /^\s*noinst_LTLIBRARIES\s*=\s*(\S+.*)/
         targets=$1
         type=StaticLib
      elsif line =~ /^\s*kde_module_LTLIBRARIES\s*=\s*(\S+.*)/
         targets=$1
         type=Part
      elsif line =~ /^\s*bin_PROGRAMS\s*=\s*(\S+.*)$/
         targets=$1
         type=Executable
      else
         return false
      end
      
      if type==Executable
         targets.split.each{ |current| @targets.push(BuildTarget.new(current, type)) }
      else
         targets.split.each{ |current| @targets.push(BuildTarget.new($1, type)) if current =~ /lib(\S+)\.la/  }
      end
      return true
   end
               
   def addSourcesToTarget(line)
      buildTarget=findTarget(line)
      if buildTarget.type==NoTarget
         return
      end
         
      if buildTarget.type==Executable
         line =~ /^\s*\S+_SOURCES\s*=\s*(\S+.*)$/
      else
         line =~ /^\s*lib\S+_la_SOURCES\s*=\s*(\S+.*)$/
      end
      buildTarget.addSourceFiles($1)
   end 
   
   def evalLine(line)
      if line =~ /^\s*METASOURCES\s*=\s*AUTO\s*$/
         @automoc=true
         return
      end
      
      if addTarget(line)
         return
      end
      
      if line =~ /^\s*\S+_SOURCES\s*=/
         addSourcesToTarget(line)
         return
      end
      
      if line =~ /^\s*INCLUDES\s*=\s*(\S+.*)$/
         @includeDirs=$1
         return
      end

      if line =~ /^\s*SUBDIRS\s*=\s*(\S+.*)$/
         @subDirs=$1
      end

   end
      
   def createListsFile
      printf("subdirs: %s\n", @subDirs);
      @targets.each do |buildTarget|
         printf("-------------------------------\n")
         printf("%s, %d\n", buildTarget.name, buildTarget.type)
         buildTarget.sources.each{ |currentFile| printf("src: %s\n", currentFile)}
         buildTarget.uis.each{ |currentFile| printf("ui: %s\n", currentFile)}
      end
      @lines.each{ |line| printf("# %s", line)}
   end
end

def convertAmFile(amFile)
   cmake=CMakeFile.new(amFile)
   cmake.createListsFile
end

Dir["**/Makefile.am"].each{ |currentFile| convertAmFile(currentFile)}

