#line 2 "tokenizer.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
static yyconst short int yy_acclist[269] =
    {   0,
       55,   53,   54,    1,   53,   54,   52,   54,   36,   53,
       54,   53,   54,   45,   53,   54,   33,   53,   54,   28,
       53,   54,   53,   54,   39,   53,   54,   40,   53,   54,
       31,   53,   54,   29,   53,   54,   38,   53,   54,   30,
       53,   54,   32,   53,   54,   46,   53,   54,   23,   53,
       54,   37,   53,   54,   26,   53,   54,   25,   53,   54,
       27,   53,   54,   45,   53,   54,   43,   53,   54,   44,
       53,   54,   35,   53,   54,   45,   53,   54,   45,   53,
       54,   45,   53,   54,   45,   53,   54,   45,   53,   54,
       45,   53,   54,   45,   53,   54,   45,   53,   54,   45,

       53,   54,   45,   53,   54,   41,   53,   54,   34,   53,
       54,   42,   53,   54,   24,   45,   53,   54,   51,   54,
       50,   54,   50,   51,   54,   51,   54,    1,   21,   45,
       45,   48,   46,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   49,   22,
       47,   47,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,    3,   45,
       45,   14,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   20,   45,   45,   45,   45,   45,
       45,    7,   45,   45,   12,   45,   45,   45,   45,    8,
       45,   11,   45,   45,   45,   19,   45,   45,   45,   45,
        5,   45,   45,   45,    2,   45,   10,   45,   45,   45,
       45,   45,   45,   13,   45,   45,   45,   45,   18,   45,
       45,   45,   17,   45,   45,    4,   45,    9,   45,   45,
       16,   45,    6,   45,   45,   45,   15,   45
    } ;

static yyconst short int yy_accept[194] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   20,   23,   25,   28,   31,   34,   37,   40,
       43,   46,   49,   52,   55,   58,   61,   64,   67,   70,
       73,   76,   79,   82,   85,   88,   91,   94,   97,  100,
      103,  106,  109,  112,  115,  119,  121,  123,  126,  128,
      129,  129,  130,  130,  131,  132,  132,  132,  133,  133,
      134,  134,  134,  135,  136,  137,  138,  139,  140,  141,
      142,  143,  144,  145,  146,  147,  148,  149,  150,  150,
      150,  151,  151,  151,  151,  152,  153,  154,  155,  156,
      157,  158,  159,  160,  161,  162,  163,  164,  165,  166,

      167,  168,  169,  170,  170,  170,  170,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  180,  181,  182,
      183,  184,  185,  186,  187,  188,  188,  188,  188,  188,
      189,  191,  192,  194,  195,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  207,  208,  209,  210,  211,
      212,  214,  215,  217,  218,  219,  220,  222,  224,  225,
      226,  228,  229,  230,  231,  233,  234,  235,  237,  239,
      240,  241,  242,  243,  244,  246,  247,  248,  249,  251,
      252,  253,  255,  256,  258,  260,  261,  263,  265,  266,
      267,  269,  269

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,    1,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   27,
        7,    7,    7,    7,    7,   28,    7,    7,   29,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       30,   31,   32,   33,    7,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    7,   43,   44,   45,   46,
       47,   48,    7,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    7,    7,    7,
        7,    7,    7,    7,    7
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    3,    4,    1,    1,    5,
        1,    1,    1,    1,    1,    1,    1,    6,    7,    1,
        1,    1,    1,    1,    3,    7,    7,    4,    4,    1,
        3,    1,    1,    6,    6,    7,    7,    7,    6,    4,
        4,    4,    4,    4,    4,    8,    4,    4,    8,    4,
        8,    4,    8,    4,    8,    4,    4,    1,    1,    1,
        4
    } ;

static yyconst short int yy_base[203] =
    {   0,
        0,    0,   59,   61,  143,  642,   64,  642,  642,   61,
       51,  642,  642,  100,  642,  642,  642,  642,  642,  642,
       58,   58,  642,  642,  642,  642,  642,   72,  642,  642,
      642,   61,   65,   67,   69,   75,   79,   81,   83,   86,
       89,  642,  642,  642,   98,  642,  642,  642,   97,  108,
       75,  642,   71,  100,    0,   93,   77,  642,  120,  110,
      119,   42,  119,  122,  127,  133,  135,  139,  141,  144,
      146,  149,  152,  154,  156,  163,  158,  642,  181,    0,
      642,  185,    0,  182,  642,  186,  199,  201,  203,  205,
      208,  210,  212,  214,  216,  219,  224,  226,  240,  228,

      242,  244,  247,  261,  287,  265,  317,  253,  266,  255,
      268,  279,  281,  285,  276,  313,  323,  290,  319,  321,
      331,  292,  327,  340,  346,  160,    0,  352,    0,  350,
      301,  352,  354,  356,  358,  360,  367,  373,  369,  375,
      385,  388,  377,  396,  398,  400,  404,  407,  411,  413,
      415,  418,  420,  422,  431,  435,  437,  439,  444,  446,
      448,  452,  454,  456,  458,  460,  463,  466,  469,  473,
      476,  482,  484,  478,  486,  490,  494,  496,  499,  501,
      503,  507,  516,  518,  520,  526,  528,  530,  532,  534,
      537,  642,  583,  591,  596,  604,  610,  615,  621,  629,

      632,  634
    } ;

static yyconst short int yy_def[203] =
    {   0,
      192,    1,  193,  193,  192,  192,  192,  192,  192,  194,
      195,  192,  192,  196,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  195,  192,  192,
      192,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  192,  192,  192,  195,  192,  192,  192,  192,  192,
      194,  192,  197,  195,  198,  196,  199,  192,  200,  192,
      194,  196,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  192,  194,  201,
      192,  196,  202,  200,  192,  200,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  194,  194,  196,  196,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  194,  105,  196,  107,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,    0,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192
    } ;

static yyconst short int yy_nxt[704] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   22,   23,
       24,   25,   26,   27,    6,   11,   11,   28,   11,   29,
        6,   30,   31,   32,   11,   33,   11,   34,   35,   11,
       11,   36,   11,   11,   11,   37,   11,   38,   11,   39,
       40,   11,   41,   11,   11,   11,   11,   42,   43,   44,
       45,   47,   48,   47,   48,   50,   52,   50,   55,   55,
       58,   49,   57,   49,   59,   60,   60,   61,   55,   55,
       52,   62,   55,   55,   55,   55,   55,   55,   79,   55,
       55,   53,   55,   55,   82,   63,   55,   55,   55,   55,

       55,   55,   81,   55,   55,   53,   55,   55,   64,   50,
       66,   50,   69,   78,   70,   55,   55,   55,   55,   67,
       68,   65,   85,   57,   52,   80,   75,   60,   60,   71,
       57,   83,   72,   73,   76,   77,   55,   55,   74,   55,
       55,   86,  192,   86,   55,   55,   86,  192,   86,   53,
       55,   55,   55,   55,  192,   88,   55,   55,   55,   55,
      192,   55,   55,   55,   55,   52,   55,   55,   87,   55,
       55,   55,   55,   55,   55,   55,   55,   89,   90,   94,
       55,   55,   91,   97,   85,   98,   52,   95,   85,   92,
       53,   93,   96,  192,   81,  192,  102,  192,  104,  100,

       99,  103,  106,   86,  101,   86,  192,   86,   86,   86,
       86,   53,   86,  192,   86,   57,   55,   55,   55,   55,
       55,   55,   55,   55,  192,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,  192,   55,   55,  111,  192,
      110,   55,   55,   55,   55,   55,   55,  114,  192,  108,
      109,  112,  192,  115,  113,  192,  116,   55,   55,   55,
       55,   55,   55,  122,   55,   55,   52,  119,  117,  118,
       55,   55,   55,   55,   81,  192,  120,  192,  126,  192,
      125,  121,  128,   55,   55,   55,   55,  192,  123,  124,
      192,   53,   52,   55,   55,   57,   55,   55,   55,   55,

      132,  130,   55,   55,  127,  127,  192,   55,   55,   55,
       55,  133,  127,  127,  192,  131,  134,   53,   55,   55,
      127,  127,  127,  127,  127,  127,   81,  140,  137,  135,
       55,   55,  144,  136,  129,  129,   55,   55,   55,   55,
       55,   55,  129,  129,   55,   55,  138,   57,   55,   55,
      129,  129,  129,  129,  129,  129,  139,   55,   55,  192,
      141,   81,  142,   55,   55,  192,  143,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,  192,
      145,  192,   57,  148,   55,   55,   55,   55,  149,  146,
       55,   55,   55,   55,   55,   55,  147,  192,  152,  192,

      150,  192,   55,   55,  153,   55,   55,  192,  151,  192,
      156,  192,  154,   55,   55,   55,   55,   55,   55,  155,
      157,   55,   55,  158,   55,   55,  192,  159,   55,   55,
       55,   55,   55,   55,  192,   55,   55,   55,   55,   55,
       55,  162,  164,  192,  160,  163,  192,  161,   55,   55,
      166,  167,   55,   55,   55,   55,   55,   55,  192,  168,
      165,   55,   55,   55,   55,   55,   55,  192,  169,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,  192,
       55,   55,  171,   55,   55,  170,   55,   55,  192,  173,
       55,   55,  172,   55,   55,   55,   55,  174,  177,   55,

       55,   55,   55,   55,   55,  176,  175,   55,   55,  192,
      178,   55,   55,   55,   55,  182,   55,   55,   55,   55,
       55,   55,  192,  179,   55,   55,  192,  180,  192,  181,
      192,  184,  185,   55,   55,   55,   55,   55,   55,  192,
      183,  192,  186,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,  187,   55,   55,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  188,  192,  192,  192,  190,
      191,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  189,   46,   46,   46,   46,   46,   46,   46,
       46,   51,  192,   51,   51,   51,   51,   51,   51,   54,

      192,   54,   54,   54,   56,  192,   56,   56,  192,   56,
       56,   56,   51,  192,   51,   51,  192,   51,   55,  192,
       55,   55,   55,   56,  192,   56,   56,  192,   56,   84,
       84,   84,   84,   84,   84,   84,   84,  105,  105,  107,
      107,    5,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192
    } ;

static yyconst short int yy_chk[704] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    7,   10,    7,   11,   11,
       21,    3,   62,    4,   21,   22,   22,   28,   32,   32,
       51,   28,   33,   33,   34,   34,   35,   35,   53,   28,
       28,   10,   36,   36,   57,   32,   37,   37,   38,   38,

       39,   39,   56,   40,   40,   51,   41,   41,   33,   50,
       35,   50,   37,   49,   38,   45,   45,   54,   54,   36,
       36,   34,   59,   56,   61,   53,   40,   60,   60,   38,
       14,   57,   38,   39,   40,   41,   63,   63,   39,   64,
       64,   59,    5,   59,   65,   65,   59,    0,   59,   61,
       66,   66,   67,   67,    0,   64,   68,   68,   69,   69,
        0,   70,   70,   71,   71,  126,   72,   72,   63,   73,
       73,   74,   74,   75,   75,   77,   77,   65,   66,   70,
       76,   76,   67,   72,   84,   73,   79,   71,   86,   68,
      126,   69,   71,    0,   82,    0,   76,    0,   79,   74,

       73,   77,   82,   84,   75,   84,    0,   86,   84,   86,
       84,   79,   86,    0,   86,   82,   87,   87,   88,   88,
       89,   89,   90,   90,    0,   91,   91,   92,   92,   93,
       93,   94,   94,   95,   95,    0,   96,   96,   90,    0,
       89,   97,   97,   98,   98,  100,  100,   92,    0,   87,
       88,   91,    0,   93,   91,    0,   94,   99,   99,  101,
      101,  102,  102,  100,  103,  103,  104,   97,   95,   96,
      108,  108,  110,  110,  106,    0,   98,    0,  104,    0,
      103,   99,  106,  109,  109,  111,  111,    0,  101,  102,
        0,  104,  105,  115,  115,  106,  112,  112,  113,  113,

      110,  108,  114,  114,  105,  105,    0,  118,  118,  122,
      122,  111,  105,  105,    0,  109,  112,  105,  131,  131,
      105,  105,  105,  105,  105,  105,  107,  118,  115,  113,
      116,  116,  122,  114,  107,  107,  119,  119,  120,  120,
      117,  117,  107,  107,  123,  123,  116,  107,  121,  121,
      107,  107,  107,  107,  107,  107,  117,  124,  124,    0,
      119,  128,  120,  125,  125,    0,  121,  130,  130,  132,
      132,  133,  133,  134,  134,  135,  135,  136,  136,    0,
      123,    0,  128,  130,  137,  137,  139,  139,  132,  124,
      138,  138,  140,  140,  143,  143,  125,    0,  136,    0,

      134,    0,  141,  141,  137,  142,  142,    0,  135,    0,
      140,    0,  138,  144,  144,  145,  145,  146,  146,  139,
      141,  147,  147,  142,  148,  148,    0,  143,  149,  149,
      150,  150,  151,  151,    0,  152,  152,  153,  153,  154,
      154,  146,  148,    0,  144,  147,    0,  145,  155,  155,
      150,  152,  156,  156,  157,  157,  158,  158,    0,  154,
      149,  159,  159,  160,  160,  161,  161,    0,  155,  162,
      162,  163,  163,  164,  164,  165,  165,  166,  166,    0,
      167,  167,  159,  168,  168,  156,  169,  169,    0,  162,
      170,  170,  160,  171,  171,  174,  174,  163,  167,  172,

      172,  173,  173,  175,  175,  166,  164,  176,  176,    0,
      170,  177,  177,  178,  178,  174,  179,  179,  180,  180,
      181,  181,    0,  171,  182,  182,    0,  172,    0,  173,
        0,  177,  178,  183,  183,  184,  184,  185,  185,    0,
      176,    0,  180,  186,  186,  187,  187,  188,  188,  189,
      189,  190,  190,  181,  191,  191,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  183,    0,    0,    0,  189,
      190,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  186,  193,  193,  193,  193,  193,  193,  193,
      193,  194,    0,  194,  194,  194,  194,  194,  194,  195,

        0,  195,  195,  195,  196,    0,  196,  196,    0,  196,
      196,  196,  197,    0,  197,  197,    0,  197,  198,    0,
      198,  198,  198,  199,    0,  199,  199,    0,  199,  200,
      200,  200,  200,  200,  200,  200,  200,  201,  201,  202,
      202,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192
    } ;

#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "./tokenizer.l"
#define INITIAL 0
/***************************************************************************
                          tokenizer.l  -  Derived from the C++ tokenizer
                          					in the cppsupport KDevelop part
                          					by Jonas Nordin
                             -------------------
    begin                : Wed Dec 12 2000
    copyright            : (C) 2000 by Richard Dale
    email                : Richard_Dale@tipitina.demon.co.uk
   
 ***************************************************************************/
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   * 
 *                                                                         *
 ***************************************************************************/
#define COMMENT 1

#line 23 "./tokenizer.l"
  #include <stdlib.h>
  #include <qstring.h>
  #include <iostream.h>
  #include "tokenizer.h"
  #include "FlexLexer.h"

  /** This class is a stupid trick to make it possible 
   * to access the gettext method. */
  class MyLexer : public yyFlexLexer
  {
    public:
    char *gettext() {return yytext;};
  };

  /* Line where a comment starts. */
  int comment_start = -1;

  /* Line where a comment ends. */
  int comment_end = -1;

  /* Last parsed comment. */
  QString comment;

  /* Function prototypes */
  bool beginComment(MyLexer *lex);
  void inComment(MyLexer *lex);
  bool endComment(MyLexer *lex);
#line 635 "tokenizer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 69 "./tokenizer.l"

    /*==============> Strip whitespace <==============*/
#line 765 "tokenizer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 193 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 642 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 71 "./tokenizer.l"
{}
	YY_BREAK
/*==============> Special keyword <==============*/
case 2:
YY_RULE_SETUP
#line 74 "./tokenizer.l"
{return JAVAPACKAGE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "./tokenizer.l"
{return JAVACLASS;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "./tokenizer.l"
{return JAVAINTERFACE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "./tokenizer.l"
{return JAVAEXTENDS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "./tokenizer.l"
{return JAVAIMPLEMENTS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "./tokenizer.l"
{return JAVAIMPORTS;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "./tokenizer.l"
{return JAVAPUBLIC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "./tokenizer.l"
{return JAVAPROTECTED;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "./tokenizer.l"
{return JAVAPRIVATE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "./tokenizer.l"
{return JAVASTATIC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "./tokenizer.l"
{return JAVANATIVE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "./tokenizer.l"
{return JAVAABSTRACT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "./tokenizer.l"
{return JAVAFINAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "./tokenizer.l"
{return JAVASYNCHRONIZED;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "./tokenizer.l"
{return JAVATRANSIENT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "./tokenizer.l"
{return JAVAVOLATILE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "./tokenizer.l"
{return JAVASTRICTFP;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "./tokenizer.l"
{return JAVATHROWS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "./tokenizer.l"
{return JAVATHROW;}
	YY_BREAK
/*==============> String <==============*/
case 21:
YY_RULE_SETUP
#line 95 "./tokenizer.l"
{return STRING;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "./tokenizer.l"
{return STRING;}
	YY_BREAK
/*==============> Normal operators <==============*/
case 23:
YY_RULE_SETUP
#line 99 "./tokenizer.l"
{return ':';}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 100 "./tokenizer.l"
{return '~';}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 101 "./tokenizer.l"
{return '=';}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 102 "./tokenizer.l"
{return '<';}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 103 "./tokenizer.l"
{return '>';}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 104 "./tokenizer.l"
{return '&';}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 105 "./tokenizer.l"
{return '+';}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 106 "./tokenizer.l"
{return '-';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 107 "./tokenizer.l"
{return '*';}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 108 "./tokenizer.l"
{return '/';}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 109 "./tokenizer.l"
{return '%';}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "./tokenizer.l"
{return '|';}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 111 "./tokenizer.l"
{return '^';}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 112 "./tokenizer.l"
{return '!';}
	YY_BREAK
/*==============> End of Phrase <==============*/
case 37:
YY_RULE_SETUP
#line 115 "./tokenizer.l"
{return ';';}
	YY_BREAK
/*==============> Comma <==============*/
case 38:
YY_RULE_SETUP
#line 118 "./tokenizer.l"
{return ',';}
	YY_BREAK
/*==============> Paranthesis <==============*/
case 39:
YY_RULE_SETUP
#line 121 "./tokenizer.l"
{return '(';}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "./tokenizer.l"
{return ')';}
	YY_BREAK
/*==============> Brackets <==============*/
case 41:
YY_RULE_SETUP
#line 125 "./tokenizer.l"
{return '{';}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "./tokenizer.l"
{return '}';}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 127 "./tokenizer.l"
{return '[';}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 128 "./tokenizer.l"
{return ']';}
	YY_BREAK
/*==============> Identifiers <==============*/
case 45:
YY_RULE_SETUP
#line 131 "./tokenizer.l"
{return ID;}
	YY_BREAK
/*==============> Numbers <==============*/
case 46:
YY_RULE_SETUP
#line 134 "./tokenizer.l"
{return NUM;}
	YY_BREAK
/*==============> Strip // comments <==============*/
case 47:
YY_RULE_SETUP
#line 138 "./tokenizer.l"
{}
	YY_BREAK
/*==============> Strip comments <==============*/
case 48:
YY_RULE_SETUP
#line 141 "./tokenizer.l"
{beginComment((MyLexer *) this);
                                  BEGIN (COMMENT);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "./tokenizer.l"
{ endComment((MyLexer *) this);
                       BEGIN (0); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 147 "./tokenizer.l"
{inComment((MyLexer *) this);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 148 "./tokenizer.l"
{inComment((MyLexer *) this);}
	YY_BREAK
/*==============> All other characters are ignored <==============*/
case 52:
YY_RULE_SETUP
#line 151 "./tokenizer.l"
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 152 "./tokenizer.l"
{}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "./tokenizer.l"
ECHO;
	YY_BREAK
#line 1146 "tokenizer.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 193 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 193 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 192);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 154 "./tokenizer.l"


static bool beginComment(MyLexer *lex)
{
 comment_start = lex->lineno();
 comment="/*";
 return true;
}

static void inComment(MyLexer *lex)
{
  char *text=lex->gettext();
  comment+=text;
};

static bool endComment(MyLexer *lex)
{
 comment_end = lex->lineno();
 comment+="*/";
 return true;
}

