#!/usr/bin/perl

use gideon;

initGideon();
installFileTemplate();
installLicense();
installGNU();

print "Installing project file\n";
install( "${src}/template-superwaba/sw.kdevelop",    "${dest}/${APPNAMELC}.kdevelop" );
install( "${src}/template-superwaba/sw.filelist",    "${dest}/${APPNAMELC}.filelist" );

print "Installing application framework\n";
install( "${src}/template-superwaba/src-Makefile",   "${dest}/Makefile" );

print "Installing application sources\n";
install( "${src}/template-superwaba/sw.java",          "${dest}/${APPNAME}.java" );

print "Finished\n";
