#line 2 "tokenizer.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
static yyconst short int yy_acclist[381] =
    {   0,
       79,   77,   78,    1,   77,   78,   76,   78,   56,   77,
       78,   77,   78,   77,   78,   53,   77,   78,   48,   77,
       78,   77,   78,   59,   77,   78,   60,   77,   78,   51,
       77,   78,   49,   77,   78,   58,   77,   78,   50,   77,
       78,   52,   77,   78,   66,   77,   78,   42,   77,   78,
       57,   77,   78,   46,   77,   78,   45,   77,   78,   47,
       77,   78,   77,   78,   65,   77,   78,   65,   77,   78,
       65,   77,   78,   65,   77,   78,   63,   77,   78,   64,
       77,   78,   55,   77,   78,   65,   77,   78,   65,   77,
       78,   65,   77,   78,   65,   77,   78,   65,   77,   78,

       65,   77,   78,   65,   77,   78,   65,   77,   78,   65,
       77,   78,   65,   77,   78,   65,   77,   78,   65,   77,
       78,   65,   77,   78,   61,   77,   78,   54,   77,   78,
       62,   77,   78,   44,   65,   77,   78,   75,   78,   74,
       78,   74,   75,   78,   75,   78,   77,   78,    1,   77,
       78,   76,   78,   77,   78,   75,   78,    1,   40,   67,
       72,   66,   43,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   73,   68,
       69,   70,   41,   71,   71,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   39,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   12,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,    2,   65,    6,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   11,   65,   65,   65,   65,
       19,   65,   65,   16,   65,   65,   65,   32,   24,   65,
       65,   65,   65,   65,   65,   65,   65,   29,   65,   14,

       65,   27,   65,   65,   65,   65,   65,    3,   65,   65,
        8,   65,   15,   65,   65,   65,   65,   65,   37,   65,
       65,   65,   65,   65,   65,   28,   65,   65,   65,    5,
       65,   65,   10,   65,   65,   13,   65,    9,   65,   65,
       35,   31,   21,   65,   23,   65,   65,   65,   65,   65,
       17,   65,   65,   18,   65,    7,   65,   34,   22,   65,
       65,   65,   65,   20,   65,    4,   65,   33,   36,   65,
       65,   65,   30,   65,   26,   65,   65,   25,   65,   38
    } ;

static yyconst short int yy_accept[328] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    7,    9,   12,   14,   16,   19,   22,   24,   27,
       30,   33,   36,   39,   42,   45,   48,   51,   54,   57,
       60,   63,   65,   68,   71,   74,   77,   80,   83,   86,
       89,   92,   95,   98,  101,  104,  107,  110,  113,  116,
      119,  122,  125,  128,  131,  134,  138,  140,  142,  145,
      147,  149,  152,  154,  156,  158,  159,  159,  160,  160,
      161,  161,  161,  162,  162,  163,  164,  164,  164,  164,
      164,  165,  166,  167,  167,  167,  168,  169,  170,  171,
      172,  173,  174,  175,  176,  177,  178,  179,  180,  181,

      182,  183,  184,  185,  186,  187,  188,  189,  190,  191,
      192,  193,  193,  193,  194,  194,  194,  194,  195,  196,
      196,  196,  196,  196,  196,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  206,  207,  208,  209,  210,
      211,  212,  213,  214,  215,  216,  217,  218,  219,  220,
      221,  222,  223,  224,  224,  224,  224,  224,  224,  225,
      225,  225,  225,  225,  225,  226,  227,  228,  229,  230,
      231,  232,  233,  234,  235,  237,  238,  239,  240,  241,
      242,  243,  244,  245,  246,  247,  248,  249,  250,  251,
      252,  253,  254,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  256,  257,  258,  259,  260,  261,
      262,  263,  265,  267,  268,  269,  270,  271,  272,  273,
      274,  275,  276,  278,  279,  280,  281,  283,  284,  286,
      287,  288,  289,  289,  289,  289,  289,  289,  289,  291,
      292,  293,  294,  295,  296,  297,  298,  300,  302,  304,
      305,  306,  307,  308,  310,  311,  313,  315,  316,  317,
      318,  319,  319,  319,  319,  319,  319,  320,  321,  322,
      323,  324,  325,  326,  328,  329,  330,  332,  333,  335,
      336,  338,  340,  341,  341,  341,  342,  342,  342,  343,
      345,  347,  348,  349,  350,  351,  353,  354,  356,  358,

      358,  358,  358,  359,  361,  362,  363,  364,  366,  368,
      368,  369,  370,  371,  372,  373,  373,  374,  375,  377,
      377,  378,  378,  380,  380,  381,  381
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,    1,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   49,   50,   51,   49,
       52,   53,   54,   55,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   49,   49,   66,   67,   68,
       69,   70,   49,   71,   72,   73,   74,   75,   76,   77,
       78,   49,   79,   80,   81,   82,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[83] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    5,    6,
        1,    1,    1,    1,    1,    3,    1,    6,    6,    6,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    3,    1,    1,    7,    5,    5,    6,    6,
        6,    5,    7,    7,    7,    7,    7,    8,    7,    7,
        8,    7,    8,    7,    8,    7,    8,    7,    1,    1,
        1,    7
    } ;

static yyconst short int yy_base[338] =
    {   0,
        0,    0,   80,   82,   85,   95,   88,  101,  667,  970,
      104,  970,  970,   86,   90,  970,  970,  601,  970,  970,
      970,  970,  970,  970,   93,   97,  627,  970,  970,  970,
      970,   53,  100,  102,  117,  107,  970,  970,  970,  111,
      113,  115,  121,  123,  125,  133,  149,  151,  158,  154,
      160,  168,  970,  970,  970,  163,  970,  970,  970,  607,
      620,  197,  607,  151,  584,  201,  103,  970,   82,  970,
      161,  127,  970,  188,  166,  970,  531,  525,  128,  136,
        0,  189,  207,  190,  531,  197,  215,  222,  226,  229,
      231,  233,  235,  237,  240,  243,  245,  250,  248,  252,

      255,  257,  259,  261,  267,  265,  269,  970,  970,  970,
      970,  275,    0,  970,  290,    0,  314,  970,  317,  522,
      517,  495,  486,   60,  499,  272,  303,  296,  332,  335,
      338,  314,  276,  299,  341,  343,  345,  349,  354,  356,
      361,  364,  366,  370,  368,  372,  374,  376,  378,  381,
      383,  390,  392,  398,  457,  402,  509,  478,  970,  467,
      465,  438,  427,  425,  411,  406,  400,  403,  414,  438,
      440,  442,  409,  448,  446,  454,  459,  463,  450,  473,
      475,  482,  479,  477,  484,  486,  488,  492,  504,  516,
      526,  529,  533,  205,  600,  371,  652,  412,  419,  404,

      393,  229,  379,  535,  541,  544,  553,  555,  563,  568,
      570,  572,  576,  581,  585,  589,  594,  592,  596,  607,
      615,  602,  598,  617,  619,  621,  624,  627,  632,  636,
      667,  970,  372,  373,  345,  357,  348,  340,  670,  675,
      677,  687,  683,  679,  699,  681,  704,  706,  708,  714,
      716,  718,  720,  722,  726,  728,  730,  732,  734,  736,
      738,  317,  315,  305,  272,  272,  970,  747,  741,  743,
      749,  745,  754,  756,  758,  761,  763,  772,  780,  787,
      789,  791,  793,  270,  270,  970,  266,  247,  970,  795,
      799,  802,  804,  806,  808,  818,  820,  822,  824,  220,

      212,  206,  970,  826,  831,  833,  836,  838,  840,  204,
      970,  970,  851,  842,  847,  163,  970,  857,  854,  127,
      859,  107,  864,   93,  970,  970,  905,  913,  921,  929,
      933,  939,  945,  953,  957,  961,  963
    } ;

static yyconst short int yy_def[338] =
    {   0,
      326,    1,  327,  327,  328,  328,  327,  327,  326,  326,
      326,  326,  326,  329,  326,  326,  326,  330,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  331,  331,  331,  331,  326,  326,  326,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  326,  326,  326,  331,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  329,  326,  332,  326,
      330,  333,  326,  334,  326,  326,  326,  326,  326,  326,
      335,  331,  331,  329,  330,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331,  331,  331,  331,  331,  331,  326,  326,  326,
      326,  329,  336,  326,  330,  337,  334,  326,  334,  326,
      326,  326,  326,  326,  326,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  329,  329,  330,  330,  326,  326,  326,
      326,  326,  326,  326,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  329,  329,  330,  330,  326,  326,  326,

      326,  326,  326,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  326,  326,  326,  326,  326,  326,  326,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  326,  326,  326,  326,  326,  326,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  326,  326,  326,  326,  326,  326,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  326,

      326,  326,  326,  331,  331,  331,  331,  331,  331,  326,
      326,  326,  331,  331,  331,  326,  326,  331,  331,  326,
      331,  326,  331,  326,  326,    0,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326
    } ;

static yyconst short int yy_nxt[1053] =
    {   0,
       10,   11,   12,   11,   11,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,   31,   10,   32,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   34,   35,   33,
       33,   33,   33,   36,   33,   33,   33,   33,   33,   33,
       33,   37,   10,   38,   39,   40,   41,   33,   42,   33,
       43,   44,   33,   33,   45,   33,   33,   46,   47,   48,
       33,   49,   50,   51,   52,   33,   33,   33,   53,   54,
       55,   56,   58,   59,   58,   59,   62,   63,   62,   62,
       58,   59,   68,   60,   70,   60,   62,   63,   62,   62,

      112,   65,   64,   58,   59,   66,   73,   66,   66,   68,
       74,   77,   64,   78,   65,   75,   75,   79,   81,   81,
       81,   81,   80,   84,  162,   81,   81,   85,  163,   81,
       81,   81,   81,   81,   81,   81,   81,   10,   69,   81,
       81,   81,   81,   81,   81,  115,   70,   10,   70,   70,
       70,   81,   81,  109,   70,   69,   70,   83,  113,   70,
      325,   70,   86,   70,  110,   70,   87,   81,   81,   81,
       81,  114,   81,   81,   88,  324,   81,   81,   81,   81,
       89,   81,   81,   90,   75,   75,   81,   81,   91,   95,
      118,  322,   94,   93,  122,  123,   68,   92,   66,  109,

       66,   66,   66,  116,   66,   66,  124,   81,   81,  125,
      119,   68,  119,   72,  102,   81,   81,  103,   96,  119,
      119,   97,   99,  100,   98,   81,   81,  105,  127,  119,
      101,  104,  106,   81,   81,  320,  107,  126,  128,  129,
       81,   81,   69,  130,   81,   81,  131,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   69,   81,   81,
      316,   81,   81,   81,   81,  312,   81,   81,   81,   81,
       81,   81,  311,   81,   81,   81,   81,   81,   81,   81,
       81,   68,  133,   81,   81,   81,   81,   81,   81,  236,
       81,   81,  310,  154,   81,   81,  134,  237,  132,  137,

      114,  165,  138,  140,  135,  136,  139,  143,  156,  141,
      144,  146,  303,  142,   81,   81,  118,   81,   81,  118,
      145,   81,   81,  148,  168,  147,  302,   69,  301,  149,
      150,  151,   81,   81,  153,  152,  119,  300,  119,  119,
      288,  119,   72,  166,  287,  119,  119,  173,  119,  119,
       81,   81,  167,   81,   81,  119,   81,   81,  119,   81,
       81,   81,   81,   81,   81,  286,  170,   81,   81,  172,
      174,  285,   81,   81,   81,   81,  169,  284,  171,   81,
       81,  114,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  267,   81,

       81,   81,   81,  176,   68,  177,  266,  175,   81,   81,
       81,   81,  114,  178,  179,  265,  194,  264,   81,   81,
      196,   81,   81,   72,   81,   81,  180,   81,   81,   81,
       81,  183,   81,   81,  263,  181,  182,  184,  262,  207,
      185,  190,  206,  238,  186,  188,  189,  187,  193,  235,
       69,  191,  204,  205,   72,  208,   81,   81,   81,   81,
       81,   81,  192,   68,   81,   81,   81,   81,   81,   81,
      210,  209,   81,   81,  234,  195,  195,   81,   81,  233,
      212,   81,   81,  232,  195,  195,  195,  195,  195,  195,
      203,   81,   81,   81,   81,   81,   81,   81,   81,  202,

       81,   81,   81,   81,   81,   81,   81,   81,  211,   69,
       81,   81,  201,  195,  195,  195,  195,  195,  195,  114,
      213,  217,   81,   81,  214,  200,  215,  197,  197,  218,
      216,  219,  199,  222,   81,   81,  197,  197,  197,  197,
      197,  197,  220,  221,   81,   81,  225,   81,   81,  198,
      224,   81,   81,   81,   81,  223,  164,  226,  161,   81,
       81,   72,   81,   81,  160,  197,  197,  197,  197,  197,
      197,   81,   81,   81,   81,  228,  159,  239,  158,  227,
      240,   81,   81,   72,  242,  241,   81,   81,   81,   81,
       81,   81,  121,  229,   81,   81,  120,  243,  244,   81,

       81,  111,  230,   81,   81,  231,   68,   81,   81,  109,
       81,   81,   81,   81,   81,   81,   81,   81,  195,  195,
       81,   81,  109,  245,  108,   81,   81,  195,  195,  195,
      195,  195,  195,   81,   81,   81,   81,   81,   81,   81,
       81,  246,   81,   81,  248,   81,   81,   76,  247,  249,
       81,   81,   69,   72,   81,   81,  195,  195,  195,  195,
      195,  195,  114,  250,  251,  253,  326,  255,  252,  326,
      197,  197,  326,  254,  326,  256,  326,  258,  326,  197,
      197,  197,  197,  197,  197,   81,   81,  259,   81,   81,
      326,  257,  260,   81,   81,   81,   81,   81,   81,   81,

       81,   81,   81,  326,   72,   81,   81,  326,  197,  197,
      197,  197,  197,  197,  271,  326,  270,   81,   81,  272,
      268,  269,   81,   81,   81,   81,   81,   81,  326,  273,
      326,  261,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,  326,  274,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  289,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,  326,
      275,  326,   81,   81,   81,   81,   81,   81,  277,   81,
       81,   81,   81,  326,  276,  294,  326,  290,  326,  291,
       81,   81,  278,  292,  326,  281,  326,  279,   81,   81,

      293,  282,  326,  283,  280,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,  326,  295,   81,   81,  326,
       81,   81,   81,   81,   81,   81,   81,   81,  326,  304,
      326,  296,  297,  326,  306,  307,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,  326,  298,  305,   81,
       81,   81,   81,  299,   81,   81,   81,   81,   81,   81,
       81,   81,  317,  326,  314,   81,   81,  326,  308,   81,
       81,  318,   81,   81,  315,   81,   81,   81,   81,  309,
      326,  313,   81,   81,  326,  326,  326,  326,  326,  326,
      326,  326,  319,  326,  326,  321,  326,  326,  326,  326,

      326,  326,  326,  326,  323,   57,   57,   57,   57,   57,
       57,   57,   57,   61,   61,   61,   61,   61,   61,   61,
       61,   67,  326,   67,   67,   67,   67,   67,   67,   71,
      326,   71,  326,   71,   71,   71,   71,   82,   82,   82,
       82,   67,   67,   67,  326,  326,   67,   71,   71,   71,
      326,  326,   71,  117,  117,  117,  117,  117,  117,  117,
      117,   81,   81,   81,   81,  155,  155,  157,  157,    9,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326
    } ;

static yyconst short int yy_chk[1053] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    5,    5,    5,    5,
        7,    7,   14,    3,   15,    4,    6,    6,    6,    6,

       69,    7,    5,    8,    8,   11,   25,   11,   11,   67,
       25,   32,    6,   32,    8,   26,   26,   32,   33,   33,
       34,   34,   32,   35,  124,   36,   36,   35,  124,   40,
       40,   41,   41,   42,   42,   35,   35,    5,   14,   43,
       43,   44,   44,   45,   45,   72,   15,    6,   15,   15,
       15,   46,   46,   64,   15,   67,   15,   34,   69,   15,
      324,   15,   36,   15,   64,   15,   40,   47,   47,   48,
       48,   71,   50,   50,   41,  322,   49,   49,   51,   51,
       42,   56,   56,   42,   75,   75,   52,   52,   43,   46,
       74,  320,   45,   44,   79,   79,   84,   43,   62,   62,

       62,   62,   66,   72,   66,   66,   80,   82,   82,   80,
       74,  194,   74,   71,   50,   86,   86,   50,   47,   74,
       74,   48,   49,   49,   48,   83,   83,   51,   86,   74,
       49,   50,   52,   87,   87,  316,   52,   83,   86,   86,
       88,   88,   84,   87,   89,   89,   87,   90,   90,   91,
       91,   92,   92,   93,   93,   94,   94,  194,   95,   95,
      310,   96,   96,   97,   97,  302,   99,   99,   98,   98,
      100,  100,  301,  101,  101,  102,  102,  103,  103,  104,
      104,  112,   89,  106,  106,  105,  105,  107,  107,  202,
      126,  126,  300,  112,  133,  133,   90,  202,   88,   93,

      115,  126,   94,   96,   91,   92,   95,   98,  115,   97,
       99,  101,  288,   97,  128,  128,  117,  134,  134,  119,
      100,  127,  127,  102,  128,  101,  287,  112,  285,  103,
      104,  105,  132,  132,  107,  106,  117,  284,  117,  119,
      266,  119,  115,  127,  265,  117,  117,  133,  119,  119,
      129,  129,  127,  130,  130,  117,  131,  131,  119,  135,
      135,  136,  136,  137,  137,  264,  130,  138,  138,  132,
      134,  263,  139,  139,  140,  140,  129,  262,  131,  141,
      141,  196,  142,  142,  143,  143,  145,  145,  144,  144,
      146,  146,  147,  147,  148,  148,  149,  149,  238,  150,

      150,  151,  151,  136,  154,  137,  237,  135,  152,  152,
      153,  153,  156,  138,  139,  236,  154,  235,  167,  167,
      156,  168,  168,  196,  166,  166,  140,  173,  173,  165,
      165,  143,  169,  169,  234,  141,  142,  144,  233,  168,
      145,  150,  167,  203,  146,  148,  149,  147,  153,  201,
      154,  151,  165,  166,  156,  169,  170,  170,  171,  171,
      172,  172,  152,  155,  175,  175,  174,  174,  179,  179,
      171,  170,  176,  176,  200,  155,  155,  177,  177,  199,
      173,  178,  178,  198,  155,  155,  155,  155,  155,  155,
      164,  180,  180,  181,  181,  184,  184,  183,  183,  163,

      182,  182,  185,  185,  186,  186,  187,  187,  172,  155,
      188,  188,  162,  155,  155,  155,  155,  155,  155,  157,
      174,  179,  189,  189,  176,  161,  177,  157,  157,  180,
      178,  181,  160,  184,  190,  190,  157,  157,  157,  157,
      157,  157,  182,  183,  191,  191,  187,  192,  192,  158,
      186,  193,  193,  204,  204,  185,  125,  188,  123,  205,
      205,  157,  206,  206,  122,  157,  157,  157,  157,  157,
      157,  207,  207,  208,  208,  190,  121,  204,  120,  189,
      205,  209,  209,   85,  207,  206,  210,  210,  211,  211,
      212,  212,   78,  191,  213,  213,   77,  208,  209,  214,

      214,   65,  192,  215,  215,  193,  195,  216,  216,   63,
      218,  218,  217,  217,  219,  219,  223,  223,  195,  195,
      222,  222,   61,  210,   60,  220,  220,  195,  195,  195,
      195,  195,  195,  221,  221,  224,  224,  225,  225,  226,
      226,  211,  227,  227,  215,  228,  228,   27,  214,  216,
      229,  229,  195,   18,  230,  230,  195,  195,  195,  195,
      195,  195,  197,  217,  218,  220,    9,  222,  219,    0,
      197,  197,    0,  221,    0,  224,    0,  226,    0,  197,
      197,  197,  197,  197,  197,  231,  231,  228,  239,  239,
        0,  225,  230,  240,  240,  241,  241,  244,  244,  246,

      246,  243,  243,    0,  197,  242,  242,    0,  197,  197,
      197,  197,  197,  197,  243,    0,  242,  245,  245,  244,
      240,  241,  247,  247,  248,  248,  249,  249,    0,  245,
        0,  231,  250,  250,  251,  251,  252,  252,  253,  253,
      254,  254,    0,  246,  255,  255,  256,  256,  257,  257,
      258,  258,  259,  259,  260,  260,  261,  261,  268,  269,
      269,  270,  270,  272,  272,  268,  268,  271,  271,    0,
      250,    0,  273,  273,  274,  274,  275,  275,  252,  276,
      276,  277,  277,    0,  251,  273,    0,  269,    0,  270,
      278,  278,  253,  271,    0,  259,    0,  255,  279,  279,

      272,  260,    0,  261,  258,  280,  280,  281,  281,  282,
      282,  283,  283,  290,  290,    0,  275,  291,  291,    0,
      292,  292,  293,  293,  294,  294,  295,  295,    0,  290,
        0,  276,  278,    0,  293,  294,  296,  296,  297,  297,
      298,  298,  299,  299,  304,  304,    0,  280,  292,  305,
      305,  306,  306,  283,  307,  307,  308,  308,  309,  309,
      314,  314,  313,    0,  306,  315,  315,    0,  295,  313,
      313,  314,  319,  319,  307,  318,  318,  321,  321,  297,
        0,  305,  323,  323,    0,    0,    0,    0,    0,    0,
        0,    0,  315,    0,    0,  318,    0,    0,    0,    0,

        0,    0,    0,    0,  321,  327,  327,  327,  327,  327,
      327,  327,  327,  328,  328,  328,  328,  328,  328,  328,
      328,  329,    0,  329,  329,  329,  329,  329,  329,  330,
        0,  330,    0,  330,  330,  330,  330,  331,  331,  331,
      331,  332,  332,  332,    0,    0,  332,  333,  333,  333,
        0,    0,  333,  334,  334,  334,  334,  334,  334,  334,
      334,  335,  335,  335,  335,  336,  336,  337,  337,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326
    } ;

#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "./tokenizer.l"
#define INITIAL 0
/***************************************************************************
                          tokenizer.l  -  description
                             -------------------
    begin                : Mon Mar 15 1999
    copyright            : (C) 1999 by Jonas Nordin
    email                : jonas.nordin@syncom.se
   
 ***************************************************************************/
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   * 
 *                                                                         *
 ***************************************************************************/
#define COMMENT 1
#define PREPARSER 2
#define PPCOMMENT 3

#line 21 "./tokenizer.l"
  #include <stdlib.h>
  #include <qstring.h>
  #include <iostream.h>
  #include "tokenizer.h"
  #include "FlexLexer.h"

  /** This class is a stupid trick to make it possible 
   * to access the getText method. */
  class MyLexer : public yyFlexLexer
  {
    public:
    char *getText() {return yytext;};
  };

  /* Line where a comment starts. */
  int comment_start = -1;

  /* Line where a comment ends. */
  int comment_end = -1;

  /* Last parsed comment. */
  QString comment;

  /* Function prototypes */
  static bool beginComment(MyLexer *lex);
  static void inComment(MyLexer *lex);
  static bool endComment(MyLexer *lex);
#line 767 "tokenizer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 67 "./tokenizer.l"

    /*==============> Strip whitespace <==============*/
#line 897 "tokenizer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 970 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 69 "./tokenizer.l"
{}
	YY_BREAK
/*==============> Special keyword <==============*/
case 2:
YY_RULE_SETUP
#line 72 "./tokenizer.l"
{return CPCLASS;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "./tokenizer.l"
{return CPPUBLIC;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "./tokenizer.l"
{return CPPROTECTED;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "./tokenizer.l"
{return CPPRIVATE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "./tokenizer.l"
{return CPCONST;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "./tokenizer.l"
{return CPVOLATILE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "./tokenizer.l"
{return CPSTATIC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "./tokenizer.l"
{return CPVIRTUAL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "./tokenizer.l"
{return QTSIGNAL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "./tokenizer.l"
{return QTSLOT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "./tokenizer.l"
{return CPENUM;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "./tokenizer.l"
{return CPTYPEDEF;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "./tokenizer.l"
{return CPFRIEND;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "./tokenizer.l"
{return CPSTRUCT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "./tokenizer.l"
{return CPUNION;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "./tokenizer.l"
{return CPOPERATOR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "./tokenizer.l"
{return CPTEMPLATE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "./tokenizer.l"
{return CPTHROW;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "./tokenizer.l"
{return CPNAMESPACE;}
	YY_BREAK
/*==============> Ignored stuff <==============*/
/*========== added to avoid extern "C" trouble--rnolden 03232000====*/
case 21:
YY_RULE_SETUP
#line 94 "./tokenizer.l"
{}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 95 "./tokenizer.l"
{}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 96 "./tokenizer.l"
{}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 97 "./tokenizer.l"
{}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 98 "./tokenizer.l"
{}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 99 "./tokenizer.l"
{}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 100 "./tokenizer.l"
{}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 101 "./tokenizer.l"
{}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 102 "./tokenizer.l"
{}
	YY_BREAK
/*========== for ignoring qt-specific macros daniel 18012002 ===*/
case 30:
YY_RULE_SETUP
#line 104 "./tokenizer.l"
{}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "./tokenizer.l"
{}
	YY_BREAK
/*==============> Objective-C keyword <==============*/
case 32:
YY_RULE_SETUP
#line 108 "./tokenizer.l"
{return CPOBJCCLASS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 109 "./tokenizer.l"
{return CPOBJCINTERFACE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "./tokenizer.l"
{return CPOBJCPROTOCOL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 111 "./tokenizer.l"
{return CPOBJCPRIVATE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 112 "./tokenizer.l"
{return CPOBJCPROTECTED;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 113 "./tokenizer.l"
{return CPOBJCPUBLIC;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 114 "./tokenizer.l"
{return CPOBJCIMPLEMENTATION;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 115 "./tokenizer.l"
{return CPOBJCEND;}
	YY_BREAK
/*==============> String <==============*/
case 40:
YY_RULE_SETUP
#line 118 "./tokenizer.l"
{return STRING;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 119 "./tokenizer.l"
{return STRING;}
	YY_BREAK
/*==============> Normal operators <==============*/
case 42:
YY_RULE_SETUP
#line 122 "./tokenizer.l"
{return ':';}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "./tokenizer.l"
{return CLCL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 124 "./tokenizer.l"
{return '~';}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 125 "./tokenizer.l"
{return '=';}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 126 "./tokenizer.l"
{return '<';}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "./tokenizer.l"
{return '>';}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 128 "./tokenizer.l"
{return '&';}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 129 "./tokenizer.l"
{return '+';}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 130 "./tokenizer.l"
{return '-';}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 131 "./tokenizer.l"
{return '*';}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 132 "./tokenizer.l"
{return '/';}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 133 "./tokenizer.l"
{return '%';}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 134 "./tokenizer.l"
{return '|';}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 135 "./tokenizer.l"
{return '^';}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 136 "./tokenizer.l"
{return '!';}
	YY_BREAK
/*==============> End of Phrase <==============*/
case 57:
YY_RULE_SETUP
#line 139 "./tokenizer.l"
{return ';';}
	YY_BREAK
/*==============> Comma <==============*/
case 58:
YY_RULE_SETUP
#line 142 "./tokenizer.l"
{return ',';}
	YY_BREAK
/*==============> Paranthesis <==============*/
case 59:
YY_RULE_SETUP
#line 145 "./tokenizer.l"
{return '(';}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 146 "./tokenizer.l"
{return ')';}
	YY_BREAK
/*==============> Brackets <==============*/
case 61:
YY_RULE_SETUP
#line 149 "./tokenizer.l"
{return '{';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 150 "./tokenizer.l"
{return '}';}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 151 "./tokenizer.l"
{return '[';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 152 "./tokenizer.l"
{return ']';}
	YY_BREAK
/*==============> Identifiers <==============*/
case 65:
YY_RULE_SETUP
#line 155 "./tokenizer.l"
{return ID;}
	YY_BREAK
/*==============> Numbers <==============*/
case 66:
YY_RULE_SETUP
#line 158 "./tokenizer.l"
{return NUM;}
	YY_BREAK
/*==============> Skip preprocessor directives <==============*/
case 67:
YY_RULE_SETUP
#line 161 "./tokenizer.l"
{BEGIN (PREPARSER);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 162 "./tokenizer.l"
{ BEGIN (0);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 163 "./tokenizer.l"
{beginComment((MyLexer *) this);
                                  BEGIN (PPCOMMENT);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 165 "./tokenizer.l"
{ endComment((MyLexer *) this);
                       BEGIN (PREPARSER); }
	YY_BREAK
/*==============> Strip // comments <==============*/
case 71:
YY_RULE_SETUP
#line 169 "./tokenizer.l"
{}
	YY_BREAK
/*==============> Strip comments <==============*/
case 72:
YY_RULE_SETUP
#line 172 "./tokenizer.l"
{beginComment((MyLexer *) this);
                                  BEGIN (COMMENT);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 175 "./tokenizer.l"
{ endComment((MyLexer *) this);
                       BEGIN (0); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 178 "./tokenizer.l"
{inComment((MyLexer *) this);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 179 "./tokenizer.l"
{inComment((MyLexer *) this);}
	YY_BREAK
/*==============> All other characters are ignored <==============*/
case 76:
YY_RULE_SETUP
#line 182 "./tokenizer.l"
{}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 183 "./tokenizer.l"
{}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 185 "./tokenizer.l"
ECHO;
	YY_BREAK
#line 1405 "tokenizer.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(PREPARSER):
			case YY_STATE_EOF(PPCOMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 326);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#include<unistd.h>
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 185 "./tokenizer.l"


static bool beginComment(MyLexer *lex)
{
 comment_start = lex->lineno();
 comment="/*";
 return true;
}

static void inComment(MyLexer *lex)
{
  char *text=lex->getText();
  comment+=text;
};

static bool endComment(MyLexer *lex)
{
 comment_end = lex->lineno();
 comment+="*/";
 return true;
}

