#define CMAKE_TESTS_PROJECTS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/manual"
#define CMAKE_INSTALLED_MODULES "${DATA_INSTALL_DIR}/cmake/modules"
#define TEST_PREFIX_PATH "${CMAKE_PREFIX_PATH};${CMAKE_INSTALL_PREFIX}"
#define TEST_ENV_PREFIX_PATH "$ENV{CMAKE_PREFIX_PATH}"
#define TEST_ENV_LIBRARY_PATH "$ENV{CMAKE_LIBRARY_PATH}"
#define TEST_ENV_INCLUDE_PATH "$ENV{CMAKE_INCLUDE_PATH}"

