#define CMAKE_TESTS_PROJECTS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/manual"
#define CMAKE_INSTALLED_MODULES "${DATA_INSTALL_DIR}/cmake/modules"
#define TEST_PREFIX_PATH "${CMAKE_PREFIX_PATH};${CMAKE_INSTALL_PREFIX}"

