#!/usr/bin/perl

use gideon;


initGideon();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kpartapp/app.kdevelop",      "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.cvs",    "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-Makefile.am",     "${dest}/Makefile.am" );
install( "${src}/template-common/kde-configure.in.in", "${dest}/configure.in.in" );
install( "${src}/template-common/kde-part.desktop",    "${dest}/src/${APPNAMELC}_part.desktop" );
install( "${src}/template-common/kde-app.desktop",     "${dest}/src/${APPNAMELC}.desktop" );
install( "${src}/template-common/kde-app.lsm",         "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/hi16-app-app.png",    "${dest}/src/hi16-app-${APPNAMELC}.png");
install( "${src}/template-common/hi32-app-app.png",    "${dest}/src/hi32-app-${APPNAMELC}.png");
install( "${src}/template-common/kde-po-Makefile.am",  "${dest}/po/Makefile.am" );
install( "${src}/template-kpartapp/subdirs",           "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kpartapp/src-Makefile.am",   "${dest}/src/Makefile.am" );
install( "${src}/template-kpartapp/app.cpp",           "${dest}/src/${APPNAMELC}.cpp" );
install( "${src}/template-kpartapp/app.h",             "${dest}/src/${APPNAMELC}.h" );
install( "${src}/template-kpartapp/app_part.cpp",      "${dest}/src/${APPNAMELC}_part.cpp" );
install( "${src}/template-kpartapp/app_part.h",        "${dest}/src/${APPNAMELC}_part.h" );
install( "${src}/template-kpartapp/main.cpp",          "${dest}/src/main.cpp" );
install( "${src}/template-kpartapp/app_part.rc",       "${dest}/src/${APPNAMELC}_part.rc" );
install( "${src}/template-kpartapp/app_shell.rc",      "${dest}/src/${APPNAMELC}_shell.rc" );

print "Finished\n";
