#!/usr/bin/perl

use gideon;

initGideon();
installLicense();

print "Installing application sources\n";
install( "${src}/template-kdevpartjava/src-Makefile.am", "${dest}/Makefile.am" );
install( "${src}/template-kdevpartjava/kdevpartjava_part.java",  "${dest}/${APPNAME}Part.java" );
install( "${src}/template-kdevpartjava/kdevpartjava_widget.java",  "${dest}/${APPNAME}Widget.java" );
install( "${src}/template-kdevpartjava/kdevpartjava_factory.cpp",  "${dest}/${APPNAMELC}_factory.cpp" );
install( "${src}/template-kdevpartjava/kdevpartjava_factory.h",    "${dest}/${APPNAMELC}_factory.h" );
install( "${src}/template-kdevpartjava/kdevpartjava_factory.java",    "${dest}/${APPNAME}Factory.java" );
install( "${src}/template-kdevpartjava/kdevpartjava_part.rc",   "${dest}/kdevpartjava_${APPNAMELC}.rc" );
install( "${src}/template-kdevpartjava/kdevpartjava.desktop",   "${dest}/kdevpartjava_${APPNAMELC}.desktop" );

print "Finished\n";
