#!/usr/bin/perl

use kdevelop;

initKDevelop();
installFileTemplate();
installLicense();
installAdmin();
installGNU();
installDocbook();

print "Installing project file\n";
install( "${src}/template-kpartplugin/plugin.kdevelop",        "${dest}/${APPNAMELC}.kdevelop" );

print "Installing application framework\n";
mkdir( "${dest}/src", 0777 );
mkdir( "${dest}/po", 0777 );
install( "${src}/template-common/kde-Makefile.cvs",            "${dest}/Makefile.cvs" );
install( "${src}/template-common/kde-Makefile.am",             "${dest}/Makefile.am" );
install( "${src}/template-common/kde-configure.in.in",         "${dest}/configure.in.in" );
install( "${src}/template-common/kde-app.lsm",                 "${dest}/src/${APPNAMELC}.lsm" );
install( "${src}/template-common/kde-po-Makefile.am",          "${dest}/po/Makefile.am" );
install( "${src}/template-kpartplugin/subdirs",                "${dest}/subdirs" );

print "Installing application sources\n";
install( "${src}/template-kpartplugin/src-Makefile.am",        "${dest}/src/Makefile.am" );
install( "${src}/template-kpartplugin/plugin_app.cpp",         "${dest}/src/plugin_${APPNAMELC}.cpp" );
install( "${src}/template-kpartplugin/plugin_app.h",           "${dest}/src/plugin_${APPNAMELC}.h" );
install( "${src}/template-kpartplugin/plugin_app.rc",          "${dest}/src/plugin_${APPNAMELC}.rc" );
install( "${src}/template-kpartplugin/hi16-action-plugin.png", "${dest}/src/hi16-action-plugin.png");
install( "${src}/template-kpartplugin/hi22-action-plugin.png", "${dest}/src/hi32-action-plugin.png");

print "Finished\n";
